Repository googleapis/python-bigquery-dataframes, pull requests merged in 2023-12, with the labels that each got.

#242 feat: add DataFrame.select_dtypes method
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: m

#243 docs: add examples for dataframe.cummin, dataframe.cummax, dataframe.…
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#248 docs: correct the params rendering for `ml.remote` and `ml.ensemble` modules
  bigframes/ml/remote.py
  docs/templates/toc.yml
  third_party/bigframes_vendored/sklearn/ensemble/_forest.py
Labels: automerge, api: bigquery, size: m

#253 docs: Fix return annotation in API docstrings
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: m

#256 feat: add nunique method to Series/DataFrameGroupby
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: automerge, api: bigquery, size: s

#245 fix: fix value_counts column label for normalize=True
  bigframes/core/block_transforms.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
Labels: automerge, api: bigquery, size: s

#257 docs: add code samples for `shape` and `head`
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#265 fix: enfore pandas version requirement <2.1.4
  setup.py
Labels: automerge, api: bigquery, size: xs

#264 feat: add ARIMAPlus.predict parameters
  bigframes/ml/core.py
  bigframes/ml/forecasting.py
  bigframes/ml/sql.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_forecasting.py
  tests/unit/ml/test_sql.py
Labels: automerge, api: bigquery, size: m

#233 feat: support dataframe.loc with conditional columns selection
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#252 docs: add example for dataframe.melt, dataframe.pivot, dataframe.stac…
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#234 docs: add example to dataframe.nlargest, dataframe.nsmallest, datafra…
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#268 fix: pin prerelease tests to pandas 2.1.3 to unblock e2e tests
  noxfile.py
Labels: automerge, api: bigquery, size: xs

#160 test: migrate e2e presubmit tests to bigframes-load-testing project
  .kokoro/continuous/e2e.cfg
  .kokoro/presubmit/e2e.cfg
  CONTRIBUTING.rst
  bigframes/remote_function.py
  notebooks/generative_ai/large_language_models.ipynb
  notebooks/regression/easy_linear_regression.ipynb
  owlbot.py
  samples/snippets/gen_ai_model_test.py
  samples/snippets/load_data_from_biquery_job_test.py
  samples/snippets/quickstart_test.py
  samples/snippets/remote_function_test.py
  scripts/create_test_model_vertex.py
  scripts/setup-project-for-testing.sh
  tests/system/conftest.py
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_pipeline.py
  tests/system/large/test_remote_function.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_decomposition.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_remote_function.py
  tests/system/utils.py
Labels: automerge, api: bigquery, size: xl

#258 fix: replaced raise `NotImplementedError` with return `NotImplemented`
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: xs

#141 docs: add sample for getting started with BQML
  samples/snippets/bqml_getting_started_test.py
  samples/snippets/conftest.py
Labels: automerge, samples, api: bigquery, size: m

#249 docs: add code samples for `values` and `value_counts`
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#270 chore: filter errors explicitly caught in BF dashboard
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: xs

#199 chore: deprecate `use_regional_endpoints`
  bigframes/_config/bigquery_options.py
Labels: api: bigquery, size: s

#198 feat: Add filters and columns arguments to read_gbq for enhanced data querying
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: m

#184 fix: increase recursion limit, cache compilation tree hashes
  bigframes/core/nodes.py
  bigframes/pandas/__init__.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#272 feat: add module/class level api tracking
  bigframes/core/log_adapter.py
  tests/unit/core/test_log_adapter.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: s

#53 deps: migrate to `ibis-framework >= "7.1.0"`
  bigframes/core/compile/compiled.py
  bigframes/core/reshape/__init__.py
  bigframes/operations/__init__.py
  bigframes/operations/aggregations.py
  bigframes/remote_function.py
  bigframes/session/__init__.py
  mypy.ini
  noxfile.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/test_ibis.py
  tests/unit/resources.py
  third_party/bigframes_vendored/ibis/backends/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/backends/bigquery/compiler.py
  third_party/bigframes_vendored/ibis/expr/operations/analytic.py
  third_party/bigframes_vendored/ibis/expr/operations/json.py
  third_party/bigframes_vendored/ibis/expr/operations/reductions.py
Labels: automerge, api: bigquery, size: l

#278 docs: add code snippets for explore query result page
  samples/snippets/explore_query_result_test.py
Labels: automerge, api: bigquery, size: m

#255 refactor: move query execution from ArrayValue to Session
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/indexes/index.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: automerge, api: bigquery, size: l

#254 feat: Add IntervalIndex support to bigframes.pandas.cut
  bigframes/core/reshape/__init__.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: api: bigquery, size: m

#222 fix: dataframes to_gbq now creates dataset if it doesn't exist
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#281 chore: use latest pip in nightly builds
  .kokoro/release-nightly.sh
  noxfile.py
  setup.py
Labels: api: bigquery, size: xs

#261 feat: add replace method to DataFrame
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l

#273 fix: fix DataFrameGroupby.agg() issue with as_index=False
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_groupby.py
  tests/system/small/test_multiindex.py
Labels: automerge, api: bigquery, size: m

#274 chore: Remove symlink that breaks local testing
  docs/samples
Labels: automerge, api: bigquery, size: xs

#246 fix: use setuptools.find_namespace_packages
  setup.py
Labels: automerge, api: bigquery, size: xs

#280 docs: code samples for `Series.{sum, mean, min, max}`, `astype`
  bigframes/dtypes.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: m

#285 fix: make `Series.str.replace` work for simple strings
  bigframes/operations/__init__.py
  tests/system/small/operations/test_strings.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#283 feat: specific pyarrow mappings for decimal, bytes types
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/groupby/__init__.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/series.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_core.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_imported.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_preprocessing.py
  tests/system/small/ml/test_remote.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  tests/system/utils.py
  tests/unit/test_dtypes.py
Labels: api: bigquery, size: l

#284 docs: code samples for `drop` and `fillna`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: m

#282 docs: code samples for `reset_index` and `sort_values`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: l

#289 docs: code samples for `isna`, `isnull`, `dropna`, `isin`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: m

#287 docs: code samples for `Series.{add, replace, unique, T, transpose}`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#259 feat: Add dataframe.to_html
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: m

#292 fix: exclude pandas 2.2.0rc0 to unblock prerelease tests
  noxfile.py
Labels: automerge, api: bigquery, size: s

#291 docs: fix the rendering for `get_dummies`
  third_party/bigframes_vendored/pandas/core/reshape/encoding.py
Labels: automerge, api: bigquery, size: xs

#286 Fix: Update dataframe.to_gbq to dedup column names.
  bigframes/dataframe.py
  tests/system/small/test_dataframe_io.py
Labels: automerge, api: bigquery, size: m

#290 docs: code samples for `Series.{map, to_list, count}`
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: m
