Repository googleapis/python-bigquery-dataframes, pull requests merged in 2023-10, with the labels that each got.

#79 fix: fix df/series.iloc by list with multiindex
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#73 feat: add multi-column dataframe merge
  bigframes/core/blocks.py
  bigframes/core/joins/single_column.py
  bigframes/core/utils.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/reshape/merge.py
Labels: api: bigquery, size: l

#84 chore: fix flaky system tests
  tests/system/small/test_pandas_options.py
  tests/system/small/test_session.py
Labels: automerge, api: bigquery, size: s

#77 fix: avoid `403 response too large to return` error with `read_gbq` and large query results
  bigframes/core/__init__.py
  bigframes/core/io.py
  bigframes/session.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_decomposition.py
  tests/system/small/test_session.py
  tests/unit/core/test_io.py
Labels: automerge, api: bigquery, size: l

#71 feat: support STRUCT data type with `Series.struct.field` to extract child fields
  .kokoro/build.sh
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/base.py
  bigframes/operations/structs.py
  bigframes/series.py
  noxfile.py
  tests/system/small/test_dataframe.py
  tests/unit/test_dtypes.py
  third_party/bigframes_vendored/pandas/core/arrays/__init__.py
  third_party/bigframes_vendored/pandas/core/arrays/arrow/__init__.py
  third_party/bigframes_vendored/pandas/core/arrays/arrow/accessors.py
  third_party/bigframes_vendored/sklearn/__init__.py
  third_party/bigframes_vendored/sklearn/ensemble/__init__.py
  third_party/bigframes_vendored/xgboost/__init__.py
Labels: automerge, api: bigquery, size: l

#74 feat: add idxmin, idxmax to series, dataframe
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#40 fix: change return type of `Series.loc[scalar]`
  bigframes/core/indexers.py
  bigframes/ml/model_selection.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#81 feat: add ml.preprocessing.KBinsDiscretizer
  bigframes/ml/compose.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_preprocessing.py
  tests/unit/ml/test_compose.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/preprocessing/_discretization.py
Labels: api: bigquery, size: l

#80 feat: add aliases for several series properties
  bigframes/series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#68 feat: Allow df.drop to take an index object
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#82 refactor: simplify ArrayValue public interface
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexes/index.py
  bigframes/core/joins/row_identity.py
  bigframes/core/joins/single_column.py
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/unit/test_core.py
Labels: api: bigquery, size: l

#76 feat: add equals methods to series/dataframe
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#93 fix: change the invalid url in docs
  bigframes/ml/base.py
Labels: api: bigquery, size: xs

#97 docs: add more preprocessing models into the docs menu.
  docs/templates/toc.yml
  third_party/bigframes_vendored/sklearn/preprocessing/_data.py
  third_party/bigframes_vendored/sklearn/preprocessing/_encoder.py
Labels: api: bigquery, size: s

#89 refactor: refactor the directory of the notebooks
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/regression/bq_dataframes_ml_linear_regression.ipynb
  noxfile.py
Labels: automerge, api: bigquery, size: l

#88 feat: add level param to DataFrame.stack
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
Labels: api: bigquery, size: m

#87 feat: use default session connection
  bigframes/_config/bigquery_options.py
  bigframes/clients.py
  bigframes/ml/llm.py
  bigframes/remote_function.py
  bigframes/session.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_remote_function.py
  tests/unit/test_clients.py
Labels: api: bigquery, size: l

#94 fix: create session dataset for remote functions only when needed
  bigframes/remote_function.py
  bigframes/session.py
  tests/system/conftest.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_session.py
Labels: automerge, api: bigquery, size: m

#91 feat: Support compression in `to_parquet`
  bigframes/dataframe.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#102 chore: address last comments of PR#87
  bigframes/clients.py
  bigframes/ml/llm.py
  bigframes/remote_function.py
  bigframes/session.py
  tests/unit/test_clients.py
Labels: automerge, api: bigquery, size: m

#103 fix: send BigQuery cancel request when canceling bigframes process
  bigframes/formatting_helpers.py
Labels: api: bigquery, size: s

#101 feat!: rename `bigframes.pandas.reset_session` to `close_session`
  README.rst
  bigframes/__init__.py
  bigframes/_config/bigquery_options.py
  bigframes/core/global_session.py
  bigframes/pandas/__init__.py
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/regression/bq_dataframes_ml_linear_regression.ipynb
  samples/snippets/quickstart_test.py
  samples/snippets/remote_function_test.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_pandas_options.py
  tests/unit/test_pandas.py
Labels: automerge, api: bigquery, size: m

#92 refactor: all ArrayValue ops return only ArrayValue
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/indexes/index.py
  bigframes/core/joins/name_resolution.py
  bigframes/core/joins/row_identity.py
  bigframes/core/joins/single_column.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/operations/base.py
  bigframes/series.py
Labels: api: bigquery, size: l

#106 docs: add open-source link in API doc
  README.rst
Labels: automerge, api: bigquery, size: xs

#105 docs: update ML overview API doc
  README.rst
Labels: api: bigquery, size: s

#111 style: improve cancellation string
  bigframes/formatting_helpers.py
Labels: automerge, api: bigquery, size: s

#112 perf: if primary keys are defined, `read_gbq` avoids copying table data
  bigframes/core/indexers.py
  bigframes/session.py
  noxfile.py
  tests/system/conftest.py
  tests/system/small/test_session.py
Labels: automerge, api: bigquery, size: m

#107 feat: add AtIndexer getitems
  bigframes/core/indexers.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#98 feat: Support external packages in `remote_function`
  bigframes/pandas/__init__.py
  bigframes/remote_function.py
  bigframes/session.py
  samples/snippets/remote_function.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#114 docs: add documentation for `Series.struct.field` and `Series.struct.explode`
  bigframes/core/indexers.py
  bigframes/operations/structs.py
  docs/reference/bigframes.pandas/series.rst
  docs/templates/toc.yml
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#117 feat: add `bigframes.options.bigquery.application_name` for partner attribution
  bigframes/_config/bigquery_options.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/clients.py
  tests/unit/_config/test_bigquery_options.py
  tests/unit/resources.py
  tests/unit/session/__init__.py
  tests/unit/session/test_clients.py
  tests/unit/session/test_session.py
Labels: automerge, api: bigquery, size: l

#113 fix: support multiindex for three loc getitem overloads
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#85 feat: use ArrowDtype for STRUCT columns in `to_pandas`
  bigframes/core/blocks.py
  bigframes/dtypes.py
  noxfile.py
  tests/system/small/test_dataframe_io.py
  third_party/bigframes_vendored/google_cloud_bigquery/LICENSE
  third_party/bigframes_vendored/google_cloud_bigquery/__init__.py
  third_party/bigframes_vendored/google_cloud_bigquery/_pandas_helpers.py
  third_party/bigframes_vendored/google_cloud_bigquery/tests/__init__.py
  third_party/bigframes_vendored/google_cloud_bigquery/tests/unit/__init__.py
  third_party/bigframes_vendored/google_cloud_bigquery/tests/unit/test_pandas_helpers.py
Labels: automerge, api: bigquery, size: l

#67 feat: Implement DataFrame.dot for matrix multiplication
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/data/matrix_2by3.json
  tests/data/matrix_2by3.jsonl
  tests/data/matrix_3by4.json
  tests/data/matrix_3by4.jsonl
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l

#121 chore: remove unneeded scripts, no longer need THIRD_PARTY_NOTICES
  .kokoro/release-nightly.sh
  scripts/generate_third_party_notices.py
  scripts/update_firebase_docs_site.sh
  scripts/update_x20_docs_site.sh
Labels: automerge, api: bigquery, size: l

#124 feat: add back `reset_session` as an alias for `close_session`
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: xs

#127 feat: change `query` parameter to `query_or_table` in `read_gbq`
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: automerge, api: bigquery, size: s

#123 refactor: Tweak notebooks to test minimal IAM permissions
  notebooks/dataframes/dataframe.ipynb
  notebooks/getting_started/ml_fundamentals.ipynb
  notebooks/regression/easy_linear_regression.ipynb
Labels: api: bigquery, size: xl

#125 docs: add runnable code samples for reading methods
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/io/gbq.py
  third_party/bigframes_vendored/pandas/io/parquet.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
  third_party/bigframes_vendored/pandas/io/pickle.py
Labels: samples, api: bigquery, size: m

#118 test: add sample code for use BigFrames developer guide
  samples/snippets/load_data_from_bigquery_test.py
  samples/snippets/load_data_from_csv_test.py
  samples/snippets/pandas_methods_test.py
  samples/snippets/set_options_test.py
Labels: samples, api: bigquery, size: m

#128 fix: expose `bigframes.pandas.reset_session` as a public API
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: xs

#131 refactor: move DDL gen to `bigframes.session._io`, add missing test
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/__init__.py
  bigframes/session/_io/bigquery.py
  tests/unit/session/test_io_bigquery.py
Labels: automerge, api: bigquery, size: s

#135 fix: use series's own session in series.reindex listlike case
  bigframes/series.py
Labels: automerge, api: bigquery, size: xs

#129 docs: add runnable code samples for DataFrames I/O methods and property
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: samples, api: bigquery, size: m

#143 test: allow for alternative PCA solutions in tests
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_pipeline.py
Labels: automerge, api: bigquery, size: s

#144 ci: Disable presubmit LLM tests temporarily
  tests/system/small/ml/test_llm.py
Labels: automerge, api: bigquery, size: s

#148 Revert "ci: Disable presubmit LLM tests temporarily (#144)"
  tests/system/small/ml/test_llm.py
Labels: automerge, api: bigquery, size: s

#132 refactor: make `to_pandas()` call `to_arrow()` and use local dtypes in DataFrame construction
  bigframes/core/blocks.py
  bigframes/core/indexes/index.py
  bigframes/dtypes.py
  bigframes/session/__init__.py
  bigframes/session/_io/pandas.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  tests/unit/session/test_io_pandas.py
  tests/unit/test_dtypes.py
Labels: automerge, api: bigquery, size: l

#146 test: Log slowest tests durations
  noxfile.py
Labels: automerge, api: bigquery, size: xs

#137 docs: link to ML.EVALUATE BQML page for score() methods
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  third_party/bigframes_vendored/sklearn/base.py
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
Labels: automerge, api: bigquery, size: s

#138 fix: don't override the global logging config
  bigframes/clients.py
  bigframes/remote_function.py
Labels: automerge, api: bigquery, size: xs

#152 fix: use indexee's session for loc listlike cases
  bigframes/core/indexers.py
Labels: automerge, api: bigquery, size: xs

#104 feat: add pandas.qcut
  bigframes/core/reshape/__init__.py
  bigframes/operations/aggregations.py
  bigframes/pandas/__init__.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: automerge, api: bigquery, size: m

#115 feat: add unstack to series, add level param
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: m

#136 feat: add `DataFrame.to_pandas_batches()` to download large `DataFrame` objects
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/session/_io/pandas.py
  tests/system/small/test_dataframe_io.py
  tests/unit/session/test_io_pandas.py
Labels: automerge, api: bigquery, size: m

#134 fix: resolve plotly rendering issue by using ipython html for job pro…
  bigframes/formatting_helpers.py
  tests/system/small/test_progress_bar.py
Labels: automerge, api: bigquery, size: m

#150 fix: fix bug with column names under repeated column assignment
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: s

#147 test: refactor remote function tests
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  tests/unit/test_remote_function.py
Labels: automerge, api: bigquery, size: l

#116 feat: add dataframe melt
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: m

#153 docs: add artithmetic df sample code
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: samples, api: bigquery, size: l

#139 feat: Implement operator `@` for `DataFrame.dot`
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
Labels: automerge, api: bigquery, size: m

#154 test: add code snippets for loading data from BigQuery Job
  samples/snippets/load_data_from_biquery_job_test.py
Labels: api: bigquery, size: m

#163 docs: fix indentation on `read_gbq_function` code sample
  bigframes/session/__init__.py
Labels: automerge, samples, api: bigquery, size: s
