Repository googleapis/python-bigquery-dataframes, pull requests merged in 2023-11, with the labels that each got.

#149 feat: add pd.get_dummies
  bigframes/pandas/__init__.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/concat.py
  third_party/bigframes_vendored/pandas/core/reshape/encoding.py
  third_party/bigframes_vendored/pandas/core/reshape/merge.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: api: bigquery, size: l

#159 test: add code snippets for using bigframes.ml
  samples/snippets/clustering_model_test.py
  samples/snippets/gen_ai_model_test.py
  samples/snippets/regression_model_test.py
Labels: api: bigquery, size: m

#157 feat: add interpolate() to series and dataframe
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#158 feat: `to_gbq` without a destination table writes to a temporary table
  bigframes/constants.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/unit/resources.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/test_dataframe.py
  tests/unit/test_pandas.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: m

#161 feat: support 32k text-generation and multilingual embedding models
  bigframes/ml/llm.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#109 fix: use table clone instead of system time for `read_gbq_table`
  bigframes/constants.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: m

#164 feat: add __iter__, iterrows, itertuples, keys methods
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: automerge, api: bigquery, size: m

#171 revert: use table clone instead of system time for `read_gbq_table` (#109)
  bigframes/constants.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: m

#174 fix: update default temp table expiration to 7 days
  bigframes/constants.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: m

#180 fix: deprecate the `remote_service_type` in llm model
  bigframes/ml/llm.py
Labels: api: bigquery, size: s

#173 feat: support `series.at[row_label] = scalar`
  bigframes/core/indexers.py
  tests/system/small/test_series.py
Labels: automerge, api: bigquery, size: s

#172 fix: match pandas behavior when assigning listlike to empty dfs
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: m

#181 fix: Use anonymous dataset instead of session dataset for temp tables
  bigframes/core/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
Labels: automerge, api: bigquery, size: m

#182 fix: for reset_index on unnamed multiindex, always use level_[n] label
  bigframes/core/blocks.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: s

#186 feat: support `date_series.astype("string[pyarrow]")` to cast DATE to STRING
  bigframes/dtypes.py
  tests/system/small/test_series.py
Labels: automerge, api: bigquery, size: xs

#176 feat: add 'cross' join support
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/single_column.py
  bigframes/core/joins/merge.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/pandas/__init__.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/reshape/merge.py
Labels: api: bigquery, size: m

#162 feat: add 'index', 'pad', 'nearest' interpolate methods
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: l

#177 docs: add llm kmeans notebook as an included example
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  noxfile.py
Labels: automerge, api: bigquery, size: l

#187 feat: add series.sample (identical to existing dataframe.sample)
  bigframes/series.py
  tests/system/small/test_series.py
Labels: automerge, samples, api: bigquery, size: s

#185 docs: Add docstring code samples for `Series.apply` and `DataFrame.map`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#175 fix: use random table when loading data for `read_csv`, `read_json`, `read_parquet`
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: xs

#193 fix: default to 7 days expiration for `read_csv`, `read_json`, `read_parquet`
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: s

#192 fix: use random table for `read_pandas`
  bigframes/core/__init__.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: s

#191 feat: read_gbq creates order deterministically without table copy
  bigframes/dataframe.py
  bigframes/ml/core.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/ml/test_cluster.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_decomposition.py
  tests/system/small/ml/test_forecasting.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_pandas_options.py
  tests/system/small/test_progress_bar.py
  tests/unit/ml/test_golden_sql.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/ibis/expr/operations/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/json.py
  third_party/bigframes_vendored/pandas/io/gbq.py
  third_party/bigframes_vendored/pandas/io/parquet.py
  third_party/bigframes_vendored/pandas/io/pickle.py
Labels: automerge, api: bigquery, size: l

#188 docs: add code samples for `read_gbq_function` using community UDFs
  bigframes/session/__init__.py
Labels: automerge, samples, api: bigquery, size: s

#194 feat: temporary resources no longer use BigQuery Sessions
  bigframes/ml/core.py
  bigframes/ml/sql.py
  bigframes/session/__init__.py
  tests/system/small/test_progress_bar.py
  tests/system/small/test_session.py
  tests/unit/ml/test_golden_sql.py
  tests/unit/ml/test_sql.py
  tests/unit/resources.py
  tests/unit/test_pandas.py
Labels: api: bigquery, size: l

#195 fix: all sort operation are now stable
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/groupby/__init__.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/dataframe.py
  bigframes/series.py
Labels: api: bigquery, size: m

#145 feat: log most recent API calls as `recent-bigframes-api-xx` labels on BigQuery jobs
  bigframes/core/groupby/__init__.py
  bigframes/core/log_adapter.py
  bigframes/core/nodes.py
  bigframes/core/window/__init__.py
  bigframes/dataframe.py
  bigframes/operations/datetimes.py
  bigframes/operations/strings.py
  bigframes/operations/structs.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/unit/core/test_log_adapter.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/test_compute_options.py
Labels: api: bigquery, size: l

#197 docs: add an example notebook about line graphs
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
  noxfile.py
Labels: automerge, api: bigquery, size: l

#210 fix: correctly handle null values when initializing fingerprint ordering
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: s

#204 feat!: model.predict returns all the columns
  bigframes/ml/cluster.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  notebooks/getting_started/ml_fundamentals.ipynb
  notebooks/regression/sklearn_linear_regression.ipynb
  tests/system/large/ml/test_cluster.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_cluster.py
  tests/system/small/ml/test_ensemble.py
  tests/system/small/ml/test_forecasting.py
  tests/system/small/ml/test_imported.py
  tests/system/small/ml/test_linear_model.py
  tests/system/small/ml/test_llm.py
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/xgboost/sklearn.py
Labels: automerge, api: bigquery, size: xl

#215 fix: invalid JSON type of the notebook
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
Labels: automerge, api: bigquery, size: xl

#216 feat: send warnings on LLM prediction partial failures
  bigframes/ml/llm.py
Labels: automerge, api: bigquery, size: m

#217 docs: code samples for `Series.where` and `Series.mask`
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#211 fix: avoid unnecessary row_number() on sort key for io
  bigframes/core/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/dataframe.py
Labels: automerge, api: bigquery, size: m

#203 docs: add code samples for df reshaping, function, merge, and join methods
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, samples, api: bigquery, size: m

#209 fix: dedup special character
  tests/unit/core/test_bf_utils.py
  third_party/bigframes_vendored/pandas/io/common.py
Labels: api: bigquery, size: s

#212 docs: add code samples for `index` and `column` properties
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#221 test: re-enable `system_prerelease` tests
  .kokoro/continuous/e2e.cfg
  .kokoro/presubmit/e2e.cfg
  noxfile.py
Labels: api: bigquery, size: m

#225 feat: add the recent api method for ML component
  bigframes/ml/cluster.py
  bigframes/ml/compose.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: s

#223 docs: code samples for dataframe.any, dataframe.all and dataframe.prod
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: samples, api: bigquery, size: m

#206 docs: make the code samples reflect default bq connection usage
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/remote_functions/remote_function.ipynb
  samples/snippets/remote_function.py
Labels: automerge, samples, api: bigquery, size: l

#227 docs: add examples for dataframe.min, dataframe.max and dataframe.sum
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#226 docs: code samples for `Series.dot` and `DataFrame.dot`
  bigframes/dataframe.py
  bigframes/operations/base.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: m

#232 docs: add examples for dataframe.kurt, dataframe.std, dataframe.count
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#228 docs: add examples for dataframe.mean, dataframe.median, dataframe.va…
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#200 fix: make to_pandas override enable_downsampling when sampling_method is manually set.
  bigframes/core/blocks.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#219 feat: add info and memory_usage methods to dataframe
  .pre-commit-config.yaml
  bigframes/_config/display_options.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  noxfile.py
  setup.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/config_init.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#205 fix: use anonymous dataset to create `remote_function`
  README.rst
  bigframes/remote_function.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: m

#236 fix: update the llm+kmeans notebook with recent change
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
Labels: automerge, api: bigquery, size: s

#239 test: fix prerelease tests
  noxfile.py
Labels: automerge, api: bigquery, size: xs

#229 fix: add df snapshots lookup for `read_gbq`
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: m

#237 feat: add remote vertex model support
  bigframes/ml/__init__.py
  bigframes/ml/core.py
  bigframes/ml/remote.py
  bigframes/ml/sql.py
  docs/reference/bigframes.ml/index.rst
  docs/reference/bigframes.ml/remote.rst
  docs/templates/toc.yml
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_remote.py
  tests/unit/ml/test_sql.py
Labels: automerge, api: bigquery, size: l

#247 fix: update the llm_kmeans notebook
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
Labels: api: bigquery, size: xs
