Repository googleapis/python-bigquery-dataframes, pull requests merged in 2023-09, with the labels that each got.

#15 chore: sync changes from internal repo
  .kokoro/build.sh
  .kokoro/continuous/nightly.cfg
  .kokoro/release-nightly.sh
  OWNERS
  bigframes/_config/bigquery_options.py
  bigframes/clients.py
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/indexes/index.py
  bigframes/core/joins/__init__.py
  bigframes/core/joins/merge.py
  bigframes/dataframe.py
  bigframes/ml/cluster.py
  bigframes/ml/core.py
  bigframes/ml/decomposition.py
  bigframes/ml/imported.py
  bigframes/ml/llm.py
  bigframes/ml/sql.py
  bigframes/operations/__init__.py
  bigframes/pandas/__init__.py
  bigframes/remote_function.py
  bigframes/series.py
  bigframes/session.py
  notebooks/experimental/longer_ml_demo.ipynb
  notebooks/getting_started/ml_fundamentals.ipynb
  notebooks/regression/sklearn_linear_regression.ipynb
  notebooks/remote_functions/remote_function.ipynb
  tests/system/conftest.py
  tests/system/large/ml/test_core.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_forecasting.py
  tests/system/large/ml/test_linear_model.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_ensemble.py
  tests/system/small/ml/test_imported.py
  tests/system/small/ml/test_linear_model.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_index.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_numpy.py
  tests/system/small/test_pandas.py
  tests/system/small/test_pandas_options.py
  tests/system/small/test_remote_function.py
  tests/system/small/test_series.py
  tests/unit/_config/test_bigquery_options.py
  tests/unit/conftest.py
  tests/unit/core/test_bf_utils.py
  tests/unit/resources.py
  tests/unit/test_core.py
  tests/unit/test_pandas.py
  tests/unit/test_session.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/reshape/merge.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: xl

#16 build: enable multi-scm for release job
  .github/release-trigger.yml
Labels: api: bigquery, size: xs

#17 fix(release): use correct directory name for release build config
  .kokoro/release/common.cfg
Labels: api: bigquery, size: s

#20 fix: make release.sh script for PyPI upload executable
  .kokoro/release.sh
Labels: api: bigquery, size: xs

#29 chore: use correct SCM name for release trigger
  .github/release-trigger.yml
Labels: automerge, api: bigquery, size: xs

#31 chore: enforce use of conventional commits
  .github/sync-repo-settings.yaml
Labels: automerge, api: bigquery, size: xs

#34 chore: sync internal changes to GitHub
  README.rst
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/core/window/__init__.py
  bigframes/dataframe.py
  bigframes/ml/core.py
  bigframes/ml/ensemble.py
  bigframes/ml/linear_model.py
  bigframes/operations/__init__.py
  bigframes/series.py
  bigframes/session.py
  tests/system/large/ml/test_linear_model.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_groupby.py
  tests/system/small/test_window.py
  tests/unit/ml/test_golden_sql.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
Labels: automerge, api: bigquery, size: l

#36 perf: simplify join order to use multiple order keys instead of string.
  bigframes/core/joins/single_column.py
Labels: api: bigquery, size: m

#41 fix: loosen filter items tests to accomodate shifting pandas impl
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#37 refactor: remove ibis references outside of arrayvalue code.
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/indexers.py
  bigframes/core/joins/single_column.py
  bigframes/core/scalar.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/unit/test_core.py
Labels: api: bigquery, size: l

#38 feat: add index `dtype`, `astype`, `drop`, `fillna`, aggregate attributes.
  bigframes/core/indexes/index.py
  bigframes/series.py
  tests/system/small/test_index.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: l

#45 perf: inline small `Series` and `DataFrames` in query text
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/base.py
  setup.py
  testing/constraints-3.9.txt
  tests/unit/core/__init__.py
  tests/unit/core/test_blocks.py
Labels: automerge, api: bigquery, size: l

#44 refactor: ml.sql to Object
  bigframes/ml/cluster.py
  bigframes/ml/compose.py
  bigframes/ml/core.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/globals.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_core.py
  tests/system/small/ml/conftest.py
  tests/unit/ml/test_golden_sql.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: l

#50 feat: add ml.preprocessing.LabelEncoder
  bigframes/ml/compose.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_preprocessing.py
  tests/unit/ml/test_compose.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/preprocessing/_label.py
Labels: api: bigquery, size: l

#47 perf: reimplement unpivot to use cross join rather than union
  bigframes/core/__init__.py
Labels: api: bigquery, size: m

#51 perf: add ability to cache dataframe and series to session table
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#56 feat: add ml.preprocessing.MaxAbsScaler
  bigframes/clients.py
  bigframes/ml/compose.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_preprocessing.py
  tests/unit/ml/test_compose.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/preprocessing/_data.py
  third_party/bigframes_vendored/sklearn/preprocessing/_encoder.py
Labels: api: bigquery, size: l

#52 feat: add axis param to simple df aggregations
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#49 fix: Fix header skipping logic in `read_csv`
  bigframes/session.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#60 fix: LabelEncoder params consistent with Sklearn
  bigframes/ml/base.py
  bigframes/ml/preprocessing.py
  tests/system/small/ml/test_preprocessing.py
  third_party/bigframes_vendored/sklearn/preprocessing/_label.py
Labels: api: bigquery, size: m

#59 feat: support casting string to integer or float
  bigframes/dtypes.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#54 feat: Add more index methods
  bigframes/core/block_transforms.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_index.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: l

#62 refactor: push down SQL generate logic in core.BqmlModelFactory
  bigframes/ml/core.py
  bigframes/ml/sql.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: m

#64 feat: add ml.preprocessing.MinMaxScaler
  bigframes/ml/compose.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_preprocessing.py
  tests/unit/ml/test_compose.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/preprocessing/_data.py
Labels: api: bigquery, size: l

#66 refactor: push down SQL generate logic in core.BqmlModel
  bigframes/ml/core.py
  bigframes/ml/sql.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: m

#65 fix: generate unique ids on join to avoid id collisions
  bigframes/core/joins/single_column.py
Labels: api: bigquery, size: m

#69 chore: remove Git-on-Borg check from config
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/continuous/nightly.cfg
Labels: api: bigquery, size: s

#57 feat: add update and align methods to dataframe
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l

#70 chore: add vertex sdk and Bigframes integration notebooks
  notebooks/vertex_sdk/sdk2_bigframes_pytorch.ipynb
  notebooks/vertex_sdk/sdk2_bigframes_sklearn.ipynb
  notebooks/vertex_sdk/sdk2_bigframes_tensorflow.ipynb
  noxfile.py
Labels: api: bigquery, size: xl

#63 feat: add df.unstack
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/utils.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l
