Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-06, with the labels that each got.

#741 fix: Resolve issue with unset thread-local options
  bigframes/_config/__init__.py
  tests/unit/_config/test_threaded_options.py
Labels: api: bigquery, size: m

#716 chore: type issue fix for _matplotlib/core.py
  bigframes/operations/_matplotlib/core.py
Labels: api: bigquery, size: xs

#718 chore: update type for _matplotlib/__init__.py
  bigframes/operations/_matplotlib/__init__.py
Labels: api: bigquery, size: xs

#742 chore: cleanup type errors in bigframes/operations/__init__.py
  bigframes/operations/__init__.py
Labels: api: bigquery, size: s

#706 feat: allow functions returned from `bpd.read_gbq_function` to execute outside of `apply`
  bigframes/functions/remote_function.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: m

#740 feat: support `score()` in GeminiTextGenerator
  bigframes/ml/llm.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#749 docs: fix ML.EVALUATE spelling
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/llm.py
  third_party/bigframes_vendored/sklearn/base.py
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
Labels: api: bigquery, size: s

#752 fix: ARIMAPlus loads auto_arima_min_order param
  tests/system/large/ml/test_forecasting.py
Labels: api: bigquery, size: xs

#753 docs: remove the unavailable LogisticRegression normal_equation strategy
  bigframes/ml/linear_model.py
  tests/system/large/ml/test_linear_model.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
Labels: api: bigquery, size: s

#738 refactor: New node type for cached subtrees
  bigframes/core/__init__.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#750 refactor: read transformers from TRANSFORM_ONLY type
  bigframes/ml/loader.py
Labels: api: bigquery, size: xs

#748 chore: cleanup type errors in tests/system/large/test_remote_function.py and…
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: s

#760 test: fix gemini-pro score test too large
  tests/system/conftest.py
  tests/system/load/test_llm.py
  tests/system/small/ml/conftest.py
Labels: api: bigquery, size: s

#751 refactor: use unit testable real python functions for most templated remote_functions code
  bigframes/functions/remote_function.py
  bigframes/functions/remote_function_template.py
  mypy.ini
  tests/unit/functions/test_remote_function_template.py
Labels: api: bigquery, size: l

#745 refactor: Move ibis type mappings to compile module
  bigframes/core/__init__.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/compile/schema_translator.py
  bigframes/core/local_data.py
  bigframes/core/nodes.py
  bigframes/dtypes.py
  bigframes/functions/remote_function.py
  tests/unit/core/test_dtypes.py
  tests/unit/test_remote_function.py
Labels: api: bigquery, size: xl

#758 feat: support fit() in GeminiTextGenerator
  bigframes/ml/llm.py
  tests/system/load/test_llm.py
Labels: automerge, api: bigquery, size: m

#756 chore: cleanup type errors in tests/system/small/test_index.py
  tests/system/small/test_index.py
Labels: api: bigquery, size: s

#754 chore: make benchmark to read subfolders and three groupby benchmarks.
  noxfile.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q1.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q2.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q3.py
Labels: api: bigquery, size: m

#736 feat: support `bigquery.vector_search()`
  bigframes/bigquery/__init__.py
  bigframes/core/sql.py
  tests/system/small/bigquery/test_vector_search.py
  tests/unit/core/test_sql.py
Labels: api: bigquery, size: l

#761 feat: support bytes type in `remote_function`
  bigframes/core/blocks.py
  bigframes/core/sql.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/functions/remote_function.py
  bigframes/functions/remote_function_template.py
  tests/system/small/test_remote_function.py
  tests/unit/functions/test_remote_function_template.py
Labels: api: bigquery, size: l

#746 fix: Improve to_pandas_batches for large results
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/load/test_large_tables.py
Labels: api: bigquery, size: m, status: ready for review

#755 chore: cleanup type errors in tests/system/small/ml/test_metrics.py
  bigframes/ml/metrics/_metrics.py
  tests/system/small/ml/test_metrics.py
Labels: api: bigquery, size: m

#762 chore: cleanup type errors in bigframes/core/indexes/base.py
  bigframes/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: s

#763 chore: cleanup type errors in tests/system/small/test_encryption.py
  tests/system/small/test_encryption.py
Labels: api: bigquery, size: s

#759 refactor: caching and aggregation don't require ordering
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/session/__init__.py
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: m

#766 chore: add overload to to_datetime and cleanup type errors in tests/system/small/test_pandas.py
  bigframes/pandas/__init__.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/tools/datetimes.py
Labels: api: bigquery, size: m

#767 chore: cleanup type errors in tests/unit/test_pandas.py
  bigframes/core/reshape/__init__.py
  bigframes/pandas/__init__.py
  tests/unit/test_pandas.py
Labels: api: bigquery, size: xs

#768 chore: update benchmark sorting logic, run environment, and add join …
  noxfile.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q1.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q2.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q3.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q4.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q5.py
Labels: api: bigquery, size: m

#765 chore: add q4-7 for groupby benchmark
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q4.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q5.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q6.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q7.py
  scripts/benchmark/db-benchmark/sort
Labels: api: bigquery, size: m

#769 chore: cleanup type errors in tests/system/small/operations/test_date…
  bigframes/series.py
  tests/system/small/operations/test_datetimes.py
Labels: api: bigquery, size: s

#757 refactor: create a basic set of SQL AST nodes
  bigframes/core/compile/googlesql/__init__.py
  bigframes/core/compile/googlesql/abc.py
  bigframes/core/compile/googlesql/expression.py
  bigframes/core/compile/googlesql/query.py
  tests/unit/core/compiler/__init__.py
  tests/unit/core/compiler/test_googlesql.py
Labels: api: bigquery, size: l

#773 chore: overload update for pre-commit mypy.
  bigframes/core/tools/datetimes.py
  bigframes/pandas/__init__.py
  third_party/bigframes_vendored/pandas/core/tools/datetimes.py
Labels: api: bigquery, size: s

#771 chore: cleanup type errors in tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#770 feat: add dataframe.insert
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#774 chore: cleanup type errors in tests/system/small/test_multiindex.py
  tests/system/small/test_multiindex.py
Labels: api: bigquery, size: s

#764 refactor: Refactor dtype conversions
  bigframes/core/compile/ibis_types.py
  bigframes/dtypes.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: l

#775 refactor: update core/sql.py selects to use SQL AST nodes and nodes updates.
  bigframes/core/compile/googlesql/__init__.py
  bigframes/core/compile/googlesql/expression.py
  bigframes/core/compile/googlesql/query.py
  bigframes/core/sql.py
  tests/unit/core/compiler/test_googlesql.py
Labels: api: bigquery, size: m

#777 chore: cleanup type errors in tests/system/small/test_session.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#779 chore: cleanup type errors in bigframes/core/indexers.py
  bigframes/core/indexers.py
Labels: api: bigquery, size: s

#780 chore: tests/system/load/test_large_tables.py
  tests/system/load/test_large_tables.py
Labels: api: bigquery, size: xs

#778 fix: allow `__repr__` to work with uninitialized DataFrame/Series/Index
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/unit/core/test_indexes.py
  tests/unit/test_dataframe.py
  tests/unit/test_series.py
Labels: api: bigquery, size: m

#785 chore: cleanup type errors in tests/system/small/operations/test_plot…
  tests/system/small/operations/test_plotting.py
Labels: api: bigquery, size: xs

#783 refactor: Remove ibis usage to define new dataframe objects
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  tests/unit/resources.py
  tests/unit/test_core.py
Labels: api: bigquery, size: m

#787 fix: Fix temp table creation retry errors from already exists.
  bigframes/session/_io/bigquery/__init__.py
Labels: api: bigquery, size: xs

#788 feat: include index columns in DataFrame.sql if they are named
  bigframes/dataframe.py
  tests/system/small/test_dataframe_io.py
Labels: api: bigquery, size: m

#791 feat: add groupby head API
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
Labels: api: bigquery, size: m

#781 chore: add sort benchmark
  scripts/benchmark/db-benchmark/sort
  scripts/benchmark/db-benchmark/sort/J1_1e9_NA_0_0/q1.py
Labels: api: bigquery, size: s

#798 fix: ensure numpy version matches in `remote_function` deployment
  bigframes/functions/remote_function.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: m

#786 refactor: Reduce compile interface to returning just SQL text
  bigframes/core/__init__.py
  bigframes/core/compile/__init__.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/nodes.py
  bigframes/session/__init__.py
  tests/unit/test_core.py
Labels: api: bigquery, size: l

#772 refactor: create internal session ordering mode flag
  bigframes/_config/bigquery_options.py
  bigframes/core/blocks.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/conftest.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: m

#784 refactor: update Select, update sql.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/googlesql/__init__.py
  bigframes/core/compile/googlesql/expression.py
  bigframes/core/compile/googlesql/query.py
  bigframes/core/sql.py
  bigframes/session/_io/bigquery/__init__.py
  tests/unit/core/compiler/test_googlesql.py
Labels: owlbot:run, api: bigquery, size: m

#796 chore: add dbbenchmark grouby benchmark q8
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q8.py
Labels: api: bigquery, size: s

#794 refactor: add googlesql cast function
  bigframes/core/compile/googlesql/__init__.py
  bigframes/core/compile/googlesql/datatype.py
  bigframes/core/compile/googlesql/function.py
  bigframes/core/sql.py
  tests/unit/core/compile/__init__.py
  tests/unit/core/compile/googlesql/__init__.py
  tests/unit/core/compile/googlesql/test_expression.py
  tests/unit/core/compile/googlesql/test_function.py
  tests/unit/core/compile/googlesql/test_query.py
Labels: api: bigquery, size: m

#797 fix: Self-join optimization doesn't needlessly invalidate caching
  bigframes/core/__init__.py
  bigframes/core/rewrite.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#793 feat: add ml.preprocessing.PolynomialFeatures class
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/small/ml/test_preprocessing.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/preprocessing/_polynomial.py
Labels: api: bigquery, size: m

#799 fix: include internally required packages in `remote_function` hash
  bigframes/functions/remote_function.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: m

#800 docs: document dtype limitation on row processing `remote_function`
  bigframes/session/__init__.py
Labels: api: bigquery, size: xs

#727 feat: Add Series.peek to preview data efficiently
  bigframes/core/blocks.py
  bigframes/core/pruning.py
  bigframes/core/tree_properties.py
  bigframes/dtypes.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/planner.py
  tests/system/small/test_series.py
  tests/unit/test_planner.py
Labels: api: bigquery, size: l

#792 feat: add .agg support for size
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_groupby.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#803 feat: expose gcf memory param in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#809 chore: add groupby benchmark q10, update q8
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q10.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q8.py
Labels: api: bigquery, size: s

#807 feat: add `DataFrame.to_arrow` to create Arrow Table from DataFrame
  bigframes/core/blocks.py
  bigframes/dataframe.py
  samples/polars/create_polars_df_with_to_arrow_test.py
  samples/polars/noxfile.py
  samples/polars/noxfile_config.py
  samples/polars/requirements-test.txt
  samples/polars/requirements.txt
  tests/system/small/test_dataframe_io.py
Labels: samples, api: bigquery, size: l

#802 refactor: Decorate api methods that require total ordering
  bigframes/core/__init__.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexes/base.py
  bigframes/core/validations.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  tests/system/conftest.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: l

#805 feat: add PolynomailFeatures to_gbq and pipeline support
  bigframes/ml/base.py
  bigframes/ml/compose.py
  bigframes/ml/core.py
  bigframes/ml/impute.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_preprocessing.py
  third_party/bigframes_vendored/sklearn/preprocessing/_polynomial.py
Labels: api: bigquery, size: l

#782 feat: bigframes.bigquery.json_set
  bigframes/bigquery/__init__.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  tests/system/small/bigquery/test_json.py
  third_party/bigframes_vendored/ibis/expr/operations/json.py
Labels: api: bigquery, size: m
