Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-08, with the labels that each got.

#875 docs: update streaming notebook
  notebooks/streaming/streaming_dataframe.ipynb
Labels: api: bigquery, size: xs

#865 fix: Fix issue with invalid sql generated by ml distance functions
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/ml/core.py
  bigframes/ml/metrics/pairwise.py
  bigframes/ml/sql.py
  bigframes/operations/__init__.py
  bigframes/operations/type.py
  tests/system/small/ml/test_metrics_pairwise.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: l

#851 feat: `df.apply(axis=1)` to support remote function with mutiple params
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/functions/remote_function.py
  bigframes/operations/__init__.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l

#870 chore: move OrderingMode to enums module
  bigframes/_config/bigquery_options.py
  bigframes/enums.py
Labels: api: bigquery, size: s

#880 docs: create sample notebook using `ordering_mode="partial"`
  notebooks/dataframes/pypi.ipynb
Labels: samples, api: bigquery, size: l

#861 feat: Allow windowing in 'partial' ordering mode
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexes/base.py
  bigframes/core/nodes.py
  bigframes/core/validations.py
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: l

#872 fix: Fix caching from generating row numbers in partial ordering mode
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: s

#877 perf: Generate SQL with fewer CTEs
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/window_spec.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#884 docs: add streaming html docs
  bigframes/session/__init__.py
  bigframes/streaming/dataframe.py
  docs/reference/bigframes.streaming/dataframe.rst
  docs/reference/bigframes.streaming/index.rst
  docs/reference/index.rst
  docs/templates/toc.yml
Labels: api: bigquery, size: s

#886 chore: clean up OWNERS
  OWNERS
Labels: api: bigquery, size: xs

#868 feat: bigframes.bigquery.json_extract
  bigframes/bigquery/__init__.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#888 chore: fix docs build on owlbot.py
  .kokoro/publish-docs.sh
  owlbot.py
Labels: api: bigquery, size: xs

#893 docs: fix the `DisplayOptions` doc rendering
  third_party/bigframes_vendored/pandas/core/config_init.py
Labels: api: bigquery, size: xs

#857 test: enable tests on Windows
  .kokoro/continuous/windows.cfg
  .kokoro/presubmit/windows.cfg
  noxfile.py
  scripts/windows/build.bat
  scripts/windows/test.bat
Labels: api: bigquery, size: m

#895 chore: require Windows unit tests and re-enable owlbot check
  .github/sync-repo-settings.yaml
Labels: api: bigquery, size: xs

#896 perf: Speed up compilation by reducing redundant type normalization
  bigframes/bigquery/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/ibis_types.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: s

#885 refactor: reorganize `remote_function` code for readability
  bigframes/functions/_remote_function_client.py
  bigframes/functions/_remote_function_session.py
  bigframes/functions/_utils.py
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  tests/system/utils.py
Labels: api: bigquery, size: xl

#889 chore: update owlbot script to prevent silent failures at s.replace
  owlbot.py
Labels: api: bigquery, size: s

#897 feat: Series.str.__getitem__
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/strings.py
  tests/system/small/operations/test_strings.py
  third_party/bigframes_vendored/pandas/core/strings/accessor.py
Labels: automerge, api: bigquery, size: l

#899 refactor: Extract DataFrame execution to class
  bigframes/core/blocks.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/clients.py
  bigframes/session/executor.py
  bigframes/session/metrics.py
  bigframes/session/temp_storage.py
  tests/system/large/test_session.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_encryption.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: xl

#905 feat: add llm.TextEmbeddingGenerator to support new embedding models
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#906 docs: update embedding model notebooks
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
Labels: api: bigquery, size: xl

#892 docs: add columns for "requires ordering/index" to supported APIs summary
  bigframes/core/validations.py
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/series.py
  scripts/publish_api_coverage.py
Labels: api: bigquery, size: m

#901 feat: add ml.llm.Claude3TextGenerator model
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  docs/templates/toc.yml
  tests/system/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: l

#890 docs: use unstack() from BigQuery DataFrames instead of pandas in the PyPI sample notebook
  notebooks/dataframes/pypi.ipynb
Labels: samples, api: bigquery, size: s

#883 docs: create sample notebook to manipulate struct and array data
  notebooks/dataframes/struct_and_array_dtypes.ipynb
Labels: samples, api: bigquery, size: l

#908 test: add claude models tests in us-east5
  docs/templates/toc.yml
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#914 fix: struct field non-nullable type issue.
  bigframes/core/compile/scalar_op_compiler.py
Labels: api: bigquery, size: xs

#900 chore: update benchmark logic
  .kokoro/continuous/notebook.cfg
  .kokoro/load/benchmark.cfg
  bigframes/session/metrics.py
  noxfile.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q1.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q10.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q2.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q3.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q4.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q5.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q6.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q7.py
  scripts/benchmark/db-benchmark/groupby/G1_1e9_1e2_5_0/q8.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q1.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q2.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q3.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q4.py
  scripts/benchmark/db-benchmark/join/J1_1e9_NA_0_0/q5.py
  scripts/benchmark/db-benchmark/sort/J1_1e9_NA_0_0/q1.py
  scripts/run_and_publish_benchmark.py
  tests/benchmark/__init__.py
  tests/benchmark/db_benchmark/sort/config.jsonl
  tests/benchmark/db_benchmark/sort/q1.py
  tests/benchmark/utils.py
  third_party/bigframes_vendored/db_benchmark/LICENSE
  third_party/bigframes_vendored/db_benchmark/METADATA
  third_party/bigframes_vendored/db_benchmark/README.md
  third_party/bigframes_vendored/db_benchmark/__init__.py
  third_party/bigframes_vendored/db_benchmark/sort_queries.py
Labels: api: bigquery, size: xl

#910 feat: implement `bigframes.bigquery.json_extract_array`
  bigframes/bigquery/__init__.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#916 feat: add `DataFrame.struct.explode` to add struct subfields to a DataFrame
  bigframes/core/explode.py
  bigframes/dataframe.py
  bigframes/operations/structs.py
  tests/data/nested.jsonl
  tests/data/nested_schema.json
  tests/system/small/operations/test_struct.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/arrays/arrow/accessors.py
Labels: api: bigquery, size: m

#915 chore: remove accidental `typing.py`
  bigframes/typing.py
Labels: api: bigquery, size: u

#922 chore: fix benchmark metric calculation.
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: xs

#920 chore: update db_benchmark groupby queries.
  tests/benchmark/db_benchmark/groupby/config.jsonl
  tests/benchmark/db_benchmark/groupby/q1.py
  tests/benchmark/db_benchmark/groupby/q10.py
  tests/benchmark/db_benchmark/groupby/q2.py
  tests/benchmark/db_benchmark/groupby/q3.py
  tests/benchmark/db_benchmark/groupby/q4.py
  tests/benchmark/db_benchmark/groupby/q5.py
  tests/benchmark/db_benchmark/groupby/q6.py
  tests/benchmark/db_benchmark/groupby/q7.py
  tests/benchmark/db_benchmark/groupby/q8.py
  third_party/bigframes_vendored/db_benchmark/groupby_queries.py
Labels: api: bigquery, size: l

#921 chore: add tpch benchmark q1-3
  tests/benchmark/tpch/config.jsonl
  tests/benchmark/tpch/q1.py
  tests/benchmark/tpch/q2.py
  tests/benchmark/tpch/q3.py
  third_party/bigframes_vendored/tpch/LICENSE
  third_party/bigframes_vendored/tpch/METADATA
  third_party/bigframes_vendored/tpch/README.md
  third_party/bigframes_vendored/tpch/__init__.py
  third_party/bigframes_vendored/tpch/queries/__init__.py
  third_party/bigframes_vendored/tpch/queries/q1.py
  third_party/bigframes_vendored/tpch/queries/q2.py
  third_party/bigframes_vendored/tpch/queries/q3.py
Labels: api: bigquery, size: l

#924 chore: bench metric fix
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: xs

#907 fix: Improve `Series.replace` for dict input
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#927 chore: add tpch q9-13
  tests/benchmark/tpch/q10.py
  tests/benchmark/tpch/q11.py
  tests/benchmark/tpch/q12.py
  tests/benchmark/tpch/q13.py
  tests/benchmark/tpch/q9.py
  third_party/bigframes_vendored/tpch/queries/q10.py
  third_party/bigframes_vendored/tpch/queries/q11.py
  third_party/bigframes_vendored/tpch/queries/q12.py
  third_party/bigframes_vendored/tpch/queries/q13.py
  third_party/bigframes_vendored/tpch/queries/q9.py
Labels: api: bigquery, size: l

#917 fix: NullIndex in ML model.predict error
  bigframes/ml/core.py
  tests/system/large/ml/test_linear_model.py
Labels: api: bigquery, size: s

#933 test: make read_pandas encryption tests non-deterministic
  tests/system/small/test_encryption.py
Labels: api: bigquery, size: s

#934 test: allow more retries on claude tests
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: xs

#932 chore: fix api coverage script in nightly build, ensure scripts tests run
  noxfile.py
  scripts/__init__.py
  scripts/publish_api_coverage.py
  scripts/test_publish_api_coverage.py
Labels: api: bigquery, size: m

#931 deps: re-introduce support for numpy 1.24.x
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/base.py
  setup.py
  testing/constraints-3.9.txt
Labels: api: bigquery, size: m

#935 test: stop checking text generation contents
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_llm.py
  tests/system/utils.py
Labels: api: bigquery, size: m

#925 fix: unordered mode errors in ml train_test_split
  bigframes/ml/model_selection.py
  tests/system/conftest.py
  tests/system/small/ml/test_model_selection.py
Labels: api: bigquery, size: m

#913 refactor: Extract data loading logic into class
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/functions/_remote_function_client.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  bigframes/session/temp_storage.py
  tests/system/small/test_encryption.py
  tests/unit/session/test_session.py
  tests/unit/test_compute_options.py
Labels: api: bigquery, size: xl

#929 chore: add tpch q19-22 and benchmark readme
  tests/benchmark/README.md
  tests/benchmark/tpch/q19.py
  tests/benchmark/tpch/q20.py
  tests/benchmark/tpch/q21.py
  tests/benchmark/tpch/q22.py
  third_party/bigframes_vendored/tpch/queries/q19.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q21.py
  third_party/bigframes_vendored/tpch/queries/q22.py
Labels: api: bigquery, size: l

#926 chore: add tpch q4-8
  tests/benchmark/tpch/config.jsonl
  tests/benchmark/tpch/q4.py
  tests/benchmark/tpch/q5.py
  tests/benchmark/tpch/q6.py
  tests/benchmark/tpch/q7.py
  tests/benchmark/tpch/q8.py
  third_party/bigframes_vendored/tpch/queries/q4.py
  third_party/bigframes_vendored/tpch/queries/q5.py
  third_party/bigframes_vendored/tpch/queries/q6.py
  third_party/bigframes_vendored/tpch/queries/q7.py
  third_party/bigframes_vendored/tpch/queries/q8.py
Labels: api: bigquery, size: l

#928 chore: add tpch q14-18
  tests/benchmark/tpch/q14.py
  tests/benchmark/tpch/q15.py
  tests/benchmark/tpch/q16.py
  tests/benchmark/tpch/q17.py
  tests/benchmark/tpch/q18.py
  third_party/bigframes_vendored/tpch/queries/q14.py
  third_party/bigframes_vendored/tpch/queries/q15.py
  third_party/bigframes_vendored/tpch/queries/q16.py
  third_party/bigframes_vendored/tpch/queries/q17.py
  third_party/bigframes_vendored/tpch/queries/q18.py
Labels: api: bigquery, size: l

#903 deps: Update minimum support to Pandas 1.5.3 and Pyarrow 10.0.1
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.9.txt
  tests/system/small/operations/test_strings.py
Labels: api: bigquery, size: s

#938 test: add CSV sample data file for testing
  tests/data/people.csv
Labels: samples, api: bigquery, size: xs

#918 perf: Improve repr performance
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/core/tree_properties.py
  bigframes/session/executor.py
  tests/unit/core/test_blocks.py
Labels: api: bigquery, size: l
