Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-09, with the labels that each got.

#904 feat: recover struct column from exploded Series
  bigframes/bigquery/__init__.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  tests/system/small/bigquery/test_struct.py
Labels: api: bigquery, size: m

#948 chore: fix the test cover workflow
  .github/workflows/unittest.yml
  owlbot.py
Labels: api: bigquery, size: xs

#949 fix: Fix issue with iterating on >10gb dataframes
  bigframes/core/blocks.py
  bigframes/session/__init__.py
  bigframes/session/executor.py
Labels: api: bigquery, size: s

#953 docs: update struct examples.
  third_party/bigframes_vendored/pandas/core/arrays/arrow/accessors.py
Labels: api: bigquery, size: s

#957 fix: astype Decimal to Int64 conversion.
  bigframes/core/compile/ibis_types.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#940 feat: enable read_csv() to process other files
  bigframes/session/__init__.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
Labels: api: bigquery, size: s

#946 feat: define list accessor for bigframes Series
  bigframes/operations/_op_converters.py
  bigframes/operations/lists.py
  bigframes/operations/strings.py
  bigframes/series.py
  docs/reference/bigframes.pandas/series.rst
  notebooks/dataframes/struct_and_array_dtypes.ipynb
  tests/system/small/operations/test_lists.py
  third_party/bigframes_vendored/pandas/core/arrays/arrow/accessors.py
Labels: api: bigquery, size: l

#945 feat: add Gemini 1.5 stable models support
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#961 refactor: Simplify projection nodes
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/expression.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/core/rewrite.py
  bigframes/session/executor.py
  bigframes/session/planner.py
  tests/unit/test_planner.py
Labels: api: bigquery, size: l

#937 docs: add docstring returns section
  bigframes/_config/__init__.py
Labels: api: bigquery, size: s

#912 chore: drop unused columns at is_monotonic methods
  bigframes/core/blocks.py
Labels: api: bigquery, size: s

#956 test: retry streaming tests to accommodate flakiness
  tests/system/large/test_streaming.py
Labels: api: bigquery, size: xs

#947 fix: make `read_gbq_function` work for multi-param functions
  bigframes/functions/remote_function.py
  bigframes/session/__init__.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: s

#950 fix: support `read_gbq_function` for axis=1 application
  bigframes/functions/_remote_function_session.py
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#952 docs: update title of pypi notebook example to reflect use of the PyPI public dataset
  notebooks/dataframes/pypi.ipynb
Labels: api: bigquery, size: xs

#972 test: adjust expectations in ml tests after bqml update
  tests/system/small/ml/test_ensemble.py
Labels: api: bigquery, size: s

#967 fix: add `__version__` alias to bigframes.pandas
  bigframes/functions/_remote_function_session.py
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: xs

#944 chore: vendor ibis paritial codes for future v9 upgrade
  .pre-commit-config.yaml
  noxfile.py
  third_party/bigframes_vendored/ibis/backends/bigquery/backend.py
  third_party/bigframes_vendored/ibis/backends/sql/__init__.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/__init__.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/base.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/backends/sql/rewrites.py
  third_party/bigframes_vendored/ibis/expr/rewrites.py
Labels: api: bigquery, size: xl

#960 chore: make doctest tests less parallel
  noxfile.py
Labels: api: bigquery, size: xs

#936 feat: include the bigframes package version alongside the feedback link in error messages
  bigframes/constants.py
  tests/unit/test_constants.py
  tests/unit/test_formatting_helpers.py
  third_party/bigframes_vendored/constants.py
Labels: api: bigquery, size: s

#975 test: Revert "test: adjust expectations in ml tests after bqml update"
  tests/system/small/ml/test_ensemble.py
Labels: api: bigquery, size: s

#974 refactor: replace raw pd types with predefined type constants
  bigframes/dtypes.py
Labels: api: bigquery, size: s

#970 chore: update notebook session to run faster.
  noxfile.py
Labels: api: bigquery, size: m

#969 chore: tpch q7 workaround removed.
  third_party/bigframes_vendored/tpch/queries/q7.py
Labels: api: bigquery, size: xs

#978 refactor: Switch explode node to use column offsets
  bigframes/core/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/core/nodes.py
Labels: api: bigquery, size: s

#874 chore: apply `remote_function` on the original series without reprojecting
  bigframes/functions/_remote_function_session.py
  bigframes/functions/remote_function.py
  bigframes/series.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: m

#983 test: disable claude3 predict tests to protect bqml capacity
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: xs

#977 refactor: Limit access to ArrayValue node field.
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/validations.py
  bigframes/session/executor.py
Labels: api: bigquery, size: s

#985 fix: DataFrameGroupby.agg now works with unnamed tuples
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
Labels: api: bigquery, size: s

#827 deps: update to ibis-framework 9.x and newer sqlglot
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/default_ordering.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/compile/single_column.py
  bigframes/core/groupby/__init__.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/functions/_remote_function_session.py
  bigframes/functions/remote_function.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  bigframes/operations/__init__.py
  bigframes/series.py
  noxfile.py
  setup.py
  testing/constraints-3.11.txt
  testing/constraints-3.12.txt
  testing/constraints-3.9.txt
  tests/system/conftest.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_ibis.py
  tests/system/small/test_numpy.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/ibis/backends/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/backends/bigquery/backend.py
  third_party/bigframes_vendored/ibis/backends/bigquery/compiler.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/base.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/backends/sql/rewrites.py
  third_party/bigframes_vendored/ibis/expr/operations/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/arrays.py
  third_party/bigframes_vendored/ibis/expr/operations/json.py
  third_party/bigframes_vendored/ibis/expr/operations/reductions.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/sklearn/metrics/_classification.py
  third_party/bigframes_vendored/sklearn/metrics/_ranking.py
  third_party/bigframes_vendored/sklearn/metrics/_regression.py
Labels: api: bigquery, size: l

#988 fix: Fix a bug that raises exception when re-indexing columns with th…
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#973 feat: support describe for non-numerical type string
  bigframes/dataframe.py
  bigframes/operations/aggregations.py
  tests/system/small/test_dataframe.py
  tests/unit/operations/__init__.py
  tests/unit/operations/test_aggregations.py
Labels: api: bigquery, size: l

#981 feat: add `subset` parameter to `DataFrame.dropna` to select which columns to consider
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/unit/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#982 refactor: Make column id namespaces explicit
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  tests/unit/test_planner.py
Labels: api: bigquery, size: l

#989 deps: limit ibis-framework version to 9.2.0
  setup.py
  testing/constraints-3.12.txt
Labels: api: bigquery, size: xs

#992 chore: Use fixture for list/str accessor tests
  tests/data/repeated.jsonl
  tests/data/repeated_schema.json
  tests/system/conftest.py
  tests/system/small/operations/test_lists.py
  tests/system/small/operations/test_strings.py
Labels: api: bigquery, size: m

#984 chore: fix tpch q5
  tests/benchmark/tpch/q5.py
  third_party/bigframes_vendored/tpch/queries/q5.py
Labels: api: bigquery, size: xs

#995 chore: update local benchmark, 10t config and kokoro project.
  .kokoro/load/benchmark.cfg
  noxfile.py
  scripts/run_and_publish_benchmark.py
  tests/benchmark/tpch/config.jsonl
  tests/benchmark/tpch/q1.py
  tests/benchmark/tpch/q10.py
  tests/benchmark/tpch/q11.py
  tests/benchmark/tpch/q12.py
  tests/benchmark/tpch/q13.py
  tests/benchmark/tpch/q14.py
  tests/benchmark/tpch/q15.py
  tests/benchmark/tpch/q16.py
  tests/benchmark/tpch/q17.py
  tests/benchmark/tpch/q18.py
  tests/benchmark/tpch/q19.py
  tests/benchmark/tpch/q2.py
  tests/benchmark/tpch/q20.py
  tests/benchmark/tpch/q21.py
  tests/benchmark/tpch/q22.py
  tests/benchmark/tpch/q3.py
  tests/benchmark/tpch/q4.py
  tests/benchmark/tpch/q5.py
  tests/benchmark/tpch/q6.py
  tests/benchmark/tpch/q7.py
  tests/benchmark/tpch/q8.py
  tests/benchmark/tpch/q9.py
  tests/benchmark/utils.py
  third_party/bigframes_vendored/tpch/queries/q1.py
  third_party/bigframes_vendored/tpch/queries/q10.py
  third_party/bigframes_vendored/tpch/queries/q11.py
  third_party/bigframes_vendored/tpch/queries/q12.py
  third_party/bigframes_vendored/tpch/queries/q13.py
  third_party/bigframes_vendored/tpch/queries/q14.py
  third_party/bigframes_vendored/tpch/queries/q15.py
  third_party/bigframes_vendored/tpch/queries/q16.py
  third_party/bigframes_vendored/tpch/queries/q17.py
  third_party/bigframes_vendored/tpch/queries/q18.py
  third_party/bigframes_vendored/tpch/queries/q19.py
  third_party/bigframes_vendored/tpch/queries/q2.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q21.py
  third_party/bigframes_vendored/tpch/queries/q22.py
  third_party/bigframes_vendored/tpch/queries/q3.py
  third_party/bigframes_vendored/tpch/queries/q4.py
  third_party/bigframes_vendored/tpch/queries/q5.py
  third_party/bigframes_vendored/tpch/queries/q6.py
  third_party/bigframes_vendored/tpch/queries/q7.py
  third_party/bigframes_vendored/tpch/queries/q8.py
  third_party/bigframes_vendored/tpch/queries/q9.py
Labels: api: bigquery, size: l

#997 test: move Claude3 tests to load test
  tests/system/conftest.py
  tests/system/load/conftest.py
  tests/system/load/test_llm.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#990 chore: re-enable the unittest workflow in Owlbot configuration
  owlbot.py
Labels: api: bigquery, size: xs

#994 feat: Support bool and bytes types in describe(include='all')
  bigframes/dataframe.py
  bigframes/operations/aggregations.py
  tests/system/small/test_dataframe.py
  tests/unit/operations/test_aggregations.py
Labels: api: bigquery, size: m

#1006 test: disable deprecated embedding model tests
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#1003 fix: Fix miscasting issues with case_when
  bigframes/core/expression.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1008 chore: exclude claude3 notebook in nox session
  noxfile.py
Labels: api: bigquery, size: xs

#1012 deps: update ibis version in prerelease tests
  noxfile.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: s

#1000 test: ensure all `remote_function` APIs work in partial ordering mode
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: l

#1001 feat: add ml.model_selection.KFold class
  bigframes/ml/model_selection.py
  bigframes/ml/utils.py
  tests/system/small/ml/test_model_selection.py
  third_party/bigframes_vendored/sklearn/model_selection/_split.py
Labels: api: bigquery, size: l

#1009 chore: update benchmark readme for usage reference.
  tests/benchmark/README.md
Labels: api: bigquery, size: m

#923 perf: Join op discards child ordering in unordered mode
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
Labels: api: bigquery, size: s

#1014 chore: remove pandas version limit from test `test_getitem_w_struct_array`
  tests/system/small/operations/test_strings.py
Labels: api: bigquery, size: xs

#1011 feat: support ingress settings in `remote_function`
  bigframes/functions/_remote_function_client.py
  bigframes/functions/_remote_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#1016 fix: Fix __repr__ caching with partial ordering
  bigframes/core/tree_properties.py
  bigframes/dataframe.py
  bigframes/session/executor.py
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#991 docs: move and edit existing linear-regression tutorial snippet
  samples/snippets/linear_regression_tutorial_test.py
Labels: samples, api: bigquery, size: s

#1005 refactor: re-arrange `describe()` logic into two helper methods
  bigframes/dataframe.py
Labels: api: bigquery, size: m

#1013 docs: limit pypi notebook to 7 days and add more info about differences with partial ordering mode
  notebooks/dataframes/pypi.ipynb
Labels: api: bigquery, size: l

#955 feat: add bigframes.ml.compose.SQLScalarColumnTransformer to create custom SQL-based transformations
  bigframes/ml/base.py
  bigframes/ml/compose.py
  tests/system/large/ml/test_compose.py
  tests/unit/ml/test_compose.py
Labels: api: bigquery, size: l

#998 feat: allow multiple columns input for llm models
  bigframes/ml/llm.py
  tests/system/load/test_llm.py
  tests/system/small/ml/test_llm.py
  tests/system/utils.py
Labels: api: bigquery, size: m

#1010 feat: add bigframes.bigquery.approx_top_count
  bigframes/bigquery/__init__.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/operations/aggregations.py
  tests/system/small/bigquery/test_approx_agg.py
Labels: api: bigquery, size: m

#976 chore: run doctest and notebook tests in bigframes-testing project
  .kokoro/continuous/doctest.cfg
  .kokoro/continuous/notebook.cfg
  .kokoro/presubmit/doctest.cfg
  .kokoro/presubmit/notebook.cfg
  notebooks/location/regionalized.ipynb
  scripts/setup-project-for-testing.sh
Labels: automerge, api: bigquery, size: m

#1020 feat: add ml.model_selection.cross_validate support
  bigframes/ml/model_selection.py
  tests/system/large/ml/test_model_selection.py
  third_party/bigframes_vendored/sklearn/model_selection/_validation.py
Labels: api: bigquery, size: m

#1015 refactor: Simplify query executor interface
  bigframes/core/blocks.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/schema.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/formatting_helpers.py
  bigframes/ml/core.py
  bigframes/operations/__init__.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/pandas.py
  bigframes/session/executor.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_remote_function.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_pandas.py
Labels: api: bigquery, size: l

#1022 refactor: Create class for column ids and column refs
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/concat.py
  bigframes/core/compile/default_ordering.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/identifiers.py
  bigframes/core/indexes/base.py
  bigframes/core/join_def.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/core/pruning.py
  bigframes/core/rewrite.py
  bigframes/core/sql.py
  bigframes/core/window/__init__.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/operations/base.py
  bigframes/series.py
  bigframes/session/executor.py
  bigframes/session/planner.py
  tests/unit/core/test_expression.py
  tests/unit/test_planner.py
Labels: api: bigquery, size: xl

#1023 refactor: move reader functions from `__init__.py` to a separate file under the pandas package
  bigframes/pandas/__init__.py
  bigframes/pandas/io/__init__.py
  bigframes/pandas/io/api.py
  bigframes/streaming/__init__.py
  docs/reference/bigframes.pandas/general_functions.rst
Labels: api: bigquery, size: l

#1019 feat: allow access of struct fields with dot operators on `Series`
  bigframes/series.py
  tests/data/nested_structs.jsonl
  tests/data/nested_structs_schema.json
  tests/system/conftest.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1026 Add parameters and polish prompts
  bigframes/dataframe.py
Labels: api: bigquery, size: s

#1018 feat: add DeprecationWarning for PaLM2TextEmbeddingGenerator
  bigframes/exceptions.py
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1027 separate out prediction logic and parse result and confidence scores
  bigframes/dataframe.py
  notebooks/lotus_demo.ipynb
Labels: api: bigquery, size: m

#1029 finish cascade mode, and use sem_filter as an example
  bigframes/dataframe.py
  notebooks/lotus_demo.ipynb
Labels: api: bigquery, size: l
