Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-10, with the labels that each got.

#1028 fix: remove pre-caching of remote function results
  bigframes/dataframe.py
  bigframes/series.py
Labels: api: bigquery, size: s

#1004 chore: internal version of resample.
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  tests/system/small/test_unordered.py
Labels: samples, api: bigquery, size: l

#1034 benchmark filter() with model cascade on/off
  notebooks/lotus_demo.ipynb
Labels: api: bigquery, size: l

#1035 feat: add deprecation warning to PaLM2TextGenerator model
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1037 docs: add ml cross-validation notebook
  notebooks/ml/bq_dataframes_ml_cross_validation.ipynb
  notebooks/ml/bq_dataframes_ml_linear_regression.ipynb
  notebooks/ml/easy_linear_regression.ipynb
  notebooks/ml/sklearn_linear_regression.ipynb
  noxfile.py
Labels: api: bigquery, size: xl

#1030 refactor: Make expression nodes prunable
  bigframes/core/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/default_ordering.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/session/executor.py
Labels: api: bigquery, size: l

#1039 chore: Add an ExperimentOptions class to control experiments
  bigframes/_config/__init__.py
  bigframes/_config/experiment_options.py
  tests/unit/_config/test_experiment_options.py
Labels: api: bigquery, size: m

#1043 chore: benchmark refactors and updates
  noxfile.py
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: m

#1046 perf: repr generates fewer queries
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1044 fix: make invalid location warning case-insensitive
  bigframes/_config/bigquery_options.py
  bigframes/constants.py
  tests/system/large/test_location.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: m

#964 docs: add docstring return type section to BigQueryOptions class
  bigframes/_config/bigquery_options.py
  bigframes/_config/sampling_options.py
Labels: api: bigquery, size: m

#1049 chore: benchmark fix
  tests/benchmark/db_benchmark/sort/q1.py
Labels: api: bigquery, size: xs

#1045 chore: Implement semantic map
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/__init__.py
  tests/system/large/operations/conftest.py
  tests/system/large/operations/test_semantics.py
  tests/system/small/operations/test_semantics.py
Labels: api: bigquery, size: l

#1031 fix: fix generic error message when entering an incorrect column name
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
Labels: api: bigquery, size: s

#1051 chore: implement semantic join
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: l

#996 test: restore original udf in the remote function test, use supported type in the test data
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: s

#1058 chore: implement semantic search
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/conftest.py
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: l

#1052 fix: show warning for unknown location set through .ctor
  bigframes/_config/bigquery_options.py
  tests/system/large/test_location.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: m

#1048 feat: update LLM generators to warn user about model name instead of raising error.
  bigframes/ml/llm.py
Labels: api: bigquery, size: s

#1062 fix: correct zero row count in DataFrame from table view
  bigframes/core/nodes.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1063 fix: remove PaLM2 test case from load test
  tests/system/load/test_llm.py
Labels: api: bigquery, size: s

#1059 chore: Implement Semantics agg
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: l

#1060 perf: Speedup internal tree comparisons
  bigframes/core/nodes.py
Labels: api: bigquery, size: m

#1056 perf: Reduce schema tracking overhead
  bigframes/core/nodes.py
Labels: api: bigquery, size: m

#1065 refactor: Remove reproject node
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
Labels: api: bigquery, size: s

#1061 feat: support regional endpoints for more bigquery locations
  bigframes/_config/bigquery_options.py
  bigframes/constants.py
  bigframes/session/clients.py
Labels: api: bigquery, size: s

#1064 fix: make `explode` respect the index labels
  bigframes/core/blocks.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1067 chore: implement semantics cluster_by
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: l

#1066 chore: implement semantic similarity join
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: l

#1055 refactor: Introduce slice op to model array slicing
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/nodes.py
  bigframes/core/rewrite.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/executor.py
Labels: api: bigquery, size: l

#1069 chore: fix typo in the cross validation notebook
  notebooks/ml/bq_dataframes_ml_cross_validation.ipynb
Labels: automerge, api: bigquery, size: xs

#1070 fix: access MATERIALIZED_VIEW with read_gbq
  bigframes/core/nodes.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/loader.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#1072 chore: implement semantics topk
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: l

#1068 feat: cleanup temp resources with graceful session shutdown
  .kokoro/continuous/doctest.cfg
  .kokoro/presubmit/doctest.cfg
  bigframes/session/__init__.py
  noxfile.py
  scripts/manage_cloud_functions.py
Labels: api: bigquery, size: m

#1074 fix: Escape ids more consistently in ml module
  bigframes/core/utils.py
  bigframes/ml/compose.py
  bigframes/ml/core.py
  bigframes/ml/impute.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_compose.py
  tests/unit/core/test_bf_utils.py
  tests/unit/ml/test_compose.py
  tests/unit/ml/test_golden_sql.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: l

#1073 fix: Remove index requirement from some dataframe APIs
  bigframes/bigquery/__init__.py
  bigframes/core/eval.py
  bigframes/dataframe.py
  tests/system/small/test_null_index.py
Labels: api: bigquery, size: m

#1078 chore: improve error messages for semantic operators
  bigframes/operations/semantics.py
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: m

#1083 chore: fix mypy errors, exclude experimental notebook from testing
  bigframes/dataframe.py
  bigframes/session/loader.py
  bigframes/session/metrics.py
  noxfile.py
Labels: api: bigquery, size: s

#1071 perf: Speed up tree transforms during sql compile
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/core/tree_properties.py
  bigframes/session/executor.py
Labels: api: bigquery, size: m

#1084 fix: update session metrics in `read_gbq_query`
  bigframes/session/loader.py
  tests/system/large/ml/test_core.py
Labels: api: bigquery, size: s

#1086 chore: skip cluster_by doctest
  bigframes/operations/semantics.py
Labels: api: bigquery, size: xs

#1085 fix: model.fit metric not collected issue.
  bigframes/session/__init__.py
  tests/system/large/ml/test_linear_model.py
  tests/system/small/ml/test_core.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: s

#1093 chore: score query count assertion fix.
  tests/system/large/ml/test_linear_model.py
Labels: api: bigquery, size: xs

#1080 chore: count */core/*.py files for code coverage tests
  .coveragerc
  noxfile.py
  owlbot.py
Labels: api: bigquery, size: s

#1036 feat: support uploading local geo data
  bigframes/session/__init__.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1077 perf: Utilize ORDER BY LIMIT over ROW_NUMBER where possible
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/nodes.py
  bigframes/core/rewrite.py
  bigframes/core/slices.py
  bigframes/core/tree_properties.py
  bigframes/session/executor.py
  tests/unit/core/test_rewrite.py
  tests/unit/core/test_slices.py
Labels: api: bigquery, size: l

#1024 feat: add `bigframes.bigquery.create_vector_index` to assist in creating vector index on `ARRAY<FLOAT64>` columns
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/__init__.py
  bigframes/bigquery/_operations/approx_agg.py
  bigframes/bigquery/_operations/array.py
  bigframes/bigquery/_operations/json.py
  bigframes/bigquery/_operations/search.py
  bigframes/bigquery/_operations/struct.py
  bigframes/core/sql.py
  tests/system/conftest.py
  tests/system/small/bigquery/test_vector_search.py
Labels: api: bigquery, size: xl

#1095 docs: show best practice of closing the session to cleanup resources in sample notebooks
  bigframes/core/global_session.py
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/location/regionalized.ipynb
  notebooks/remote_functions/remote_function_usecases.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  noxfile.py
  scripts/manage_cloud_functions.py
Labels: automerge, api: bigquery, size: m

#1098 chore: lower the sem ops temperature to 0 to reduce randomness
  bigframes/operations/semantics.py
Labels: api: bigquery, size: s

#1099 chore: Semantic - support non-string types, fix flaky top_k doctests
  bigframes/operations/semantics.py
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: m

#1087 docs: Update docstrings of Session and related files
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/io/gbq.py
  third_party/bigframes_vendored/pandas/io/parquet.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
  third_party/bigframes_vendored/pandas/io/pickle.py
Labels: api: bigquery, size: s

#1105 feat: add gemini-1.5-pro-002 and gemini-1.5-flash-002 to known Gemini…
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1102 chore: update semantic join column reference syntax
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: m

#1097 feat: show possible correct key(s) in .__getitem__ KeyError message
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
Labels: api: bigquery, size: m

#1088 feat: add support for pandas series & data frames as inputs for ml models.
  bigframes/ml/base.py
  bigframes/ml/cluster.py
  bigframes/ml/compose.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/impute.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/model_selection.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/remote.py
  bigframes/ml/utils.py
  tests/system/small/ml/test_model_selection.py
  tests/system/small/ml/test_utils.py
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
  third_party/bigframes_vendored/sklearn/compose/_column_transformer.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
  third_party/bigframes_vendored/sklearn/ensemble/_forest.py
  third_party/bigframes_vendored/sklearn/impute/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
  third_party/bigframes_vendored/sklearn/preprocessing/_data.py
  third_party/bigframes_vendored/sklearn/preprocessing/_discretization.py
  third_party/bigframes_vendored/sklearn/preprocessing/_encoder.py
  third_party/bigframes_vendored/sklearn/preprocessing/_label.py
  third_party/bigframes_vendored/sklearn/preprocessing/_polynomial.py
Labels: api: bigquery, size: l

#1089 feat: support series items method
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#1100 chore: fix docstrings typos
  bigframes/_config/__init__.py
  bigframes/ml/forecasting.py
  bigframes/ml/llm.py
Labels: api: bigquery, size: xs

#1092 docs: update docstrings of DataFrame and related files
  bigframes/dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: l

#1112 chore: manually update owlbot docker images to latest
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/requirements.txt
  .kokoro/samples/python3.13/common.cfg
  .kokoro/samples/python3.13/continuous.cfg
  .kokoro/samples/python3.13/periodic-head.cfg
  .kokoro/samples/python3.13/periodic.cfg
  .kokoro/samples/python3.13/presubmit.cfg
  owlbot.py
  samples/polars/noxfile.py
  samples/snippets/noxfile.py
Labels: api: bigquery, size: l

#1082 feat: Add warning when user tries to access struct series fields with `__getitem__`
  bigframes/core/indexers.py
  bigframes/exceptions.py
  tests/system/small/core/__init__.py
  tests/system/small/core/test_indexers.py
Labels: api: bigquery, size: m

#1115 chore: Enable REP for latest supported regions b/375100286
  bigframes/constants.py
Labels: api: bigquery, size: xs

#1107 feat: support context manager for bigframes session
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/large/test_session.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: m

#1096 feat: allow `fit` to take additional eval data in linear and ensemble models
  bigframes/ml/base.py
  bigframes/ml/ensemble.py
  bigframes/ml/linear_model.py
  bigframes/ml/utils.py
  tests/system/large/ml/test_linear_model.py
  third_party/bigframes_vendored/sklearn/ensemble/_forest.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
  third_party/bigframes_vendored/xgboost/sklearn.py
Labels: api: bigquery, size: l

#1108 perf: improve series.unique performance and replace drop_duplicates i…
  bigframes/series.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/tpch/queries/q10.py
  third_party/bigframes_vendored/tpch/queries/q11.py
  third_party/bigframes_vendored/tpch/queries/q15.py
  third_party/bigframes_vendored/tpch/queries/q16.py
  third_party/bigframes_vendored/tpch/queries/q17.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q22.py
  third_party/bigframes_vendored/tpch/queries/q4.py
Labels: api: bigquery, size: m

#1042 chore: performance improvement for resample.
  bigframes/core/compile/compiler.py
Labels: samples, api: bigquery, size: xs

#1119 feat: add the `ground_with_google_search` option for GeminiTextGenerator predict
  bigframes/ml/llm.py
  bigframes/operations/semantics.py
  tests/system/load/test_llm.py
Labels: api: bigquery, size: m

#1121 chore: test fix.
  tests/system/small/test_session.py
Labels: api: bigquery, size: xs

#1101 docs: add snippet for Linear Regression tutorial Predict Outcomes section
  samples/snippets/linear_regression_tutorial_test.py
Labels: samples, api: bigquery, size: s

#1103 docs: update GroupBy docstrings
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: m

#1118 fix: Fix Series.to_frame generating string label instead of int where…
  bigframes/core/indexers.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1124 refactor: sort the region and location in constants.py
  bigframes/constants.py
Labels: api: bigquery, size: m

#1120 fix: update the API documentation with newly added rep
  bigframes/_config/bigquery_options.py
Labels: api: bigquery, size: xs

#962 feat: add basic geopandas functionality
  bigframes/geopandas/__init__.py
  bigframes/geopandas/geoseries.py
  bigframes/series.py
  docs/reference/bigframes.geopandas/geoseries.rst
  docs/reference/bigframes.geopandas/index.rst
  docs/reference/index.rst
  third_party/bigframes_vendored/geopandas/LICENSE.txt
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: m

#1114 perf: Reduce CURRENT_TIMESTAMP queries
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/loader.py
  bigframes/session/time.py
  noxfile.py
  tests/unit/resources.py
  tests/unit/session/test_time.py
Labels: api: bigquery, size: m

#1128 chore: update tpch q7/q14
  third_party/bigframes_vendored/tpch/queries/q14.py
  third_party/bigframes_vendored/tpch/queries/q7.py
Labels: api: bigquery, size: s
