Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-07, with the labels that each got.

#812 chore: add a test for external table reading.
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#811 feat: More informative error when query plan too complex
  bigframes/exceptions.py
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#810 refactor: Add mappings from internal dtypes to bq types
  bigframes/core/blocks.py
  bigframes/core/schema.py
  bigframes/dtypes.py
Labels: api: bigquery, size: m

#808 test: add notebook with remote function use cases
  notebooks/remote_functions/remote_function_usecases.ipynb
Labels: api: bigquery, size: xl

#814 refactor: Create ordering base class to represent partial ordering
  bigframes/core/__init__.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/concat.py
  bigframes/core/compile/default_ordering.py
  bigframes/core/compile/single_column.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#821 docs: remove session and connection in llm notebook
  notebooks/generative_ai/large_language_models.ipynb
Labels: api: bigquery, size: m

#820 docs: remove the experimental flask icon from the public docs
  docs/templates/toc.yml
Labels: api: bigquery, size: xs

#813 chore: remove an unused parameter in _rows_to_dataframe
  bigframes/core/blocks.py
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: xs

#830 chore: remove references to conda
  noxfile.py
  third_party/bigframes_vendored/ibis/README.md
  third_party/bigframes_vendored/pandas/README.md
Labels: api: bigquery, size: s

#817 refactor: read transformer output columns from model entity
  bigframes/ml/base.py
  bigframes/ml/compose.py
  bigframes/ml/impute.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
Labels: automerge, api: bigquery, size: l

#815 feat: add stratify param support to ml.model_selection.train_test_split method
  bigframes/ml/model_selection.py
  tests/system/small/ml/test_model_selection.py
Labels: api: bigquery, size: m

#823 fix: Fewer relation joins from df self-operations
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/join_def.py
  bigframes/core/nodes.py
  bigframes/core/rewrite.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#835 docs: add partner attribution steps to integrations sample notebook
  notebooks/dataframes/integrations.ipynb
Labels: samples, api: bigquery, size: m

#836 test: fix llm load tests
  tests/system/load/test_llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#838 refactor: SQL builder supports partial ordering
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/ordering.py
Labels: api: bigquery, size: m

#839 fix: Fix unordered mode using ordered path to print frame
  bigframes/core/blocks.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: s

#841 chore: fix notebook test.
  notebooks/regression/sklearn_linear_regression.ipynb
Labels: api: bigquery, size: xs

#840 refactor: Turn compiler into object with toggleable order strictness
  bigframes/core/compile/api.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
Labels: api: bigquery, size: l

#818 feat: support remote function cleanup with `session.close`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/large/test_session.py
Labels: api: bigquery, size: xl

#845 test: Fix json_set error tests to create resources in test body
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: s

#831 test: Run several tests in unordered mode as well as ordered
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
  tests/system/utils.py
Labels: api: bigquery, size: m

#832 feat: Add bigframes-mode label to query jobs
  bigframes/session/__init__.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: s

#848 test: disable unavailable BQML remote vertex model tests
  noxfile.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_remote.py
Labels: api: bigquery, size: xs

#849 refactor: Allow unambiguous windows even in unstrictly ordered sessions
  bigframes/core/__init__.py
  bigframes/core/nodes.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: s

#846 test: re-enable gemini tuning load test
  tests/system/load/test_llm.py
Labels: api: bigquery, size: xs

#842 refactor: Unordered mode supports user partial orders
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/__init__.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiler.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: m

#850 test: temporarily disable streaming tests
  tests/system/large/test_streaming.py
Labels: api: bigquery, size: xs

#847 test: restore remote function stickiness in small tests
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: l

#852 test: fix mypy failures to unblock presubmit tests
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: s

#844 fix: Fix 'sql' property for null index
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: s

#853 chore: fix create_bigtable script
  scripts/create_bigtable.py
Labels: api: bigquery, size: xs

#859 test: enable Gemini 1.5 flash default test
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: xs

#855 feat: Add config option to set partial ordering mode
  bigframes/_config/bigquery_options.py
  bigframes/session/__init__.py
  tests/system/conftest.py
Labels: api: bigquery, size: m

#863 chore: increase stale cloud functions cleanup rate
  tests/system/conftest.py
Labels: api: bigquery, size: s

#854 refactor: Block .head consistently in unordered mode
  bigframes/constants.py
  bigframes/core/groupby/__init__.py
  bigframes/core/validations.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: s

#862 refactor: Respect session default index in merge and reset_index methods
  bigframes/core/blocks.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: m

#860 feat: Allow DataFrame.join for self-join on Null index
  bigframes/core/blocks.py
  bigframes/ml/core.py
  tests/system/large/ml/test_linear_model.py
  tests/system/small/test_null_index.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: m

#858 feat: Support to_csv/parquet/json to local files/objects
  bigframes/core/utils.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: l

#856 fix: reduce redundant `remote_function` deployments
  bigframes/functions/remote_function.py
  bigframes/functions/remote_function_template.py
  bigframes/session/__init__.py
  notebooks/remote_functions/remote_function_usecases.ipynb
Labels: api: bigquery, size: l

#864 feat: add streaming.StreamingDataFrame class
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/streaming/__init__.py
  bigframes/streaming/dataframe.py
  notebooks/streaming/streaming_dataframe.ipynb
  tests/system/conftest.py
  tests/system/large/test_streaming.py
  tests/unit/test_pandas.py
Labels: api: bigquery, size: xl

#873 chore: reduce the `remote_function` cleanup rate
  tests/system/conftest.py
Labels: api: bigquery, size: xs
