Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-12, with the labels that each got.

#1184 chore: Minor updates on doc "bigframes/ml/base.py"
  bigframes/ml/base.py
Labels: kokoro:force-run, api: bigquery, size: xs

#1188 chore: Bound Jellyfish <1.1.2
  setup.py
Labels: api: bigquery, size: xs

#1192 test: fix/disable failed linear_model tests
  tests/system/conftest.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_ensemble.py
  tests/system/small/ml/test_linear_model.py
Labels: api: bigquery, size: m

#1186 feat: Update llm.TextEmbeddingGenerator to 005
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  owlbot.py
  tests/system/large/operations/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1194 refactor: consolidate reshaping functions under the reshape package
  bigframes/core/reshape/__init__.py
  bigframes/core/reshape/api.py
  bigframes/core/reshape/concat.py
  bigframes/core/reshape/merge.py
  bigframes/core/reshape/tile.py
  bigframes/dataframe.py
  bigframes/operations/semantics.py
  bigframes/pandas/__init__.py
  bigframes/pandas/io/api.py
Labels: api: bigquery, size: l

#1195 feat: Series.isin supports bigframes.Series arg
  bigframes/core/blocks.py
  bigframes/ml/utils.py
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1177 feat: add ARIMAPlus.predict_explain() to generate forecasts with explanation columns
  bigframes/ml/core.py
  bigframes/ml/forecasting.py
  bigframes/ml/sql.py
  tests/system/small/ml/test_forecasting.py
  tests/unit/ml/test_forecasting.py
Labels: api: bigquery, size: m

#1189 feat: Add support for temporal types in dataframe's describe() method
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/aggregations.py
  tests/system/small/test_dataframe.py
  tests/unit/operations/test_aggregations.py
Labels: api: bigquery, size: m

#1201 test: fix load test local run
  tests/system/load/test_llm.py
Labels: api: bigquery, size: xs

#1202 fix: Fix series.isin using local path always
  bigframes/core/blocks.py
  bigframes/series.py
Labels: api: bigquery, size: xs

#1179 chore: fix cleanup on Python 3.9
  tests/system/conftest.py
Labels: api: bigquery, size: xs

#1191 docs: update bigframes.pandas.index docs return types
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: xs

#1209 feat: add Gemini 2.0 preview text model support
  bigframes/ml/llm.py
  bigframes/ml/loader.py
Labels: api: bigquery, size: s

#1199 refactor: Share logic between old and new aligner
  bigframes/core/__init__.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/implicit_align.py
  bigframes/core/rewrite/legacy_align.py
Labels: api: bigquery, size: m

#1207 chore: de-flake sem_cluster test by relaxing the passing requirement
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: s

#1211 docs: add Gemini 2.0 text gen sample notebook
  notebooks/generative_ai/bq_dataframes_llm_gemini_2.ipynb
  noxfile.py
Labels: samples, api: bigquery, size: l

#1210 chore: add Colab link in semantic ops demo notebook
  notebooks/experimental/semantic_operators.ipynb
Labels: api: bigquery, size: s

#1213 test: add Gemini 2.0 tests
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1166 feat: support dataframe where method
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l

#1198 refactor: Create memoized tree traversal helpers
  bigframes/core/compile/compiler.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/slices.py
  bigframes/core/tree_properties.py
  bigframes/session/executor.py
Labels: api: bigquery, size: m

#1187 fix: json in struct destination type
  bigframes/bigquery/_operations/json.py
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/session/executor.py
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1208 feat: add Gemini-pro-1.5 to GeminiTextGenerator Tuning and Support score() method in Gemini-pro-1.5
  bigframes/ml/llm.py
  tests/system/load/test_llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#1218 chore: credit the Lotus paper and its authors in the sem ops notebook
  notebooks/experimental/semantic_operators.ipynb
Labels: api: bigquery, size: xs

#1221 test: re-enable fixed BQML linear model test
  tests/system/small/ml/test_core.py
Labels: api: bigquery, size: xs

#1200 chore: add a demo notebook showcasing the summary of bigframes features
  notebooks/getting_started/bq_dataframes_template.ipynb
  tests/unit/test_notebook.py
Labels: api: bigquery, size: xl

#1126 feat: add `GeoSeries.x` and `GeoSeries.y`
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  tests/data/urban_areas.jsonl
  tests/data/urban_areas_schema.json
  tests/system/conftest.py
  tests/system/small/geopandas/test_geoseries.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l

#1225 chore: update tpch q21
  third_party/bigframes_vendored/tpch/queries/q21.py
Labels: api: bigquery, size: m

#1223 docs: add an "open in BQ Studio" link to all BigFrames sample notebooks
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
Labels: samples, api: bigquery, size: m

#1224 chore: add experimental series.str.to_blob function
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/blob.py
  bigframes/operations/strings.py
Labels: api: bigquery, size: m

#1229 chore: add a script to verify the tpch code.
  scripts/tpch_result_verify.py
Labels: api: bigquery, size: l

#1219 refactor: move get_dummies() to encoding.py
  bigframes/core/reshape/api.py
  bigframes/core/reshape/encoding.py
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: l

#1222 feat: add `LogisticRegression.predict_explain()` to generate `ML.EXPLAIN_PREDICT` columns
  bigframes/ml/linear_model.py
  tests/system/small/ml/test_linear_model.py
Labels: api: bigquery, size: m

#1230 chore: add experimental bpd.from_glob_path method
  bigframes/pandas/__init__.py
  bigframes/pandas/io/api.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#1233 chore: set the default python version for templates to 3.10
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/unittest.yml
  owlbot.py
Labels: api: bigquery, size: xs

#1232 chore: add experimental series.blob.display() function
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1234 docs: add KMeans example
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
Labels: api: bigquery, size: s

#1236 docs: add examples for ml PCA and SimpleImputer
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
  third_party/bigframes_vendored/sklearn/impute/_base.py
Labels: api: bigquery, size: s

#1237 fix: ARIMAPlus series input
  bigframes/ml/forecasting.py
  tests/system/large/ml/test_forecasting.py
Labels: api: bigquery, size: xs

#1238 docs: add ml.model_selection examples
  bigframes/ml/model_selection.py
  third_party/bigframes_vendored/sklearn/model_selection/_split.py
  third_party/bigframes_vendored/sklearn/model_selection/_validation.py
Labels: api: bigquery, size: m

#1235 docs: add linear model example
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
Labels: api: bigquery, size: s

#1239 docs: add bq studio link for a new ipynb file
  notebooks/getting_started/bq_dataframes_template.ipynb
Labels: api: bigquery, size: xs

#371 feat: add `write_engine` parameter to `read_FORMATNAME` methods to control how data is written to BigQuery
  bigframes/dtypes.py
  bigframes/pandas/io/api.py
  bigframes/session/__init__.py
  bigframes/session/_io/pandas.py
  bigframes/session/loader.py
  bigframes/session/validation.py
  noxfile.py
  setup.py
  testing/constraints-3.13.txt
  testing/constraints-3.14.txt
  testing/constraints-3.15.txt
  testing/constraints-3.9.txt
  tests/system/small/test_session.py
  tests/unit/core/test_dtypes.py
  tests/unit/polars_session.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/constants.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
  third_party/bigframes_vendored/pandas/io/pickle.py
Labels: api: bigquery, size: l

#1240 docs: add example for logistic regression
  tests/system/small/ml/test_llm.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
Labels: api: bigquery, size: s

#1227 docs: add python snippet for "Create the time series model" section of the Forecast a single time series with a univariate model tutorial
  samples/snippets/create_single_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: s

#1242 feat: add client side retry to GeminiTextGenerator
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: l

#1243 chore: update semantic operator notebook
  notebooks/experimental/semantic_operators.ipynb
Labels: api: bigquery, size: xl

#1228 feat: add support for `LinearRegression.predict_explain` and `LogisticRegression.predict_explain` parameter, `top_k_features`
  bigframes/ml/core.py
  bigframes/ml/linear_model.py
  bigframes/ml/sql.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_linear_model.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: m
