Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-04, with the labels that each got.

#554 fix: allow `repr` for results more than 10 GB
  bigframes/core/blocks.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#549 chore: fix typo `mertics` to `metrics`
  bigframes/ml/metrics/_metrics.py
Labels: api: bigquery, size: s

#555 chore: address comments from technical writers for legal review
  bigframes/_config/bigquery_options.py
  bigframes/ml/compose.py
  bigframes/ml/imported.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
  third_party/bigframes_vendored/sklearn/compose/_column_transformer.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
  third_party/bigframes_vendored/sklearn/preprocessing/_discretization.py
Labels: api: bigquery, size: s

#552 feat: add transformers save/load
  bigframes/ml/base.py
  bigframes/ml/compose.py
  bigframes/ml/loader.py
  bigframes/ml/preprocessing.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_preprocessing.py
Labels: api: bigquery, size: l

#558 fix: Respect hard stack size limit and swallow limit change exception.
  bigframes/pandas/__init__.py
Labels: automerge, api: bigquery, size: s

#561 fix: rename Embedding output columns to be back-compatible
  bigframes/ml/llm.py
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: xl

#557 docs: add opeartions in API docs
  docs/templates/toc.yml
Labels: automerge, api: bigquery, size: xs

#568 fix: exclude list-like s parameter in plot.scatter
  bigframes/operations/_matplotlib/core.py
  tests/system/small/operations/test_plotting.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: api: bigquery, size: s

#565 fix: Restore string to date/time type coercion
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/type.py
  tests/system/small/operations/test_datetimes.py
Labels: automerge, api: bigquery, size: m

#564 fix: include all names in MultiIndex repr
  bigframes/core/blocks.py
  bigframes/core/indexes/__init__.py
  bigframes/core/indexes/base.py
  docs/reference/bigframes.pandas/indexing.rst
  docs/templates/toc.yml
  scripts/publish_api_coverage.py
  tests/system/small/test_index.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#559 feat: add ml.metrics.mean_squared_error
  bigframes/ml/metrics/__init__.py
  bigframes/ml/metrics/_metrics.py
  tests/system/small/ml/test_metrics.py
  third_party/bigframes_vendored/sklearn/metrics/_regression.py
Labels: api: bigquery, size: m

#560 refactor: remove to_pandas in ml.metrics.roc_auc_score
  bigframes/ml/metrics/_metrics.py
Labels: api: bigquery, size: s

#566 test: remove transformer test column reorders
  tests/system/large/ml/test_compose.py
  tests/system/small/ml/test_preprocessing.py
Labels: api: bigquery, size: m

#563 fix: plot.scatter s parameter cannot accept float-like column
  bigframes/operations/_matplotlib/core.py
  tests/system/small/operations/test_plotting.py
Labels: automerge, api: bigquery, size: s

#573 feat: read_pandas accepts pandas Series and Index objects
  .pre-commit-config.yaml
  bigframes/pandas/__init__.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: automerge, api: bigquery, size: m

#544 feat: Allow DataFrame binary ops to align on either axis and with loc…
  bigframes/core/convert.py
  bigframes/dataframe.py
  bigframes/typing.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#576 fix: Use bytes limit on frame inlining rather than element count
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_progress_bar.py
Labels: api: bigquery, size: s

#556 feat: (Series|DataFrame).explode
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/ibis/expr/operations/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/generic.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#567 chore: remove outdated notebook
  notebooks/vertex_sdk/sdk2_bigframes_pytorch.ipynb
  notebooks/vertex_sdk/sdk2_bigframes_sklearn.ipynb
  notebooks/vertex_sdk/sdk2_bigframes_tensorflow.ipynb
Labels: api: bigquery, size: xl

#569 fix: reloaded transformer .transform error
  bigframes/ml/compose.py
  tests/system/large/ml/test_compose.py
  tests/system/small/ml/test_preprocessing.py
Labels: api: bigquery, size: m

#571 docs: address more comments from technical writers to meet legal purposes
  bigframes/ml/base.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/metrics/_metrics.py
  bigframes/ml/model_selection.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
  notebooks/regression/sklearn_linear_regression.ipynb
  third_party/bigframes_vendored/pandas/core/config_init.py
  third_party/bigframes_vendored/xgboost/sklearn.py
Labels: automerge, api: bigquery, size: m

#575 fix: fix error in `Series.drop(0)`
  bigframes/series.py
  tests/system/small/test_series.py
Labels: automerge, api: bigquery, size: s

#427 perf: Add multi-query execution capability for complex dataframes
  bigframes/_config/compute_options.py
  bigframes/core/blocks.py
  bigframes/core/expression.py
  bigframes/core/nodes.py
  bigframes/core/tree_properties.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: l

#507 docs: add General Availability banner to README
  README.rst
  setup.py
Labels: api: bigquery, size: s

#578 chore: add BigQuery locations to bigframes/constants.py
  bigframes/constants.py
  tests/config.py
  tests/system/large/test_location.py
Labels: api: bigquery, size: m

#572 chore: add context and address some TODOs in noxfile
  noxfile.py
  tests/system/small/operations/test_plotting.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_encryption.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_pandas.py
  tests/system/small/test_progress_bar.py
  tests/system/small/test_remote_function.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/cpython/_pprint.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: l

#574 fix: Inverting int now does bitwise inversion rather than sign flip
  bigframes/core/compile/scalar_op_compiler.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#584 chore: reorganize the supported pandas apis page
  docs/templates/toc.yml
Labels: api: bigquery, size: xs

#581 fix: address more technical writers feedback
  bigframes/_config/compute_options.py
  bigframes/ml/base.py
  bigframes/ml/cluster.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  third_party/bigframes_vendored/pandas/core/config_init.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/sklearn/base.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
Labels: api: bigquery, size: m

#582 docs: add examples for at/iat
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m, status: ready for review

#591 fix: toc menu missing plotting name
  docs/templates/toc.yml
Labels: automerge, api: bigquery, size: xs

#577 doc: add examples for DatetimeMethods
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
  third_party/bigframes_vendored/pandas/core/tools/datetimes.py
Labels: api: bigquery, size: m

#598 docs: (Series|Dataframe).dtypes
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#473 feat: Add pivot_table for DataFrame.
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#594 docs: add code samples for `str` accessor methdos
  bigframes/operations/strings.py
  scripts/get_documentation_coverage.py
  third_party/bigframes_vendored/pandas/core/strings/accessor.py
Labels: automerge, samples, api: bigquery, size: l

#570 fix: error for object dtype on read_pandas
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#596 feat: Add MultiIndex subclass.
  bigframes/core/indexes/__init__.py
  bigframes/core/indexes/base.py
  bigframes/core/indexes/multi.py
  bigframes/pandas/__init__.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/indexes/multi.py
Labels: automerge, api: bigquery, size: m

#600 feat: Add hasnans, combine_first, update to Series
  bigframes/core/convert.py
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: m

#603 fix: loc setitem dtype issue.
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: s

#597 refactor: Remove join name mapper code.
  bigframes/core/compile/single_column.py
  bigframes/core/joins/__init__.py
  bigframes/core/joins/name_resolution.py
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: m

#605 feat: Add Series.autocorr
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#562 docs: add docs for `DataFrame` and `Series` dunder methods
  bigframes/dataframe.py
  bigframes/series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: xl

#580 feat: support list of numerics in pandas.cut
  bigframes/core/reshape/__init__.py
  bigframes/operations/aggregations.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: automerge, api: bigquery, size: m, status: ready for review

#606 test: series explode test
  tests/system/small/test_series.py
Labels: api: bigquery, size: xs

#613 feat: Add quantile statistic
  bigframes/constants.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/groupby/__init__.py
  bigframes/dataframe.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_groupby.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: automerge, api: bigquery, size: l

#604 test: add a bigquery usage report to notebook test session
  bigframes/session/_io/bigquery.py
  noxfile.py
Labels: api: bigquery, size: m, status: ready for review

#611 fix: address technical writers fb
  bigframes/ml/model_selection.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
  third_party/bigframes_vendored/sklearn/base.py
  third_party/bigframes_vendored/sklearn/metrics/_classification.py
  third_party/bigframes_vendored/sklearn/pipeline.py
  third_party/bigframes_vendored/sklearn/preprocessing/_encoder.py
  third_party/bigframes_vendored/sklearn/preprocessing/_label.py
Labels: api: bigquery, size: s

#602 fix: infer narrowest numeric type when combining numeric columns
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/expression.py
  bigframes/core/join_def.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#616 feat: Add fine tuning `fit()` for Palm2TextGenerator
  bigframes/ml/core.py
  bigframes/ml/llm.py
  bigframes/ml/sql.py
  tests/system/load/test_llm.py
  tests/system/small/ml/test_llm.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: m

#620 docs: Fix rendering of examples for multiple apis
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: xs

#609 feat: warn if location is set to unknown location
  bigframes/_config/bigquery_options.py
  bigframes/exceptions.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: m

#619 fix: Use exact median implementation by default
  bigframes/core/block_transforms.py
  bigframes/core/groupby/__init__.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#622 feat: expose `max_batching_rows` in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#615 chore: add synthetic data generation notebook
  notebooks/apps/synthetic_data_generation.ipynb
  noxfile.py
Labels: api: bigquery, size: xl

#599 feat: Series.struct.dtypes
  bigframes/operations/structs.py
  third_party/bigframes_vendored/pandas/core/arrays/arrow/accessors.py
Labels: api: bigquery, size: s

#624 docs: set `index_cols` in `read_gbq` as a best practice
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: s

#625 feat: support primary key(s) in `read_gbq` by using as the `index_col` by default
  bigframes/session/__init__.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/test_session.py
  tests/unit/resources.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: m

#618 feat: Series binary ops compatible with more types
  bigframes/core/__init__.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/convert.py
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: l

#621 feat: Add transpose support for small homogeneously typed DataFrames.
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#627 fix: llm fine tuning tests
  tests/system/load/test_llm.py
Labels: api: bigquery, size: s

#595 test: test most relevant dtype for aggregates
  bigframes/dtypes.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#636 refactor: cache table metadata alongside snapshot time
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#634 feat: support the `score` method for `PaLM2TextGenerator`
  bigframes/ml/core.py
  bigframes/ml/llm.py
  bigframes/ml/sql.py
  tests/system/load/test_llm.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/ensemble/_forest.py
  third_party/bigframes_vendored/xgboost/sklearn.py
Labels: api: bigquery, size: m

#635 perf: Cache transpose to allow performant retranspose
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/ordering.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#637 fix: Allow to_pandas to download more than 10GB
  bigframes/core/blocks.py
  bigframes/session/__init__.py
  tests/system/load/test_large_tables.py
Labels: api: bigquery, size: s

#639 feat: expose gcf max timeout in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#632 fix: Extend row hash to 128 bits to guarantee unique row id
  bigframes/session/__init__.py
  tests/unit/resources.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#640 docs: address more technical writers' feedback
  bigframes/ml/cluster.py
  bigframes/ml/decomposition.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/pipeline.py
  bigframes/ml/remote.py
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
  third_party/bigframes_vendored/sklearn/ensemble/_forest.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
  third_party/bigframes_vendored/sklearn/metrics/pairwise.py
  third_party/bigframes_vendored/sklearn/pipeline.py
  third_party/bigframes_vendored/sklearn/preprocessing/_encoder.py
  third_party/bigframes_vendored/xgboost/sklearn.py
Labels: api: bigquery, size: m

#626 feat: Add .cache() method to persist intermediate dataframe
  bigframes/dataframe.py
  bigframes/ml/core.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: s

#641 feat: allow single input type in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  samples/snippets/remote_function.py
  tests/system/large/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#516 perf: Automatically condense internal expression representation
  bigframes/core/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/core/rewrite.py
Labels: api: bigquery, size: m

#643 fix: llm palm score tests
  tests/system/load/test_llm.py
Labels: automerge, api: bigquery, size: s

#642 refactor: split `read_gbq_table` implementation into functions and move to separate module
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_read_gbq_table.py
Labels: api: bigquery, size: l

#630 feat: add the `bigframes.bigquery` sub-package with a `bigframes.bigquery.array_length` function
  bigframes/bigquery/__init__.py
  docs/reference/bigframes.bigquery/index.rst
  docs/reference/bigframes/index.rst
  docs/reference/index.rst
  docs/templates/toc.yml
  tests/system/small/bigquery/__init__.py
  tests/system/small/bigquery/test_array.py
Labels: api: bigquery, size: m
