Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-01, with the labels that each got.

#297 chore: stop using deprecated ibis relabel method
  bigframes/core/compile/compiled.py
Labels: automerge, api: bigquery, size: xs

#295 docs: code samples for `sample`, `get`, `Series.round`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#293 docs: code samples for `DataFrame.rename`, `Series.rename`
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#294 feat: support upcasting numeric columns in concat
  bigframes/core/blocks.py
  bigframes/dtypes.py
  bigframes/operations/aggregations.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_pandas.py
Labels: api: bigquery, size: m

#296 fix: Fix bug converting non-string labels to sql ids
  bigframes/core/__init__.py
  bigframes/core/nodes.py
  bigframes/core/utils.py
  tests/system/small/test_multiindex.py
Labels: automerge, api: bigquery, size: m

#298 feat: add 'columns' as an alias for 'col_order'
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: m

#302 feat: Allow manually set clustering_columns in dataframe.to_gbq
  bigframes/dataframe.py
  bigframes/session/_io/bigquery.py
  tests/system/small/test_dataframe_io.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#301 fix: DF.drop tuple input as multi-index
  bigframes/dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: s

#307 docs: add code samples for `Series.ffill` and `DataFrame.ffill`
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: samples, api: bigquery, size: s

#304 feat: support assigning to columns like a property
  bigframes/core/log_adapter.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: m

#303 feat: add Series dt.tz and dt.unit properties
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
Labels: automerge, api: bigquery, size: m

#299 feat: add to_gbq() method for LLM models
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#100 refactor: unify row operators to same interface
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/indexes/index.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/operations/base.py
  bigframes/operations/strings.py
  bigframes/operations/structs.py
  bigframes/pandas/__init__.py
  bigframes/series.py
Labels: automerge, api: bigquery, size: xl

#305 fix: handle multi-level columns for df aggregates properly
  bigframes/core/blocks.py
  tests/system/small/test_multiindex.py
Labels: automerge, api: bigquery, size: s

#308 fix: update max_output_token limitation.
  bigframes/ml/llm.py
Labels: api: bigquery, size: s

#309 refactor: define scalar expression structs
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/expression.py
  bigframes/core/indexes/index.py
  bigframes/core/nodes.py
  bigframes/operations/__init__.py
  tests/unit/test_core.py
Labels: automerge, api: bigquery, size: l

#306 refactor: refactor block materialization
  bigframes/_config/sampling_options.py
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/row_identity.py
  bigframes/series.py
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: m

#316 docs: add code samples for `Series.corr`
  bigframes/series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: samples, api: bigquery, size: s

#314 refactor: remove 'partial' ops and replace with expressions
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/expression.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexers.py
  bigframes/core/indexes/index.py
  bigframes/core/reshape/__init__.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/operations/base.py
  bigframes/pandas/__init__.py
  bigframes/series.py
Labels: api: bigquery, size: l

#317 refactor: combine all projection nodes into single node type
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/expression.py
  bigframes/core/indexes/index.py
  bigframes/core/nodes.py
  tests/unit/test_core.py
Labels: api: bigquery, size: l

#310 chore: add polished ml fundamental notebooks and retire the old one
  notebooks/getting_started/ml_fundamentals.ipynb
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
Labels: automerge, api: bigquery, size: xl

#322 refactor: move remote_function logic to make a space for other types
  bigframes/functions/__init__.py
  bigframes/functions/remote_function.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  tests/unit/test_dtypes.py
  tests/unit/test_remote_function.py
Labels: api: bigquery, size: s

#324 refactor: move remote_function logic to make a space for other types …
  bigframes/functions/__init__.py
  bigframes/functions/remote_function.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  tests/unit/test_dtypes.py
  tests/unit/test_remote_function.py
Labels: size: s

#325 chore: add ml_fundamentals_bq_dataframes.ipynb to denylist.
  noxfile.py
Labels: api: bigquery, size: xs

#326 docs: Add `DataFrame.applymap` documentation
  README.rst
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: xs

#323 docs: code samples for Series.{argmax, argmin, is_monotonic_increasing, is_monotonic_decreasing}
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#330 chore: delete the connection requirement in llm notebooks
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
Labels: api: bigquery, size: m

#332 fix: read_gbq large response issue
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: xs

#321 refactor: simplify filter and join nodes
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/row_identity.py
  bigframes/core/compile/single_column.py
  bigframes/core/indexes/index.py
  bigframes/core/join_def.py
  bigframes/core/joins/__init__.py
  bigframes/core/joins/name_resolution.py
  bigframes/core/nodes.py
Labels: automerge, api: bigquery, size: l

#333 docs: add remote model requirements
  README.rst
Labels: automerge, api: bigquery, size: s

#329 fix: use object dtype for ARRAY columns in `to_pandas()` with pandas 1.x
  bigframes/features.py
  bigframes/session/_io/pandas.py
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_preprocessing.py
  tests/system/small/test_dataframe_io.py
  tests/unit/session/test_io_pandas.py
  tests/unit/test_features.py
Labels: automerge, api: bigquery, size: xl

#335 feat: update cut to work without labels = False and show intervals as dict
  bigframes/core/reshape/__init__.py
  bigframes/operations/aggregations.py
  tests/system/small/test_pandas.py
  tests/unit/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: api: bigquery, size: m

#339 fix: Series iteration correctly returns values instead of index
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: s

#343 chore: exclude pandas 2.2.0 to unblock prerelease tests
  noxfile.py
Labels: automerge, api: bigquery, size: xs

#331 chore: Script to inspect and clean up stale GCFs
  scripts/manage_cloud_functions.py
Labels: automerge, api: bigquery, size: m

#336 feat: add ARIMA_EVAULATE options in forecasting models
  bigframes/ml/core.py
  bigframes/ml/forecasting.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_forecasting.py
  tests/system/small/ml/test_forecasting.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: m

#338 refactor: add output type annotations to scalar ops
  bigframes/core/expression.py
  bigframes/dtypes.py
  bigframes/functions/remote_function.py
  bigframes/operations/__init__.py
  bigframes/operations/type.py
  tests/unit/core/test_expression.py
  tests/unit/test_dtypes.py
  tests/unit/test_remote_function.py
Labels: api: bigquery, size: l

#318 feat: add efficient peek dataframe preview
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: m

#344 feat: Improve error message for drive based BQ table reads
  bigframes/session/__init__.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#347 fix: chance default connection name in getting_started.ipnyb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
Labels: automerge, api: bigquery, size: xs

#334 feat: Add Index constructor, copy, get_level_values, to_series
  bigframes/core/blocks.py
  bigframes/core/indexers.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/system/small/test_index.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#354 refactor: Split aggregate ops from implementation
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/analytic_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/operations/aggregations.py
Labels: automerge, api: bigquery, size: l

#358 chore: pin pytest version
  noxfile.py
Labels: automerge, api: bigquery, size: xs

#351 chore: ensure colab sample notebooks are tested
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  noxfile.py
  scripts/notebooks_fill_params.py
  scripts/notebooks_restore_from_backup.py
Labels: samples, api: bigquery, size: m

#353 docs: add code samples for `Series.{between, cumprod}`
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, samples, api: bigquery, size: m

#350 perf: Make repr cache the block where appropriate
  bigframes/core/blocks.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/core/traversal.py
  bigframes/dataframe.py
  bigframes/ml/core.py
  bigframes/series.py
  bigframes/session/__init__.py
Labels: automerge, api: bigquery, size: m
