Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-03, with the labels that each got.

#378 chore: add the toc template file for entry page
  docs/templates/toc.yml
Labels: automerge, api: bigquery, size: s

#400 fix: docs link for metrics.pairwise
  docs/reference/bigframes.ml/index.rst
  docs/reference/bigframes.ml/metrics.pairwise.rst
Labels: api: bigquery, size: xs

#407 feat: Support BYOSA in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: automerge, api: bigquery, size: m

#410 chore: add load tests session for reading large tables
  .kokoro/load/common.cfg
  .kokoro/load/load.cfg
  noxfile.py
  scripts/create_load_test_tables.py
  tests/system/conftest.py
  tests/system/load/test_large_tables.py
Labels: api: bigquery, size: l

#415 chore: update toc entry to properly include summary pages
  docs/templates/toc.yml
Labels: automerge, api: bigquery, size: xs

#413 feat: add engine parameter to `read_parquet`
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/io/parquet.py
Labels: automerge, api: bigquery, size: m

#408 chore: materialize result of `remote_function` early
  bigframes/series.py
Labels: automerge, api: bigquery, size: xs

#356 fix: only do row identity based joins when joining by index
  bigframes/core/__init__.py
  bigframes/core/compile/single_column.py
  bigframes/core/nodes.py
  tests/system/conftest.py
  tests/system/small/regression/test_issue355_merge_after_filter.py
Labels: automerge, api: bigquery, size: m

#417 docs: fix the note rendering for DataFrames methods: nlargest, nsmallest
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: s

#416 docs: Document minimum IAM requirement
  README.rst
Labels: automerge, api: bigquery, size: s

#388 docs: add predict sample to samples/snippets/bqml_getting_started_test.py
  samples/snippets/bqml_getting_started_test.py
Labels: samples, api: bigquery, size: m

#419 chore: increase timeout on load tests
  .kokoro/load/common.cfg
  noxfile.py
Labels: api: bigquery, size: xs

#403 feat: Support CMEK for BQ tables
  bigframes/_config/bigquery_options.py
  bigframes/ml/core.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  bigframes/session/clients.py
  tests/system/small/test_encryption.py
  tests/unit/_config/test_bigquery_options.py
  tests/unit/ml/test_golden_sql.py
  tests/unit/session/test_clients.py
Labels: api: bigquery, size: l

#425 chore: don't require branch to be synced with main to merge
  .github/sync-repo-settings.yaml
Labels: automerge, api: bigquery, size: xs

#420 feat: (Series|Dataframe).plot.hist()
  bigframes/dataframe.py
  bigframes/operations/_matplotlib/__init__.py
  bigframes/operations/_matplotlib/core.py
  bigframes/operations/_matplotlib/hist.py
  bigframes/operations/plotting.py
  bigframes/series.py
  docs/reference/bigframes.pandas/frame.rst
  docs/reference/bigframes.pandas/series.rst
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/operations/test_plot.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: api: bigquery, size: l

#424 fix: move `third_party.bigframes_vendored` to `bigframes_vendored`
  MANIFEST.in
  bigframes/_config/__init__.py
  bigframes/_config/display_options.py
  bigframes/_config/sampling_options.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexes/index.py
  bigframes/core/tools/datetimes.py
  bigframes/core/utils.py
  bigframes/core/window/__init__.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/functions/remote_function.py
  bigframes/ml/base.py
  bigframes/ml/cluster.py
  bigframes/ml/compose.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/linear_model.py
  bigframes/ml/metrics/_metrics.py
  bigframes/ml/metrics/pairwise.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/operations/base.py
  bigframes/operations/datetimes.py
  bigframes/operations/plotting.py
  bigframes/operations/strings.py
  bigframes/operations/structs.py
  bigframes/pandas/__init__.py
  bigframes/py.typed
  bigframes/series.py
  bigframes/session/__init__.py
  noxfile.py
  owlbot.py
  pyproject.toml
  setup.py
  tests/system/small/test_ibis.py
  tests/unit/test_remote_function.py
  third_party/bigframes_vendored/google_cloud_bigquery/tests/unit/test_pandas_helpers.py
  third_party/bigframes_vendored/ibis/backends/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/ibis/expr/operations/__init__.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
  third_party/bigframes_vendored/py.typed
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
  third_party/bigframes_vendored/sklearn/compose/_column_transformer.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
  third_party/bigframes_vendored/sklearn/pipeline.py
  third_party/bigframes_vendored/sklearn/preprocessing/_data.py
  third_party/bigframes_vendored/sklearn/preprocessing/_discretization.py
  third_party/bigframes_vendored/sklearn/preprocessing/_encoder.py
  third_party/bigframes_vendored/sklearn/preprocessing/_label.py
Labels: automerge, api: bigquery, size: m

#412 fix: read_pandas inline respects location
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/nodes.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  notebooks/location/regionalized.ipynb
  tests/system/small/test_dataframe.py
  tests/system/small/test_session.py
  tests/unit/core/test_blocks.py
Labels: automerge, api: bigquery, size: m

#426 feat: add detect_anomalies to ml ARIMAPlus and KMeans models
  bigframes/ml/cluster.py
  bigframes/ml/decomposition.py
  bigframes/ml/forecasting.py
  tests/system/small/ml/test_cluster.py
  tests/system/small/ml/test_decomposition.py
  tests/system/small/ml/test_forecasting.py
Labels: automerge, api: bigquery, size: m

#429 chore: update genai notebooks for Gemini
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/generative_ai/large_language_models.ipynb
  noxfile.py
Labels: automerge, api: bigquery, size: xl

#428 chore: add script to compute code samples coverage
  scripts/get_code_sample_coverage.py
Labels: samples, api: bigquery, size: m

#404 chore: remove `to_pandas_dtypes_overrides` dead code
  bigframes/dtypes.py
Labels: automerge, api: bigquery, size: s

#433 test: include model.register test for BQML CMEK
  bigframes/ml/core.py
  bigframes/session/__init__.py
  tests/system/small/test_encryption.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: m

#430 feat: support CMEK for `remote_function` cloud functions
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#406 chore: fix two typos in dtypes.py
  bigframes/dtypes.py
Labels: api: bigquery, size: xs

#431 feat: (Series|DataFrame).plot.(line|area|scatter)
  bigframes/operations/_matplotlib/__init__.py
  bigframes/operations/_matplotlib/core.py
  bigframes/operations/plotting.py
  tests/system/small/operations/test_plotting.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: api: bigquery, size: l

#439 chore: add deferred exec code samples
  bigframes/_config/compute_options.py
  third_party/bigframes_vendored/pandas/core/config_init.py
Labels: samples, api: bigquery, size: s

#421 feat: add DataFrame.pipe() method
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/common.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: m

#442 feat: support datetime related casting in (Series|DataFrame|Index).astype
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#441 fix: warn when `read_gbq` / `read_gbq_table` uses the snapshot time cache
  bigframes/session/__init__.py
  tests/unit/resources.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: s

#437 docs: add version information to bug template
  .github/ISSUE_TEMPLATE/bug_report.md
  owlbot.py
Labels: api: bigquery, size: s

#438 feat: (Series|DataFrame).plot
  bigframes/operations/plotting.py
  tests/system/small/operations/test_plotting.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: api: bigquery, size: m

#432 test: enable BYOSA test for `remote_function` cloud function
  tests/system/large/test_remote_function.py
Labels: automerge, api: bigquery, size: s

#447 fix: raise `ValueError` when `read_pandas()` receives a bigframes `DataFrame`
  bigframes/session/__init__.py
  tests/unit/session/test_io_pandas.py
Labels: api: bigquery, size: s

#450 fix: fix broken link in covid notebook
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
Labels: api: bigquery, size: xs

#446 docs: add the docs for loc and iloc indexers
  docs/reference/bigframes.pandas/index.rst
  docs/reference/bigframes.pandas/indexers.rst
  docs/templates/toc.yml
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: m

#451 docs: indicate that project and location are optional in example notebooks
  notebooks/dataframes/dataframe.ipynb
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
  notebooks/location/regionalized.ipynb
  notebooks/regression/bq_dataframes_ml_linear_regression.ipynb
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
Labels: api: bigquery, size: xl

#453 feat: support Series.dt.strftime
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
Labels: api: bigquery, size: m

#452 fix: series.(to_csv|to_json) leverages bq export
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#454 feat: `read_gbq_table` supports `LIKE` as a operator in `filters`
  bigframes/session/__init__.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: automerge, api: bigquery, size: s

#436 refactor: Reimplement implicit joiner at expression layer
  bigframes/core/__init__.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/row_identity.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/ordering.py
  bigframes/core/rewrite.py
  bigframes/operations/__init__.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: l

#457 fix: df.drop_na preserves columns dtype
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
Labels: automerge, api: bigquery, size: m

#423 test: do GCF cleanup in both presubmit and e2e tests
  tests/system/conftest.py
  tests/system/large/test_remote_function.py
  tests/system/utils.py
Labels: api: bigquery, size: l

#456 docs: add the pages for at and iat indexers
  docs/reference/bigframes.pandas/indexers.rst
  docs/templates/toc.yml
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#459 docs: add code samples for `ml.metrics.r2_score`
  third_party/bigframes_vendored/sklearn/metrics/_regression.py
Labels: automerge, samples, api: bigquery, size: s

#455 fix: fix grouping series on multiple other series
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#465 fix!: exclude remote models for .register()
  bigframes/ml/base.py
  bigframes/ml/llm.py
  tests/system/small/ml/test_register.py
Labels: api: bigquery, size: s

#471 fix: any() on empty set now correctly returns False
  bigframes/core/compile/aggregate_compiler.py
  tests/system/small/test_index.py
Labels: automerge, api: bigquery, size: xs

#467 fix: fix broken multiindex loc cases
  bigframes/core/indexers.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_multiindex.py
Labels: automerge, api: bigquery, size: m

#472 fix: groupby aggregates no longer check if grouping keys are numeric
  bigframes/core/groupby/__init__.py
  bigframes/dataframe.py
  tests/system/small/test_groupby.py
Labels: automerge, api: bigquery, size: s

#474 feat: add ml PCA model params
  bigframes/ml/decomposition.py
  tests/system/large/ml/test_decomposition.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
Labels: api: bigquery, size: m

#464 feat: add params for LinearRegression model
  bigframes/ml/linear_model.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_linear_model.py
  tests/unit/ml/test_golden_sql.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
Labels: api: bigquery, size: m

#468 fix: renable to_csv and to_json related tests
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_encryption.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  tests/system/utils.py
Labels: api: bigquery, size: m

#376 refactor: complete dtype rules for expression tree transformations
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/expression.py
  bigframes/core/local_data.py
  bigframes/core/nodes.py
  bigframes/core/schema.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/functions/remote_function.py
  bigframes/operations/__init__.py
  bigframes/operations/aggregations.py
  bigframes/operations/type.py
  bigframes/pandas/__init__.py
  bigframes/series.py
  bigframes/session/__init__.py
  mypy.ini
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  tests/unit/core/test_blocks.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#475 fix: sampling plot cannot preserve ordering if index is not ordered
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/operations/_matplotlib/core.py
  bigframes/series.py
  tests/system/small/operations/test_plotting.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: m

#460 feat: option to use bq connection without check
  bigframes/_config/bigquery_options.py
  bigframes/clients.py
  bigframes/functions/remote_function.py
  bigframes/ml/llm.py
  bigframes/ml/remote.py
  bigframes/session/__init__.py
  tests/system/small/test_remote_function.py
  tests/unit/_config/test_bigquery_options.py
  tests/unit/test_clients.py
Labels: api: bigquery, size: l

#477 feat: add ml KMeans model params
  bigframes/ml/cluster.py
  tests/system/large/ml/test_cluster.py
  third_party/bigframes_vendored/sklearn/cluster/_kmeans.py
Labels: automerge, api: bigquery, size: m

#463 fix: fix -1 offset lookups failing
  bigframes/core/indexers.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#483 feat: support Series.dt.normalize
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
Labels: automerge, api: bigquery, size: m

#478 docs: add code samples for metrics.{accuracy_score, confusion_matrix}
  third_party/bigframes_vendored/sklearn/metrics/_classification.py
Labels: automerge, samples, api: bigquery, size: s

#493 feat: support Series.dt.floor
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
Labels: automerge, api: bigquery, size: m

#485 chore: update docstring for astype
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: m

#490 refactor: convert ordering definitions to use flexible scalar express…
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/concat.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexes/index.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/core/reshape/__init__.py
  bigframes/core/rewrite.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/unit/resources.py
  tests/unit/test_core.py
Labels: automerge, api: bigquery, size: l

#458 feat: update plot sample to 1000 rows
  bigframes/operations/_matplotlib/core.py
  tests/system/small/operations/test_plotting.py
Labels: automerge, samples, api: bigquery, size: s

#488 feat: add ml ARIMAPlus model params
  bigframes/ml/forecasting.py
  tests/system/large/ml/test_forecasting.py
Labels: api: bigquery, size: m

#481 feat: add ml LogisticRegression model params
  bigframes/ml/linear_model.py
  tests/system/large/ml/test_linear_model.py
  tests/unit/ml/test_golden_sql.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
Labels: api: bigquery, size: m

#495 feat: allow assigning directly to Series.name property
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#401 feat: add configuration option to read_gbq
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: automerge, api: bigquery, size: m

#489 docs: improve API documentation
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: s

#497 feat: ensure `Series.str.len()` can get length of array columns
  tests/system/conftest.py
  tests/system/small/operations/test_strings.py
Labels: automerge, api: bigquery, size: s

#492 deps: support pandas 2.2
  bigframes/core/joins/merge.py
  bigframes/core/utils.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery.py
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
  noxfile.py
  setup.py
  tests/system/conftest.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_groupby.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_series.py
  tests/unit/test_pandas.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/indexing.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#496 docs: update LLM + K-means notebook to handle partial failures
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
Labels: api: bigquery, size: xl

#498 feat: support dataframe.cov
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: m

#502 docs: add code samples for metrics.{recall_score, precision_score, f11_score}
  third_party/bigframes_vendored/sklearn/metrics/_classification.py
Labels: automerge, samples, api: bigquery, size: s

#461 test: enable back cmek tests on inline data
  tests/system/small/test_encryption.py
Labels: automerge, api: bigquery, size: xs

#491 feat!: rename ml model params
  bigframes/ml/cluster.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/linear_model.py
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_linear_model.py
  tests/unit/ml/test_golden_sql.py
  third_party/bigframes_vendored/sklearn/decomposition/_pca.py
  third_party/bigframes_vendored/sklearn/ensemble/_forest.py
  third_party/bigframes_vendored/sklearn/linear_model/_base.py
  third_party/bigframes_vendored/sklearn/linear_model/_logistic.py
  third_party/bigframes_vendored/xgboost/sklearn.py
Labels: automerge, api: bigquery, size: l

#494 fix: plot.scatter `c` argument functionalities
  bigframes/operations/_matplotlib/core.py
  tests/system/small/operations/test_plotting.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: automerge, api: bigquery, size: m

#503 test: use `reuse=False` in more `remote_function` e2e tests
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: xs

#499 docs: update bigquery connection documentation
  README.rst
Labels: api: bigquery, size: s

#500 fix: Use actual BigQuery types rather than ibis types in to_pandas
  bigframes/dtypes.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: s

#508 docs: add progress_bar code sample
  third_party/bigframes_vendored/pandas/core/config_init.py
Labels: automerge, samples, api: bigquery, size: s

#510 chore: fix model.register test to use anonymous dataset
  tests/system/small/ml/conftest.py
Labels: api: bigquery, size: xs

#505 feat: Add support for numpy expm1, log1p, floor, ceil, arctan2 ops
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  tests/system/small/test_numpy.py
Labels: api: bigquery, size: m

#361 feat: add DataFrame.eval, DataFrame.query
  bigframes/core/eval.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/common.py
  third_party/bigframes_vendored/pandas/core/computation/align.py
  third_party/bigframes_vendored/pandas/core/computation/common.py
  third_party/bigframes_vendored/pandas/core/computation/engines.py
  third_party/bigframes_vendored/pandas/core/computation/eval.py
  third_party/bigframes_vendored/pandas/core/computation/expr.py
  third_party/bigframes_vendored/pandas/core/computation/ops.py
  third_party/bigframes_vendored/pandas/core/computation/parsing.py
  third_party/bigframes_vendored/pandas/core/computation/scope.py
  third_party/bigframes_vendored/pandas/core/dtypes/inference.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/util/_exceptions.py
  third_party/bigframes_vendored/pandas/util/_validators.py
Labels: api: bigquery, size: xl

#514 chore: remove initialization workaround in to_datetime.
  bigframes/core/tools/datetimes.py
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
  third_party/bigframes_vendored/pandas/core/tools/datetimes.py
Labels: api: bigquery, size: s

#501 fix: Product operation produces float result for all input types
  bigframes/core/compile/aggregate_compiler.py
  bigframes/operations/aggregations.py
  tests/system/small/test_groupby.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, api: bigquery, size: s

#512 docs: fix docs of ARIMAPlus.predict
  bigframes/ml/forecasting.py
Labels: api: bigquery, size: xs

#520 docs: add the code samples for metrics{auc, roc_auc_score, roc_curve}
  third_party/bigframes_vendored/sklearn/metrics/_ranking.py
Labels: automerge, samples, api: bigquery, size: m

#527 chore: remove unused ColumnTransformer check
  bigframes/ml/compose.py
  tests/system/large/ml/test_compose.py
Labels: automerge, api: bigquery, size: s

#519 feat: expose `DataFrame.bqclient` to assist in integrations
  bigframes/dataframe.py
  notebooks/dataframes/dataframe.ipynb
  notebooks/dataframes/integrations.ipynb
Labels: api: bigquery, size: l

#528 chore: address comments from technical writers
  bigframes/_config/bigquery_options.py
Labels: automerge, api: bigquery, size: s

#529 deps: include `pyarrow` as a dependency
  noxfile.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.9.txt
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#535 chore: experimentally double load test timeout
  .kokoro/load/common.cfg
  noxfile.py
Labels: automerge, api: bigquery, size: xs, status: ready for review

#537 fix: don't download 100gb onto local python machine in load test
  tests/system/load/test_large_tables.py
Labels: api: bigquery, size: xs

#517 test: add e2e tests for all BQ locations
  bigframes/session/clients.py
  tests/config.py
  tests/system/large/test_location.py
Labels: api: bigquery, size: m

#532 refactor: Add type constraints to internal op definitions.
  bigframes/core/nodes.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/type.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: l

#536 docs: Migrate the overview page to Bigframes official landing page
  README.rst
Labels: api: bigquery, size: l

#543 docs: Mark Gemini model as Pre-GA
  bigframes/ml/llm.py
Labels: automerge, size: xs

#515 feat: Support max_columns in repr and make repr more efficient
  bigframes/core/blocks.py
  bigframes/core/indexes/index.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m, status: ready for review

#539 feat: support `ML.GENERATE_EMBEDDING` in `PaLM2TextEmbeddingGenerator`
  bigframes/ml/core.py
  bigframes/ml/llm.py
  bigframes/ml/sql.py
  tests/system/small/ml/test_llm.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: s

#546 test: add the code snippets for gemini model
  samples/snippets/gemini_model_test.py
Labels: api: bigquery, size: s

#513 fix: assign NaN scalar to column error.
  bigframes/core/__init__.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#545 chore: enhance documentation coverage script
  scripts/get_documentation_coverage.py
Labels: api: bigquery, size: s

#511 fix: Fix case where df.peek would fail to execute even with force=True
  bigframes/core/blocks.py
  bigframes/core/nodes.py
  bigframes/core/tree_properties.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#541 feat: add ColumnTransformer save/load
  bigframes/ml/compose.py
  bigframes/ml/loader.py
  bigframes/ml/pipeline.py
  bigframes/session/__init__.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_pipeline.py
Labels: api: bigquery, size: l

#542 docs: add "Supported pandas APIs" reference to the documentation
  .kokoro/release-nightly.sh
  docs/index.rst
  docs/supported_pandas_apis.rst
  docs/supported_pandas_apis/.gitignore
  docs/templates/toc.yml
  noxfile.py
  scripts/publish_api_coverage.py
  scripts/test_publish_api_coverage.py
Labels: automerge, api: bigquery, size: l

#550 fix: sync the notebook with embedding changes
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
Labels: automerge, api: bigquery, size: xl
