Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-02, with the labels that each got.

#312 refactor: refactor block index properties
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/indexes/__init__.py
  bigframes/core/indexes/index.py
  bigframes/core/reshape/__init__.py
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/unit/core/test_blocks.py
Labels: api: bigquery, size: l

#367 chore: add test data in preparation for `explode()` and similar methods
  tests/data/nested.jsonl
  tests/data/nested_schema.json
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#366 docs: Fix the `DataFrame.apply` code sample
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: automerge, samples, api: bigquery, size: s

#360 refactor: generalize aggregation to handle 0,1, or 2 inputs
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/analytic_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/expression.py
  bigframes/core/groupby/__init__.py
  bigframes/core/indexes/index.py
  bigframes/core/nodes.py
  bigframes/core/reshape/__init__.py
  bigframes/core/window/__init__.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  tests/unit/test_core.py
Labels: automerge, api: bigquery, size: l

#352 test: fix unit tests for handling drive access issues
  tests/unit/resources.py
  tests/unit/session/test_session.py
  tests/unit/test_compute_options.py
Labels: api: bigquery, size: m

#364 docs: Add a sample to demonstrate the evaluation results
  samples/snippets/bqml_getting_started_test.py
Labels: automerge, samples, api: bigquery, size: m

#368 feat: add `Series.cov` method
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/operations/aggregations.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/system/small/test_series.py
  tests/unit/test_core.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: m

#363 feat: add XGBoostModel
  README.rst
  bigframes/ml/core.py
  bigframes/ml/globals.py
  bigframes/ml/imported.py
  bigframes/ml/loader.py
  bigframes/ml/remote.py
  bigframes/ml/sql.py
  docs/templates/toc.yml
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_imported.py
  tests/unit/ml/test_sql.py
Labels: automerge, api: bigquery, size: l

#375 fix: error message fix.
  bigframes/dataframe.py
  bigframes/functions/remote_function.py
  bigframes/series.py
Labels: automerge, api: bigquery, size: xs

#348 docs: clarify ADC pre-auth in a non-interactive environment
  README.rst
Labels: automerge, api: bigquery, size: s

#370 feat: add ml.llm.GeminiTextGenerator model
  README.rst
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  docs/templates/toc.yml
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: automerge, api: bigquery, size: m

#372 feat: Support bigframes.pandas.to_datetime for scalars, iterables and series.
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/tools/__init__.py
  bigframes/core/tools/datetimes.py
  bigframes/operations/__init__.py
  bigframes/pandas/__init__.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/tools/__init__.py
  third_party/bigframes_vendored/pandas/core/tools/datetimes.py
Labels: api: bigquery, size: l

#345 feat: limited support of lamdas in `Series.apply`
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: automerge, api: bigquery, size: l

#377 feat: support read_gbq wildcard table path
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/small/test_session.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: m

#374 feat: add ml.metrics.pairwise.cosine_similarity function
  bigframes/ml/core.py
  bigframes/ml/metrics/__init__.py
  bigframes/ml/metrics/_metrics.py
  bigframes/ml/metrics/pairwise.py
  bigframes/ml/sql.py
  docs/templates/toc.yml
  tests/system/small/ml/test_metrics_pairwise.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/metrics/pairwise.py
Labels: automerge, api: bigquery, size: l

#365 fix: correct the numeric literal dtype
  bigframes/dtypes.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#382 docs: Fix `bigframes.pandas.concat` documentation
  third_party/bigframes_vendored/pandas/core/reshape/concat.py
Labels: api: bigquery, size: m

#379 feat: add `DataFrames.corr()` method
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#383 perf: inline read_pandas for small data
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/session/__init__.py
  tests/system/small/test_progress_bar.py
  tests/unit/session/test_io_bigquery.py
Labels: automerge, api: bigquery, size: m

#381 refactor!: move model optional args to kwargs
  bigframes/ml/base.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/metrics/_metrics.py
  bigframes/ml/remote.py
Labels: automerge, api: bigquery, size: m

#389 deps: add minimum version constraint for sqlglot to 19.9.0
  setup.py
  testing/constraints-3.9.txt
Labels: api: bigquery, size: m

#391 chore: exclude pandas 2.2.x from testing
  noxfile.py
Labels: automerge, api: bigquery, size: xs

#386 feat: Enable regional endpoints for me-central2
  bigframes/_config/bigquery_options.py
  bigframes/session/__init__.py
  bigframes/session/clients.py
Labels: automerge, api: bigquery, size: s

#393 fix!: rename cosine_similarity to paired_cosine_distances
  bigframes/ml/metrics/pairwise.py
  tests/system/small/ml/test_metrics_pairwise.py
  third_party/bigframes_vendored/sklearn/metrics/pairwise.py
Labels: automerge, api: bigquery, size: s

#392 feat: Add `ml.metrics.pairwise.manhattan_distance`
  bigframes/ml/metrics/pairwise.py
  tests/system/small/ml/test_metrics_pairwise.py
  third_party/bigframes_vendored/sklearn/metrics/pairwise.py
Labels: api: bigquery, size: s

#267 docs: add a code sample for creating a kmeans model
  samples/snippets/conftest.py
  samples/snippets/create_kmeans_model_test.py
Labels: automerge, samples, api: bigquery, size: m

#394 feat: add TextEmbedding model version support
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  bigframes/ml/utils.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: automerge, api: bigquery, size: m

#402 docs: update README to point to new summary pages
  README.rst
Labels: automerge, api: bigquery, size: xs

#387 fix: exceptions raised in `apply` from a `remote_function` now surface in the client
  bigframes/functions/remote_function.py
  tests/system/large/test_remote_function.py
Labels: automerge, api: bigquery, size: m
