Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-11, with the labels that each got.

#1129 perf: Reduce dry runs from read_gbq with table
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/loader.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#1094 refactor: Add function to make all column ids in a tree unique and sequential
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/concat.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/identifiers.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/core/rewrite.py
  bigframes/core/window_spec.py
Labels: api: bigquery, size: l

#1104 chore: add exec_seconds attribute to ExecutionMetrics
  bigframes/session/metrics.py
Labels: api: bigquery, size: s

#1127 docs: update `DataFrame` docstrings to include the errors section
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: m

#1137 test: add `requests` dependency to the anthropic remote function
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
Labels: api: bigquery, size: xs

#1136 test: Add data file for JSON dtype system tests
  tests/data/json.jsonl
  tests/data/json_schema.json
  tests/system/conftest.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1134 chore: fix docstrings typos
  notebooks/remote_functions/remote_function.ipynb
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#1135 docs: add file for Classification with a Boosted Treed Model and snippet for preparing sample data
  samples/snippets/classification_boosted_tree_model_test.py
Labels: samples, api: bigquery, size: s

#1130 docs: update ``Session`` doctrings to include exceptions
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/io/gbq.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
Labels: api: bigquery, size: s

#1111 docs: document groupby.head and groupby.size methods
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: m

#1138 fix: exclude index columns from model fitting processes.
  bigframes/ml/core.py
  tests/system/large/ml/test_cluster.py
  tests/system/large/ml/test_linear_model.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: m

#1132 fix: dataframe fillna with scalar.
  bigframes/dataframe.py
  bigframes/dtypes.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1148 fix: unordered mode too many labels issue.
  bigframes/session/executor.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1133 refactor: Reduce executor cache interface to one method
  bigframes/core/blocks.py
  bigframes/session/executor.py
Labels: api: bigquery, size: s

#1122 feat: add astype(type, errors='null') to cast safely
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_index.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: m

#1149 chore: add guidance for read_parquet using wildcard paths
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1150 chore: add blob experimental flag
  bigframes/_config/experiment_options.py
  tests/unit/_config/test_experiment_options.py
Labels: api: bigquery, size: s

#1151 chore: Amend astype error message and docstring
  bigframes/core/indexes/base.py
  bigframes/series.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: s

#1007 test: Add unit testing using local polars-based engine
  bigframes/core/compile/polars/__init__.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/local_data.py
  bigframes/core/slices.py
  bigframes/session/__init__.py
  bigframes/session/_io/pandas.py
  bigframes/session/executor.py
  noxfile.py
  setup.py
  tests/unit/polars_session.py
  tests/unit/resources.py
  tests/unit/test_local_engine.py
Labels: api: bigquery, size: l

#1142 docs: add snippet for creating boosted tree model
  samples/snippets/classification_boosted_tree_model_test.py
Labels: samples, api: bigquery, size: s

#1165 fix: Fix error loading local dataframes into bigquery
  bigframes/session/loader.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1158 feat: `bigframes.bigquery.vector_search` supports `use_brute_force` and `fraction_lists_to_search` parameters
  bigframes/bigquery/_operations/search.py
  bigframes/core/sql.py
  tests/unit/core/test_sql.py
Labels: api: bigquery, size: m

#1164 docs: fix `bigframes.pandas.general_function` missing docs
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: xs

#1152 feat: (Series | DataFrame).plot.bar
  bigframes/operations/_matplotlib/__init__.py
  bigframes/operations/_matplotlib/core.py
  bigframes/operations/plotting.py
  tests/system/small/operations/test_plotting.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: api: bigquery, size: m

#1172 refactor: move/clear test code
  tests/unit/resources.py
  tests/unit/test_formatting_helper.py
  tests/unit/test_formatting_helpers.py
Labels: automerge, api: bigquery, size: s

#909 docs: add a code sample using `bpd.options.bigquery.ordering_mode = "partial"`
  samples/snippets/ordering_mode_partial_test.py
Labels: samples, api: bigquery, size: s

#1169 chore: add experimental series. blob.metadata() function
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/blob.py
  bigframes/operations/type.py
  bigframes/series.py
Labels: api: bigquery, size: m

#1167 feat: add client_endpoints_override to bq options
  bigframes/_config/bigquery_options.py
  bigframes/_config/experiment_options.py
  bigframes/pandas/io/api.py
  bigframes/session/__init__.py
  bigframes/session/clients.py
  tests/unit/_config/test_bigquery_options.py
Labels: automerge, api: bigquery, size: m

#1173 chore: close session after partial ordering mode sample
  samples/snippets/ordering_mode_partial_test.py
Labels: samples, api: bigquery, size: s

#1168 feat: Allow join-free alignment of analytic expressions
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/identifiers.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/identifiers.py
  bigframes/core/rewrite/implicit_align.py
  bigframes/core/rewrite/legacy_align.py
  bigframes/core/rewrite/slices.py
  tests/system/small/test_null_index.py
  tests/system/small/test_series.py
  tests/unit/core/test_rewrite.py
  tests/unit/test_planner.py
Labels: api: bigquery, size: xl

#1144 docs: update `bigframes.pandas.Index` docstrings
  bigframes/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: l

#1178 refactor: use core.convert for series conversions under the ml packages
  bigframes/core/convert.py
  bigframes/ml/metrics/_metrics.py
  bigframes/ml/metrics/pairwise.py
  bigframes/ml/model_selection.py
  bigframes/ml/utils.py
  tests/system/small/ml/test_utils.py
Labels: api: bigquery, size: m

#1171 docs: add third party `pandas.Index methods` and docstrings
  bigframes/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: m

#1180 refactor: Move dataframe conversion function from ml package to core package
  bigframes/bigquery/_operations/search.py
  bigframes/core/convert.py
  bigframes/ml/cluster.py
  bigframes/ml/compose.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/impute.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/model_selection.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/remote.py
  bigframes/ml/utils.py
  bigframes/operations/base.py
  tests/system/small/core/test_convert.py
  tests/system/small/ml/test_utils.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: l
