Repository googleapis/python-bigquery-dataframes, pull requests merged in 2024-05, with the labels that each got.

#649 docs: fix the Palm2TextGenerator output token size
  bigframes/ml/llm.py
Labels: automerge, api: bigquery, size: xs

#650 test: explicitly use US location for session in tests
  tests/system/conftest.py
Labels: api: bigquery, size: xs

#651 fix: use explicit session in `PaLM2TextGenerator`
  bigframes/ml/llm.py
Labels: api: bigquery, size: xs

#653 fix: don't raise UnknownLocationWarning for US or EU multi-regions
  bigframes/constants.py
Labels: api: bigquery, size: xs

#585 feat: add `ARIMAPlus.coef_` property exposing `ML.ARIMA_COEFFICIENTS` functionality
  bigframes/ml/core.py
  bigframes/ml/forecasting.py
  bigframes/ml/sql.py
  tests/system/large/ml/test_forecasting.py
  tests/unit/ml/test_sql.py
Labels: api: bigquery, size: m

#553 feat: Add a unique session_id to Session and allow cleaning up sessions
  bigframes/core/global_session.py
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  tests/system/conftest.py
  tests/system/large/test_session.py
  tests/system/small/test_encryption.py
  tests/system/small/test_pandas_options.py
  tests/unit/session/test_io_bigquery.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/plotting/_core.py
Labels: automerge, api: bigquery, size: l

#657 feat: support gcf max instance count in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#638 feat: custom query labels for compute options
  bigframes/_config/compute_options.py
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#658 fix: downgrade NoDefaultIndexError to DefaultIndexWarning
  bigframes/exceptions.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: m

#652 feat: `bigframes.options` and `bigframes.option_context` now uses thread-local variables to prevent context managers in separate threads from affecting each other
  bigframes/_config/__init__.py
  bigframes/core/global_session.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_pandas_options.py
  tests/system/small/test_progress_bar.py
  third_party/bigframes_vendored/pandas/_config/config.py
Labels: api: bigquery, size: l

#659 fix: fix bug with na in the column labels in stack
  bigframes/core/__init__.py
  tests/system/small/test_multiindex.py
Labels: automerge, api: bigquery, size: s

#531 docs: add python code sample to multiple timeseries forecasting
  samples/snippets/create_multiple_timeseries_forecasting_model.py
Labels: samples, api: bigquery, size: m

#661 chore: disable BQML regression affected tests
  tests/system/large/ml/test_core.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_pipeline.py
Labels: api: bigquery, size: xs

#656 refactor: ml model load read from class type hints
  bigframes/ml/cluster.py
  bigframes/ml/decomposition.py
  bigframes/ml/ensemble.py
  bigframes/ml/forecasting.py
  bigframes/ml/imported.py
  bigframes/ml/linear_model.py
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  bigframes/ml/utils.py
  tests/system/large/ml/test_ensemble.py
Labels: api: bigquery, size: l

#654 feat: add `strategy="quantile"` in KBinsDiscretizer
  bigframes/ml/compose.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  tests/system/small/ml/test_preprocessing.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/preprocessing/_discretization.py
Labels: automerge, api: bigquery, size: m

#665 docs: address lint errors in code samples
  .kokoro/continuous/e2e.cfg
  .kokoro/presubmit/e2e-gerrit.cfg
  .kokoro/presubmit/e2e.cfg
  noxfile.py
  owlbot.py
  samples/snippets/bqml_getting_started_test.py
  samples/snippets/clustering_model_test.py
  samples/snippets/conftest.py
  samples/snippets/create_kmeans_model_test.py
  samples/snippets/create_multiple_timeseries_forecasting_model.py
  samples/snippets/create_single_timeseries_forecasting_model_test.py
  samples/snippets/explore_query_result_test.py
  samples/snippets/gemini_model_test.py
  samples/snippets/gen_ai_model_test.py
  samples/snippets/load_data_from_bigquery_test.py
  samples/snippets/load_data_from_biquery_job_test.py
  samples/snippets/load_data_from_csv_test.py
  samples/snippets/noxfile.py
  samples/snippets/noxfile_config.py
  samples/snippets/pandas_methods_test.py
  samples/snippets/quickstart.py
  samples/snippets/regression_model_test.py
  samples/snippets/remote_function.py
  samples/snippets/remote_function_test.py
  samples/snippets/requirements-test.txt
  samples/snippets/requirements.txt
  samples/snippets/set_options_test.py
Labels: samples, api: bigquery, size: l

#668 chore: remove outdated `NoDefaultIndexError` info from CHANGELOG.md
  CHANGELOG.md
Labels: api: bigquery, size: xs

#648 fix: include `index_col` when selecting `columns` and `filters` in `read_gbq_table`
  bigframes/exceptions.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  tests/system/small/test_pandas_options.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: l

#670 docs: document inlining of small data in `read_*` APIs
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/io/parquet.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
  third_party/bigframes_vendored/pandas/io/pickle.py
Labels: api: bigquery, size: s

#666 feat: suggest correct options in bpd.options.bigquery.location
  bigframes/_config/bigquery_options.py
  setup.py
  testing/constraints-3.9.txt
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: s

#669 docs: add code snippets for llm text generatiion
  samples/snippets/text_generation_test.py
Labels: automerge, samples, api: bigquery, size: m

#673 feat: add `Series.case_when()`
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/operations/base.py
  bigframes/series.py
  samples/snippets/logistic_regression_prediction_test.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#672 refactor: Distinguish between range and row windows
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/groupby/__init__.py
  bigframes/core/reshape/__init__.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/operations/aggregations.py
  bigframes/series.py
Labels: api: bigquery, size: l

#629 feat: Support `axis=1` in `df.apply` for scalar outputs
  bigframes/core/blocks.py
  bigframes/core/sql.py
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/functions/remote_function.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: l

#674 chore: log and labels update
  bigframes/core/log_adapter.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: m

#677 feat: support gcf vpc connector in `remote_function`
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: m

#680 feat: Add Series.combine
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_numpy.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#683 chore: add logger support for properties.
  bigframes/core/log_adapter.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: s

#679 docs: add code snippets for imported tensorflow model
  samples/snippets/imported_tensorflow_model_test.py
Labels: automerge, samples, api: bigquery, size: s

#684 docs: add code snippets for imported onnx tutorials
  samples/snippets/imported_onnx_model_test.py
Labels: samples, api: bigquery, size: s

#579 feat: to_datetime supports utc=False for string inputs
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/tools/datetimes.py
  bigframes/operations/__init__.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/ibis/expr/operations/generic.py
Labels: api: bigquery, size: m

#688 fix: the imported samples error and use peek()
  samples/snippets/imported_onnx_model_test.py
  samples/snippets/imported_tensorflow_model_test.py
Labels: automerge, samples, api: bigquery, size: xs

#681 fix: remove a usage of the `resource` package when not available, such as on Windows
  bigframes/pandas/__init__.py
Labels: api: bigquery, size: s

#682 fix: Improve escaping of literals and identifiers
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/sql.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/system/large/test_remote_function.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: l

#693 chore: type check with mypy `--check-untyped-defs` option
  bigframes/core/blocks.py
  bigframes/core/indexers.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/functions/remote_function.py
  bigframes/operations/__init__.py
  bigframes/operations/_matplotlib/__init__.py
  bigframes/operations/_matplotlib/core.py
  bigframes/session/clients.py
  noxfile.py
  tests/system/conftest.py
  tests/system/large/ml/test_cluster.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_forecasting.py
  tests/system/large/ml/test_linear_model.py
  tests/system/large/test_remote_function.py
  tests/system/load/test_large_tables.py
  tests/system/small/ml/test_metrics.py
  tests/system/small/ml/test_model_selection.py
  tests/system/small/operations/test_datetimes.py
  tests/system/small/operations/test_plotting.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_encryption.py
  tests/system/small/test_index.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_pandas.py
  tests/system/small/test_remote_function.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  tests/unit/ml/test_api_primitives.py
  tests/unit/test_pandas.py
Labels: api: bigquery, size: l

#690 test: stop checking ml large tests exact numbers
  tests/system/large/ml/test_cluster.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_core.py
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_forecasting.py
  tests/system/large/ml/test_linear_model.py
  tests/system/large/ml/test_pipeline.py
  tests/system/utils.py
Labels: api: bigquery, size: l

#678 docs: use `class_weight="balanced"` in the logistic regression prediction tutorial
  samples/snippets/logistic_regression_prediction_test.py
Labels: samples, api: bigquery, size: s

#691 chore: update continuous samples tests to latest bigframes release
  samples/snippets/requirements.txt
Labels: samples, api: bigquery, size: xs

#695 test: disable test_to_pandas_large_table
  tests/system/load/test_large_tables.py
Labels: api: bigquery, size: xs

#663 feat: bigframes.bigquery.array_agg(SeriesGroupBy|DataFrameGroupby)
  bigframes/bigquery/__init__.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/operations/aggregations.py
  tests/system/small/bigquery/test_array.py
  third_party/bigframes_vendored/ibis/backends/bigquery/registry.py
  third_party/bigframes_vendored/ibis/expr/operations/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/arrays.py
  third_party/bigframes_vendored/ibis/expr/operations/reductions.py
Labels: api: bigquery, size: l

#689 fix: `read_gbq_table` respects primary keys even when `filters` are set
  .pre-commit-config.yaml
  bigframes/core/blocks.py
  bigframes/core/sql.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_read_gbq_table.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: l

#696 chore: clean up type errors in test_api_primitives
  tests/unit/ml/test_api_primitives.py
Labels: api: bigquery, size: xs

#699 fix: Properly identify non-unique index in non-pk tables
  bigframes/core/compile/compiled.py
  bigframes/core/sql.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/unit/session/test_read_gbq_table.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#698 fix: type error in test_cluster
  tests/system/large/ml/test_cluster.py
Labels: api: bigquery, size: xs

#700 chore: type error in test_ensemble
  tests/system/large/ml/test_ensemble.py
Labels: api: bigquery, size: s

#702 chore: type errors in bigframes.ml tests
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_forecasting.py
  tests/system/large/ml/test_linear_model.py
Labels: automerge, api: bigquery, size: s

#662 feat: add `DefaultIndexKind.NULL` to use as `index_col` in `read_gbq*`, creating an indexless DataFrame/Series
  bigframes/core/__init__.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/indexes/base.py
  bigframes/core/rewrite.py
  bigframes/dataframe.py
  bigframes/enums.py
  bigframes/exceptions.py
  bigframes/operations/base.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/system/conftest.py
  tests/system/small/test_empty_index.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: l

#697 refactor: caching is now a session property
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/indexes/base.py
  bigframes/core/tree_properties.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#708 feat: support `ml.SimpleImputer` in bigframes
  bigframes/ml/compose.py
  bigframes/ml/impute.py
  bigframes/ml/loader.py
  bigframes/ml/pipeline.py
  bigframes/ml/preprocessing.py
  bigframes/ml/sql.py
  docs/reference/bigframes.ml/impute.rst
  docs/reference/bigframes.ml/index.rst
  docs/templates/toc.yml
  tests/system/conftest.py
  tests/system/large/ml/test_pipeline.py
  tests/system/small/ml/test_impute.py
  tests/unit/ml/test_sql.py
  third_party/bigframes_vendored/sklearn/impute/_base.py
Labels: api: bigquery, size: l

#701 docs: add examples to DataFrameGroupBy and SeriesGroupBy
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: l

#711 fix: Fix Null index assign series to column
  bigframes/dataframe.py
  tests/system/small/test_empty_index.py
Labels: api: bigquery, size: s

#712 fix: warn and disable time travel for linked datasets
  bigframes/exceptions.py
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s, status: ready for review

#720 chore: make `cleanup_cloud_functions` test fixture more robust to flakiness
  tests/system/conftest.py
Labels: api: bigquery, size: s

#721 feat: Add DataFrame `~` operator
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: s

#722 feat: ensure `"bigframes-api"` label is always set on jobs, even if the API is unknown
  .kokoro/continuous/e2e.cfg
  .kokoro/presubmit/e2e.cfg
  bigframes/core/log_adapter.py
  bigframes/dataframe.py
  bigframes/functions/remote_function.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  noxfile.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: m

#479 feat: add `GroupBy.size()` to get number of rows in each group
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/expression.py
  bigframes/core/groupby/__init__.py
  bigframes/operations/aggregations.py
  tests/system/small/test_groupby.py
  third_party/bigframes_vendored/ibis/expr/operations/analytic.py
Labels: api: bigquery, size: m

#717 feat: support type annotations to supply input and output types to `@remote_function` decorator
  bigframes/functions/remote_function.py
  tests/system/conftest.py
  tests/unit/resources.py
  tests/unit/test_pandas.py
  tests/unit/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#704 feat: allow functions decorated with `@bpd.remote_function` to execute locally
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/functions/remote_function.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: m

#725 feat: add slot_millis and add stats to session object
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  noxfile.py
Labels: api: bigquery, size: m, status: ready for review

#726 tests: fix failing e2e tests
  tests/system/large/ml/test_ensemble.py
  tests/system/large/test_remote_function.py
Labels: api: bigquery, size: s

#729 fix: set `@bpd.remote_function`s `input_types` and `output_types` default to `None` to allow omitting them when type annotations are present
  bigframes/constants.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  third_party/bigframes_vendored/constants.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/indexing.py
Labels: api: bigquery, size: m

#723 fix: correct index labels in multiple aggregations for DataFrameGroupBy
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: automerge, api: bigquery, size: m

#724 feat: Add `+`, `-` as unary ops, `^` binary op
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#709 refactor: New read node that defers ibis table instantiation
  bigframes/core/__init__.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/default_ordering.py
  bigframes/core/compile/schema_translator.py
  bigframes/core/nodes.py
  bigframes/core/schema.py
  bigframes/dtypes.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_read_gbq_table.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: l

#731 feat: adds bigframes.bigquery.array_to_string to convert array elements to delimited strings
  bigframes/bigquery/__init__.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  tests/system/small/bigquery/test_array.py
Labels: api: bigquery, size: m

#730 feat: support type annotations with `bpd.remote_function()` and `axis=1` (a preview feature)
  bigframes/functions/remote_function.py
  tests/system/small/test_remote_function.py
  tests/unit/resources.py
  tests/unit/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#737 feat: add GeminiText 1.5 Preview models
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#733 feat: `merge` only generates a default index if both inputs already have an index
  bigframes/_config/__init__.py
  bigframes/core/blocks.py
  bigframes/exceptions.py
  notebooks/dataframes/index_col_null.ipynb
  tests/system/conftest.py
  tests/system/small/test_empty_index.py
  tests/system/small/test_null_index.py
Labels: api: bigquery, size: xl

#732 perf: Optimize dataframe-series alignment on axis=1
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/dataframe.py
  bigframes/operations/base.py
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: l
