Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-02, with the labels that each got.

#1352 fix: make `DataFrame` `__getattr__` and `__setattr__` more robust to subclassing
  bigframes/dataframe.py
  tests/unit/test_dataframe.py
Labels: api: bigquery, size: m

#1347 perf: Prevent inlining of remote ops
  bigframes/core/compile/compiled.py
  bigframes/core/expression.py
  bigframes/operations/base_ops.py
  bigframes/operations/remote_function_ops.py
  third_party/bigframes_vendored/ibis/backends/sql/rewrites.py
Labels: api: bigquery, size: m

#1353 chore: reduce number of versions notebooks are tested on
  noxfile.py
Labels: api: bigquery, size: m

#1338 refactor: reorganize bigframes function tests
  tests/system/large/functions/test_remote_function.py
  tests/system/small/functions/test_remote_function.py
  tests/unit/functions/test_remote_function.py
Labels: api: bigquery, size: u

#1355 chore: avoid bq storage API deadlock by setting max_results.
  scripts/tpch_result_verify.py
  third_party/bigframes_vendored/tpch/queries/q1.py
  third_party/bigframes_vendored/tpch/queries/q10.py
  third_party/bigframes_vendored/tpch/queries/q11.py
  third_party/bigframes_vendored/tpch/queries/q12.py
  third_party/bigframes_vendored/tpch/queries/q13.py
  third_party/bigframes_vendored/tpch/queries/q14.py
  third_party/bigframes_vendored/tpch/queries/q15.py
  third_party/bigframes_vendored/tpch/queries/q16.py
  third_party/bigframes_vendored/tpch/queries/q17.py
  third_party/bigframes_vendored/tpch/queries/q18.py
  third_party/bigframes_vendored/tpch/queries/q2.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q21.py
  third_party/bigframes_vendored/tpch/queries/q22.py
  third_party/bigframes_vendored/tpch/queries/q3.py
  third_party/bigframes_vendored/tpch/queries/q4.py
  third_party/bigframes_vendored/tpch/queries/q5.py
  third_party/bigframes_vendored/tpch/queries/q6.py
  third_party/bigframes_vendored/tpch/queries/q7.py
  third_party/bigframes_vendored/tpch/queries/q8.py
  third_party/bigframes_vendored/tpch/queries/q9.py
Labels: api: bigquery, size: s

#1350 perf: Fall back to ordering by bq pk when possible
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/loader.py
  tests/unit/session/test_read_gbq_table.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#1349 chore: support timedeltas for read_pandas()
  bigframes/core/compile/compiler.py
  bigframes/core/local_data.py
  bigframes/core/schema.py
  bigframes/core/utils.py
  bigframes/dtypes.py
  bigframes/session/__init__.py
  bigframes/session/_io/pandas.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1357 test: update small `remote_function` tests path
  noxfile.py
Labels: api: bigquery, size: xs

#1356 chore: update benchmark verify code.
  scripts/tpch_result_verify.py
  third_party/bigframes_vendored/tpch/TPC-EULA.txt
  third_party/bigframes_vendored/tpch/sql_queries/q1.sql
  third_party/bigframes_vendored/tpch/sql_queries/q10.sql
  third_party/bigframes_vendored/tpch/sql_queries/q11.sql
  third_party/bigframes_vendored/tpch/sql_queries/q12.sql
  third_party/bigframes_vendored/tpch/sql_queries/q13.sql
  third_party/bigframes_vendored/tpch/sql_queries/q14.sql
  third_party/bigframes_vendored/tpch/sql_queries/q15.sql
  third_party/bigframes_vendored/tpch/sql_queries/q16.sql
  third_party/bigframes_vendored/tpch/sql_queries/q17.sql
  third_party/bigframes_vendored/tpch/sql_queries/q18.sql
  third_party/bigframes_vendored/tpch/sql_queries/q19.sql
  third_party/bigframes_vendored/tpch/sql_queries/q2.sql
  third_party/bigframes_vendored/tpch/sql_queries/q20.sql
  third_party/bigframes_vendored/tpch/sql_queries/q21.sql
  third_party/bigframes_vendored/tpch/sql_queries/q22.sql
  third_party/bigframes_vendored/tpch/sql_queries/q3.sql
  third_party/bigframes_vendored/tpch/sql_queries/q4.sql
  third_party/bigframes_vendored/tpch/sql_queries/q5.sql
  third_party/bigframes_vendored/tpch/sql_queries/q6.sql
  third_party/bigframes_vendored/tpch/sql_queries/q7.sql
  third_party/bigframes_vendored/tpch/sql_queries/q8.sql
  third_party/bigframes_vendored/tpch/sql_queries/q9.sql
Labels: api: bigquery, size: xl

#1176 docs: add link to DataFrames intro to improve SEO
  README.rst
Labels: api: bigquery, size: xs

#1359 chore: update q11
  third_party/bigframes_vendored/tpch/queries/q11.py
Labels: api: bigquery, size: s

#1318 feat: add `bigframes.bigquery.st_area` and suggest it from `GeoSeries.area`
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  notebooks/geo/geoseries.ipynb
  tests/system/small/bigquery/test_geo.py
  tests/system/small/geopandas/test_geoseries.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l

#1363 chore: Revert "remove 10t benchmark temporarily"
  tests/benchmark/tpch/config.jsonl
Labels: api: bigquery, size: xs

#1361 perf: Simplify merge join key coalescing
  bigframes/core/blocks.py
Labels: api: bigquery, size: s

#1354 fix: dtype parameter ineffective in Series/DataFrame construction
  bigframes/dtypes.py
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/arrays/arrow/accessors.py
Labels: api: bigquery, size: m

#1346 chore: support timestamp subtractions
  bigframes/core/compile/compiler.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/operators.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/datetime_ops.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/timedelta_ops.py
  bigframes/series.py
  bigframes/session/loader.py
  tests/system/small/operations/test_datetimes.py
Labels: api: bigquery, size: m

#1367 chore: add a tool to upload tpcds data to bigquery.
  scripts/dev-utils/tpcds_upload_helper.py
Labels: api: bigquery, size: l

#1368 chore: add experimental Multimodal support in Gemini
  bigframes/dataframe.py
  bigframes/ml/llm.py
Labels: api: bigquery, size: m

#1371 chore: Add __init__.py to functions test modules
  tests/system/large/functions/__init__.py
  tests/system/small/functions/__init__.py
  tests/unit/functions/__init__.py
Labels: api: bigquery, size: s

#1364 feat: add `GeoSeries.from_xy()`
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  bigframes/operations/type.py
  notebooks/geo/geoseries.ipynb
  tests/system/small/geopandas/test_geoseries.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: m

#1362 chore: support casting floats and list-likes to timedelta series
  bigframes/operations/timedelta_ops.py
  bigframes/pandas/core/tools/timedeltas.py
  tests/system/small/test_pandas.py
Labels: api: bigquery, size: m

#1366 chore: patch StreamingDataFrame impl for the upcoming required APPENDS clause
  bigframes/streaming/dataframe.py
Labels: api: bigquery, size: s

#1372 fix: translate labels to col ids when copying dataframes
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1374 chore: add experimental MutimodalEmbeddingGenerator class
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  bigframes/ml/utils.py
Labels: api: bigquery, size: m

#1376 chore: add missing bigframes package name in `pip install` in template notebook
  notebooks/getting_started/bq_dataframes_template.ipynb
Labels: api: bigquery, size: xs

#1377 chore: fix GeoSeries doc
  docs/templates/toc.yml
Labels: api: bigquery, size: xs

#1379 chore: remove discontinued sqlglot type attribute from the vendored ibis code
  third_party/bigframes_vendored/ibis/backends/sql/datatypes.py
Labels: api: bigquery, size: xs

#1369 chore: support addition between a timestamp and a timedelta
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/rewrite/operators.py
  bigframes/core/utils.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/timedelta_ops.py
  tests/data/scalars.jsonl
  tests/system/small/operations/test_timedeltas.py
  tests/unit/core/test_bf_utils.py
Labels: api: bigquery, size: l

#1380 refactor: clean up bigframes/core/__init__.py
  bigframes/core/__init__.py
  bigframes/core/array_value.py
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/order.py
  bigframes/core/rewrite/pruning.py
  bigframes/core/window/__init__.py
Labels: api: bigquery, size: xl

#1370 chore: add experimental blob.pdf_chunking function
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1382 refactor: rename rewrite.operators file to rewrite.timedeltas
  bigframes/core/compile/compiler.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/timedeltas.py
Labels: api: bigquery, size: s

#1385 refactor: resolve identifier package names in nodes.py
  bigframes/core/nodes.py
Labels: api: bigquery, size: s

#1383 chore: add experimental blob.image_resize function
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1386 refactor: Tree traversals now non-recursive
  bigframes/core/bigframe_node.py
  bigframes/core/nodes.py
  bigframes/core/tree_properties.py
  bigframes/session/executor.py
Labels: api: bigquery, size: l

#1388 chore: add experimental blob.image_normalize function
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1381 perf: Use simple null constraints to simplify queries
  bigframes/core/bigframe_node.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/isin.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/nodes.py
  tests/system/small/core/test_indexers.py
Labels: api: bigquery, size: l

#1348 docs: Add DataFrame.struct docs
  docs/reference/bigframes.geopandas/geoseries.rst
  docs/reference/bigframes.pandas/frame.rst
  docs/reference/bigframes.pandas/series.rst
  docs/templates/toc.yml
Labels: api: bigquery, size: s

#1391 feat: JSON dtype support for read_pandas and Series constructor
  bigframes/core/compile/compiler.py
  bigframes/core/utils.py
  bigframes/dtypes.py
  bigframes/session/_io/pandas.py
  bigframes/session/loader.py
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1387 chore: support comparison, ordering, and filtering for timedeltas
  bigframes/core/rewrite/timedeltas.py
  bigframes/dtypes.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: m

#1389 chore: update tpch code
  third_party/bigframes_vendored/tpch/queries/q14.py
  third_party/bigframes_vendored/tpch/queries/q17.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q22.py
  third_party/bigframes_vendored/tpch/queries/q3.py
  third_party/bigframes_vendored/tpch/queries/q5.py
Labels: api: bigquery, size: m

#1397 chore: add experimental image transform functions to BQ bytes
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1400 chore: Use isin() in tpch benchmarks
  third_party/bigframes_vendored/tpch/queries/q16.py
  third_party/bigframes_vendored/tpch/queries/q18.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q22.py
Labels: api: bigquery, size: s

#1398 perf: Prune projections more aggressively
  bigframes/core/rewrite/pruning.py
Labels: api: bigquery, size: s

#1395 perf: Simplify sum aggregate SQL text
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
Labels: api: bigquery, size: s

#1402 chore: kickstart tests for experimental blob creation
  scripts/create_gcs.py
  scripts/data/images/img0.jpg
  scripts/data/images/img1.jpg
  tests/system/small/blob/test_io.py
Labels: api: bigquery, size: m

#1404 fix: Ensure binops with pandas objects returns bigquery dataframes
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1396 chore: support operators between timedeltas
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/__init__.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/timedelta_ops.py
  bigframes/operations/type.py
  bigframes/series.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: l

#1405 feat: (Preview) Support diff aggregation for timestamp series.
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/aggregations.py
  tests/system/small/operations/test_datetimes.py
Labels: api: bigquery, size: m

#1407 chore: add max_batching_rows to experimental blob transform functions
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1399 perf: Avoid redundant SQL casts
  bigframes/core/compile/compiler.py
  bigframes/core/compile/ibis_types.py
  third_party/bigframes_vendored/ibis/expr/operations/relations.py
Labels: api: bigquery, size: m

#1406 chore: add experimental blob from_glob_path test
  tests/system/small/blob/test_io.py
Labels: api: bigquery, size: m

#1409 chore: update CHANGELOG.md to include timedelta PRs
  CHANGELOG.md
Labels: api: bigquery, size: s

#1401 feat: add `GeoSeries.from_wkt() `and `GeoSeries.to_wkt()`
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  notebooks/geo/geoseries.ipynb
  tests/system/small/geopandas/test_geoseries.py
  tests/system/small/test_dataframe_io.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l

#1411 fix: calling to_timdelta() over timedeltas no longer changes their values
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/__init__.py
  bigframes/operations/timedelta_ops.py
  tests/system/small/test_pandas.py
Labels: api: bigquery, size: m

#1403 feat: Support DF.__array__(copy=True)
  bigframes/dataframe.py
  bigframes/series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#1415 chore: Amend tpch q9 to more closely resemble sql
  third_party/bigframes_vendored/tpch/queries/q9.py
Labels: api: bigquery, size: s

#1414 chore: replace "an valid" with "a valid" in the exception messages
  bigframes/operations/json_ops.py
Labels: api: bigquery, size: s

#1416 fix: replace empty dict with None to avoid mutable default arguments
  bigframes/core/schema.py
Labels: api: bigquery, size: xs

#1310 docs: add snippets for visualizing a time series and creating a time series model for the Limit forecasted values in time series model tutorial
  samples/snippets/limit_single_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: m

#1358 docs: add samples using SQL methods via the `bigframes.bigquery` module
  samples/snippets/bigquery_modules_test.py
Labels: samples, api: bigquery, size: m

#1418 feat: (Preview) Support aggregations over timedeltas
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/aggregations.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: m

#1422 chore: add experimental blob tansform func tuning params
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1426 chore: fix experimental max_batching_rows default number
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1425 chore: add experimental blob read_gbq_object_table test
  tests/system/small/blob/test_io.py
Labels: api: bigquery, size: s

#1423 feat: (Preview) Support `diff()` for date series
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/constants.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/aggregations.py
  tests/system/small/operations/test_dates.py
Labels: api: bigquery, size: m

#1420 refactor: Simplify compile code paths
  bigframes/core/array_value.py
  bigframes/core/blocks.py
  bigframes/core/compile/__init__.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/session/executor.py
Labels: api: bigquery, size: m

#1431 fix: remove warnings for null index and partial ordering mode in prep for GA
  bigframes/core/blocks.py
  bigframes/exceptions.py
  bigframes/session/__init__.py
  notebooks/dataframes/index_col_null.ipynb
  notebooks/dataframes/pypi.ipynb
Labels: api: bigquery, size: m

#1309 perf: Speed up DataFrame corr, cov
  bigframes/core/utils.py
  bigframes/dataframe.py
  tests/system/large/test_dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#1413 feat: (Preview) Support arithmetics between dates and timedeltas
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/__init__.py
  bigframes/operations/date_ops.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/timedelta_ops.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/operations/test_dates.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: l

#1432 chore: show `FutureWarning` for LEP endpoints usage with `use_regional_endpoints=True`
  bigframes/constants.py
  bigframes/session/clients.py
  tests/system/large/test_location.py
Labels: api: bigquery, size: m

#1437 feat: iloc multiple columns selection.
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#1433 feat: Add groupby.rank()
  bigframes/core/block_transforms.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/groupby/__init__.py
  tests/system/small/test_groupby.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: l

#1428 feat: add allow_large_results option
  bigframes/_config/bigquery_options.py
  bigframes/core/blocks.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/executor.py
  tests/system/large/test_dataframe_io.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_index_io.py
  tests/system/small/test_series_io.py
  tests/unit/polars_session.py
  tests/unit/resources.py
  tests/unit/test_dataframe_io.py
  tests/unit/test_series_io.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#1438 refactor: Remove col_id_overrides from executor interfaces
  bigframes/core/array_value.py
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/session/executor.py
  tests/unit/polars_session.py
Labels: api: bigquery, size: m

#1434 refactor: Make join order propogation explicit in node
  bigframes/core/array_value.py
  bigframes/core/compile/compiler.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/order.py
Labels: api: bigquery, size: s

#1439 chore: impl experimental blob image output encodings
  bigframes/blob/_functions.py
  bigframes/core/indexers.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1435 feat: add `GeoSeries.boundary()`
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  notebooks/geo/geoseries.ipynb
  tests/system/small/geopandas/test_geoseries.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l
