Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-09, with the labels that each got.

#2007 refactor: Unify bigquery execution paths
  bigframes/core/blocks.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/execution_spec.py
  bigframes/session/executor.py
  bigframes/testing/compiler_session.py
  bigframes/testing/polars_session.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: l

#2048 refactor: Aggregation is now an expression subclass
  bigframes/core/agg_expressions.py
  bigframes/core/array_value.py
  bigframes/core/bigframe_node.py
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/ibis_compiler/aggregate_compiler.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/compile/sqlglot/aggregate_compiler.py
  bigframes/core/expression.py
  bigframes/core/groupby/aggs.py
  bigframes/core/groupby/dataframe_group_by.py
  bigframes/core/indexes/base.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/order.py
  bigframes/core/rewrite/schema_binding.py
  bigframes/core/rewrite/timedeltas.py
  bigframes/dataframe.py
  bigframes/operations/aggregations.py
  bigframes/series.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_aggregation.py
  tests/system/small/engines/test_windowing.py
  tests/unit/core/compile/sqlglot/aggregations/test_unary_compiler.py
Labels: api: bigquery, size: l

#2054 feat: Add str.join method
  bigframes/core/compile/ibis_compiler/aggregate_compiler.py
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/operations/aggregations.py
  bigframes/operations/strings.py
  tests/system/small/operations/test_strings.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/reductions.py
  third_party/bigframes_vendored/pandas/core/strings/accessor.py
Labels: api: bigquery, size: m

#2058 perf: avoid re-authenticating if credentials have already been fetched
  bigframes/_config/auth.py
  bigframes/_config/bigquery_options.py
  bigframes/session/__init__.py
  bigframes/session/clients.py
  tests/unit/pandas/io/test_api.py
Labels: api: bigquery, size: m

#2065 chore: allow method_logger to directly decorate functions with param in parentheses
  bigframes/core/log_adapter.py
  tests/unit/core/test_log_adapter.py
Labels: api: bigquery, size: m

#2062 feat: support pandas.Index as key for DataFrame.__setitem__()
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#2064 feat: support pd.cut() for array-like type
  bigframes/core/reshape/tile.py
  tests/system/small/test_pandas.py
  tests/unit/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: api: bigquery, size: s

#2067 feat: support to cast struct to json
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/dtypes.py
  bigframes/operations/generic_ops.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#2083 chore: fix e2e tests after move of bigquery-storage package
  noxfile.py
Labels: api: bigquery, size: xs

#2063 feat: Add __dataframe__ interchange support
  bigframes/core/blocks.py
  bigframes/core/interchange.py
  bigframes/dataframe.py
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
  tests/unit/test_interchange.py
Labels: api: bigquery, size: l

#2060 feat: Add ai_generate_bool to the bigframes.bigquery package
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/ai.py
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/operations/__init__.py
  bigframes/operations/ai_ops.py
  docs/reference/bigframes.bigquery/ai.rst
  docs/reference/bigframes.bigquery/index.rst
  docs/templates/toc.yml
  tests/system/large/bigquery/__init__.py
  tests/system/large/bigquery/test_ai.py
  tests/system/small/bigquery/test_ai.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/ai_ops.py
Labels: api: bigquery, size: l

#2084 feat: Add rank(pct=True) support
  bigframes/core/block_transforms.py
  bigframes/core/groupby/dataframe_group_by.py
  bigframes/core/groupby/series_group_by.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_groupby.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: m

#2091 chore: remove linked table case in time travel test
  tests/system/small/test_session.py
Labels: api: bigquery, size: xs

#2086 feat: support pandas series in ai.generate_bool
  bigframes/bigquery/_operations/ai.py
  bigframes/operations/ai_ops.py
  tests/system/small/bigquery/test_ai.py
Labels: api: bigquery, size: m

#2098 fix: Throw type error for incomparable join keys
  bigframes/core/array_value.py
  bigframes/dtypes.py
  bigframes/operations/type.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#2097 refactor: add agg_ops.MinOp and MaxOp for sqlglot compiler
  .pre-commit-config.yaml
  bigframes/core/compile/sqlglot/aggregations/unary_compiler.py
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_count/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_max/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_min/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_size_unary/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_sum/out.sql
  tests/unit/core/compile/sqlglot/aggregations/test_unary_compiler.py
Labels: api: bigquery, size: m

#2100 feat: Support callable for series map method
  bigframes/series.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: s

#2095 refactor: reorganize the sqlglot scalar compiler layout - part 3
  bigframes/core/compile/sqlglot/__init__.py
  bigframes/core/compile/sqlglot/expressions/binary_compiler.py
  bigframes/core/compile/sqlglot/expressions/blob_ops.py
  bigframes/core/compile/sqlglot/expressions/comparison_ops.py
  bigframes/core/compile/sqlglot/expressions/json_ops.py
  bigframes/core/compile/sqlglot/expressions/numeric_ops.py
  bigframes/testing/utils.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_mul_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_blob_ops/test_obj_make_ref/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_eq_null_match/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_eq_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_ge_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_gt_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_le_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_lt_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_comparison_ops/test_ne_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_datetime_ops/test_add_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_datetime_ops/test_sub_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_json_ops/test_json_set/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_add_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_div_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_div_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_floordiv_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_mul_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_sub_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_string_ops/test_add_string/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_binary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/test_blob_ops.py
  tests/unit/core/compile/sqlglot/expressions/test_comparison_ops.py
  tests/unit/core/compile/sqlglot/expressions/test_datetime_ops.py
  tests/unit/core/compile/sqlglot/expressions/test_json_ops.py
  tests/unit/core/compile/sqlglot/expressions/test_numeric_ops.py
  tests/unit/core/compile/sqlglot/expressions/test_string_ops.py
Labels: api: bigquery, size: l

#2104 fix: negative start and stop parameter values in Series.str.slice()
  tests/system/small/operations/test_strings.py
  third_party/bigframes_vendored/ibis/expr/rewrites.py
  third_party/bigframes_vendored/ibis/expr/types/strings.py
Labels: api: bigquery, size: m

#2096 refactor: add agg_ops.MeanOp for sqlglot compiler
  bigframes/core/compile/sqlglot/aggregations/unary_compiler.py
  tests/system/small/engines/test_aggregation.py
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_mean/out.sql
  tests/unit/core/compile/sqlglot/aggregations/test_unary_compiler.py
Labels: api: bigquery, size: m

#2110 refactor: add agg_ops.QuantileOp, ApproxQuartilesOp and ApproxTopCountOp to sqlglot compiler
  bigframes/core/compile/sqlglot/aggregations/op_registration.py
  bigframes/core/compile/sqlglot/aggregations/unary_compiler.py
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_approx_quartiles/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_approx_top_count/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_quantile/out.sql
  tests/unit/core/compile/sqlglot/aggregations/test_op_registration.py
  tests/unit/core/compile/sqlglot/aggregations/test_unary_compiler.py
Labels: api: bigquery, size: m

#2116 refactor: support agg_ops.CovOp and CorrOp in sqlglot compiler
  bigframes/core/compile/sqlglot/aggregations/binary_compiler.py
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_binary_compiler/test_corr/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_binary_compiler/test_cov/out.sql
  tests/unit/core/compile/sqlglot/aggregations/test_binary_compiler.py
Labels: api: bigquery, size: m

#2111 feat: add ai.generate_double to bigframes.bigquery package
  bigframes/bigquery/_operations/ai.py
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/core/compile/sqlglot/expressions/ai_ops.py
  bigframes/operations/__init__.py
  bigframes/operations/ai_ops.py
  tests/system/small/bigquery/test_ai.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_ai_ops/test_ai_generate_double/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_ai_ops/test_ai_generate_double_with_model_param/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_ai_ops.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/ai_ops.py
Labels: api: bigquery, size: l

#2117 refactor: support and, or, xor for sqlglot compiler
  bigframes/core/compile/sqlglot/__init__.py
  bigframes/core/compile/sqlglot/expressions/bool_ops.py
  bigframes/operations/type.py
  tests/system/small/engines/test_bool_ops.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_bool_ops/test_and_op/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_bool_ops/test_or_op/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_bool_ops/test_xor_op/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_bool_ops.py
Labels: api: bigquery, size: m

#2124 docs: add timedelta notebook sample
  notebooks/data_types/timedelta.ipynb
Labels: samples, api: bigquery, size: l

#2127 refactor: support agg_ops.AllOp and AnyValueOp in sqlglot compiler
  bigframes/core/compile/sqlglot/aggregations/unary_compiler.py
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_all/out.sql
  tests/unit/core/compile/sqlglot/aggregations/snapshots/test_unary_compiler/test_any_value/out.sql
  tests/unit/core/compile/sqlglot/aggregations/test_unary_compiler.py
Labels: api: bigquery, size: m
