Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-10, with the labels that each got.

#2126 refactor: support ops.mod_op for the sqlglot compiler
  bigframes/core/compile/sqlglot/expressions/numeric_ops.py
  tests/system/small/engines/test_numeric_ops.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_numeric_ops/test_mod_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_numeric_ops.py
Labels: api: bigquery, size: l

#2120 refactor: enable engine tests for sqlglot concat, filtering and string compilers
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  tests/system/small/engines/test_concat.py
  tests/system/small/engines/test_filtering.py
  tests/system/small/engines/test_strings.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_concat/test_compile_concat/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_concat/test_compile_concat_filter_sorted/out.sql
  tests/unit/core/compile/sqlglot/test_compile_concat.py
Labels: api: bigquery, size: l

#2132 feat: add ai.if_() and ai.score() to bigframes.bigquery package
  bigframes/bigquery/_operations/ai.py
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/core/compile/sqlglot/expressions/ai_ops.py
  bigframes/operations/__init__.py
  bigframes/operations/ai_ops.py
  tests/system/small/bigquery/test_ai.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_ai_ops/test_ai_if/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_ai_ops/test_ai_score/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_ai_ops.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/ai_ops.py
Labels: api: bigquery, size: l

#2134 chore: skip vector search notebook tests
  noxfile.py
Labels: api: bigquery, size: xs

#2140 fix: join on, how args are now positional
  bigframes/dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: xs

#2144 refactor: make sqlglot.from_bf_dtype() a top-level function
  bigframes/core/compile/sqlglot/expressions/generic_ops.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/core/compile/sqlglot/sqlglot_types.py
  tests/unit/core/compile/sqlglot/test_sqlglot_types.py
Labels: api: bigquery, size: m

#2148 fix: Yield row count from read session if otherwise unknown
  bigframes/session/read_api_execution.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: xs

#2115 fix: avoid possible circular imports in global session
  bigframes/core/global_session.py
  third_party/bigframes_vendored/pandas/_config/config.py
Labels: api: bigquery, size: s
