Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-08, with the labels that each got.

#1957 perf: Use promote_offsets for consistent row number generation for index.get_loc
  bigframes/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: m

#1962 test: temp disable claude related test for presubmit
  tests/system/small/ml/test_llm.py
  tests/unit/test_dataframe_polars.py
Labels: api: bigquery, size: xs

#1965 feat: retry AI/ML jobs that fail more often
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  third_party/bigframes_vendored/google_cloud_bigquery/retry.py
Labels: api: bigquery, size: l

#1966 chore: fix unit tests for `_read_gbq_colab` when Polars isn't installed
  tests/unit/pandas/io/test_api.py
Labels: api: bigquery, size: xs

#1963 feat: add `st_buffer`, `st_centroid`, and `st_convexhull` and their corresponding GeoSeries methods
  GEMINI.md
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  specs/2025-08-04-geoseries-scalars.md
  specs/TEMPLATE.md
  tests/system/small/bigquery/test_geo.py
  tests/system/small/geopandas/test_geoseries.py
Labels: api: bigquery, size: xl

#1822 chore: refactor IsNullOp and NotNullOp logic to make scalar ops generation easier
  bigframes/_importing.py
  bigframes/core/compile/__init__.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/ibis_compiler/__init__.py
  bigframes/core/compile/ibis_compiler/aggregate_compiler.py
  bigframes/core/compile/ibis_compiler/ibis_compiler.py
  bigframes/core/compile/ibis_compiler/operations/__init__.py
  bigframes/core/compile/ibis_compiler/operations/generic_ops.py
  bigframes/core/compile/ibis_compiler/scalar_op_compiler.py
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/core/compile/polars/__init__.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/compile/polars/operations/__init__.py
  bigframes/core/compile/polars/operations/generic_ops.py
  noxfile.py
  setup.py
  testing/constraints-3.10.txt
  testing/constraints-3.11.txt
  tests/system/small/pandas/test_describe.py
  tests/system/small/pandas/test_read_gbq_colab.py
  tests/system/small/test_polars_execution.py
Labels: api: bigquery, size: xl

#1956 fix: add warnings for duplicated or conflicting type hints in bigfram…
  bigframes/exceptions.py
  bigframes/functions/_function_session.py
  bigframes/functions/_utils.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1972 perf: remove an unnecessary extra `dry_run` query from `read_gbq_table`
  bigframes/exceptions.py
  bigframes/pandas/io/api.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/loader.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: l

#1973 fix: make `remote_function` more robust when there are `create_function` retries
  bigframes/functions/_function_client.py
Labels: api: bigquery, size: s

#1974 feat: Add value_counts to GroupBy classes
  bigframes/core/block_transforms.py
  bigframes/core/groupby/dataframe_group_by.py
  bigframes/core/groupby/series_group_by.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_groupby.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: l

#1976 feat: Add where, coalesce, fillna, casewhen, invert local impl
  bigframes/core/compile/polars/compiler.py
  bigframes/core/compile/polars/lowering.py
  bigframes/core/compile/polars/operations/generic_ops.py
  bigframes/operations/generic_ops.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_generic_ops.py
  third_party/bigframes_vendored/ibis/expr/operations/numeric.py
  third_party/bigframes_vendored/ibis/expr/types/binary.py
Labels: api: bigquery, size: m

#1986 docs: remove preview warning from partial ordering mode sample notebook
  notebooks/dataframes/pypi.ipynb
Labels: samples, api: bigquery, size: xs

#1980 fix: Correct pypdf dependency specifier for remote PDF functions
  bigframes/blob/_functions.py
  tests/system/large/blob/test_function.py
Labels: api: bigquery, size: m

#1889 refactor: add compile_window to the sqlglot compiler
  bigframes/core/compile/sqlglot/aggregate_compiler.py
  bigframes/core/compile/sqlglot/aggregations/unary_compiler.py
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/scalar_compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/core/rewrite/schema_binding.py
  bigframes/operations/aggregations.py
  tests/system/small/engines/test_windowing.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_window/test_compile_window_w_groupby_rolling/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_window/test_compile_window_w_min_periods/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_window/test_compile_window_w_range_rolling/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_window/test_compile_window_w_rolling/out.sql
  tests/unit/core/compile/sqlglot/test_compile_window.py
Labels: api: bigquery, size: l

#1981 style: Constrain footer to table width
  bigframes/display/table_widget.css
  bigframes/display/table_widget.js
Labels: api: bigquery, size: s

#1982 perf: Faster session startup by defering anon dataset fetch
  bigframes/session/anonymous_dataset.py
Labels: api: bigquery, size: s

#1987 chore: implement mul_op and div_op compilers
  bigframes/core/compile/sqlglot/expressions/binary_compiler.py
  tests/system/small/engines/test_numeric_ops.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_div_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_div_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_mul_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_mul_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_binary_compiler.py
Labels: api: bigquery, size: l

#1996 fix: Fix the copyright year in dbt sample files
  samples/dbt/.dbt.yml
  samples/dbt/dbt_sample_project/dbt_project.yml
  samples/dbt/dbt_sample_project/models/example/dbt_bigframes_code_sample_1.py
  samples/dbt/dbt_sample_project/models/example/dbt_bigframes_code_sample_2.py
Labels: samples, api: bigquery, size: xs

#1989 chore: implement blob scalar ops for sqlglot compilers
  bigframes/core/compile/sqlglot/expressions/binary_compiler.py
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  bigframes/operations/blob_ops.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_obj_make_ref/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_obj_fetch_metadata/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_obj_get_access_url/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_binary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: m

#1994 feat: Or, And, Xor can execute locally
  bigframes/core/compile/polars/compiler.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_bool_ops.py
Labels: api: bigquery, size: m

#2006 refactor: Consolidate all _utils unit tests of bigframes function
  tests/unit/functions/test_remote_function_utils.py
  tests/unit/functions/test_utils.py
Labels: api: bigquery, size: l

#2008 chore: implement eq, eq_null_match, ne compilers
  bigframes/core/compile/sqlglot/expressions/binary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_eq_null_match/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_eq_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_binary_compiler/test_ne_numeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_binary_compiler.py
Labels: api: bigquery, size: l

#1993 feat: Add isin local execution impl
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/compile/polars/lowering.py
  bigframes/dataframe.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_generic_ops.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#2016 test: Add unit test for get_remote_function_locations
  tests/unit/functions/test_remote_function_utils.py
Labels: api: bigquery, size: s

#2017 feat: Add reset_index names, col_level, col_fill, allow_duplicates args
  bigframes/core/blocks.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#2015 chore: implement StrPadOp, StrFindOp, StrExtractOp, StrRepeatOp, RegexReplaceStrOp and ReplaceStrOp compilers
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_regex_replace_str/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_replace_str/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_extract/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_find/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_find/out_with_end.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_find/out_with_start.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_find/out_with_start_and_end.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_pad/both.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_pad/left.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_pad/right.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_repeat/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: l

#2013 feat: Support args in series apply method
  bigframes/series.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#2020 feat: Support callable for dataframe mask method
  bigframes/dataframe.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#2025 test: Add unit test for get_hash
  tests/unit/functions/test_remote_function_utils.py
Labels: api: bigquery, size: m

#2030 feat: add parameter shuffle for ml.model_selection.train_test_split
  bigframes/ml/model_selection.py
  bigframes/ml/utils.py
  tests/system/small/ml/test_model_selection.py
Labels: api: bigquery, size: m

#2032 feat: Support string matching in local executor
  bigframes/core/compile/polars/compiler.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_strings.py
Labels: api: bigquery, size: m

#2035 chore: fix typos in bigframes.ml
  bigframes/dataframe.py
  bigframes/ml/cluster.py
  bigframes/ml/forecasting.py
  bigframes/ml/llm.py
  bigframes/ml/model_selection.py
  bigframes/ml/preprocessing.py
Labels: api: bigquery, size: s

#2019 fix: read_csv fails when check file size for wildcard gcs files
  bigframes/session/__init__.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#2037 test: add unit test for remap_variables
  tests/unit/core/rewrite/conftest.py
  tests/unit/core/rewrite/test_identifiers.py
  tests/unit/core/rewrite/test_slices.py
Labels: api: bigquery, size: m

#2038 perf: improve iter_nodes_topo performance using Kahn's algorithm
  bigframes/core/bigframe_node.py
Labels: api: bigquery, size: m

#2036 perf: Improve axis=1 aggregation performance
  bigframes/core/blocks.py
  bigframes/core/compile/ibis_compiler/aggregate_compiler.py
  bigframes/core/compile/ibis_compiler/scalar_op_registry.py
  bigframes/core/compile/polars/compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/array_ops.py
  tests/system/small/engines/conftest.py
  tests/system/small/engines/test_array_ops.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/expr/operations/arrays.py
  third_party/bigframes_vendored/ibis/expr/rewrites.py
  third_party/bigframes_vendored/ibis/expr/types/arrays.py
  third_party/bigframes_vendored/ibis/expr/types/logical.py
Labels: api: bigquery, size: m

#2034 feat: Local date accessor execution support
  bigframes/core/compile/polars/compiler.py
  bigframes/operations/datetimes.py
  bigframes/operations/frequency_ops.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_temporal_ops.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_floor_dt/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: m

#2041 test: Add unit test for get_python_version
  tests/unit/functions/test_remote_function_utils.py
Labels: api: bigquery, size: s

#2040 feat: Support pivoting unordered, unindexed dataframe
  bigframes/core/blocks.py
  bigframes/dataframe.py
  tests/system/conftest.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: m

#2042 fix: Resolve the validation issue for other arg in dataframe where me…
  bigframes/dataframe.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m
