Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-05, with the labels that each got.

#1675 docs: add a visualization notebook to BigFrame samples
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
  notebooks/visualization/tutorial.ipynb
Labels: samples, api: bigquery, size: xl

#1676 refactor: Factor out exectuor.head method into cache and execute slice
  bigframes/core/blocks.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/executor.py
Labels: api: bigquery, size: m

#1662 fix: support large lists of lists in bpd.Series() constructor
  bigframes/session/__init__.py
  bigframes/session/loader.py
  tests/system/small/bigquery/test_array.py
Labels: api: bigquery, size: m

#1683 chore: split Multimodal snippets
  samples/snippets/multimodal_test.py
Labels: samples, api: bigquery, size: xs

#1681 test: streaming test check bigtable and pubsub results
  mypy.ini
  scripts/create_bigtable.py
  scripts/create_pubsub.py
  tests/system/large/test_streaming.py
Labels: api: bigquery, size: l

#1679 refactor: add uid generator and encasualate query as cte in SQLGlotCompiler
  .pre-commit-config.yaml
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/core/guid.py
  bigframes/core/rewrite/identifiers.py
  tests/unit/core/compile/sqlglot/compiler_session.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_json_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_lists_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_structs_df/out.sql
Labels: api: bigquery, size: l

#1667 perf: `to_datetime()` now avoids caching inputs unless data is inspected to infer format
  bigframes/core/tools/datetimes.py
  tests/unit/core/tools/__init__.py
  tests/unit/core/tools/test_datetimes.py
Labels: api: bigquery, size: m

#1664 docs: update snippet for `Create a k-means` model tutorial
  samples/snippets/create_kmeans_model_test.py
Labels: samples, api: bigquery, size: s

#1684 fix: Guarantee guid thread safety across threads
  bigframes/core/guid.py
Labels: api: bigquery, size: s

#1670 test: add tests for gemini structured output array and struct types
  bigframes/ml/llm.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
Labels: api: bigquery, size: m

#1690 fix: use value equality to check types for unix epoch functions and timestamp diff
  bigframes/operations/datetime_ops.py
  tests/system/small/bigquery/test_datetime.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: m

#1687 docs: fix spacing of k-means code snippet
  samples/snippets/create_kmeans_model_test.py
Labels: samples, api: bigquery, size: xs

#1691 fix: rename columns with protected names such as `_TABLE_SUFFIX` in `to_gbq()`
  bigframes/core/utils.py
  tests/system/small/test_dataframe_io.py
Labels: api: bigquery, size: m

#1680 perf: Rechunk result pages client side
  bigframes/core/blocks.py
  bigframes/core/pyarrow_utils.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  tests/unit/core/test_pyarrow_utils.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: m

#1697 feat: add bigframes.bigquery.json_value
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/json.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#1693 feat: publish bigframes blob(Multimodal) to preview
  bigframes/_config/display_options.py
  bigframes/_config/experiment_options.py
  bigframes/dataframe.py
  bigframes/ml/llm.py
  bigframes/operations/blob.py
  bigframes/operations/strings.py
  bigframes/session/__init__.py
  notebooks/experimental/multimodal_dataframe.ipynb
  samples/snippets/multimodal_test.py
  tests/system/conftest.py
  tests/system/large/blob/test_function.py
  tests/system/small/blob/test_io.py
  tests/system/small/blob/test_properties.py
  tests/system/small/blob/test_urls.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
  tests/unit/_config/test_experiment_options.py
  third_party/bigframes_vendored/pandas/core/config_init.py
Labels: api: bigquery, size: l

#1701 fix: fix dayofyear doc test
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
Labels: api: bigquery, size: xs

#1305 feat: support forecast_limit_lower_bound and forecast_limit_upper_bou…
  .gitignore
  bigframes/ml/forecasting.py
  tests/system/large/ml/test_forecasting.py
Labels: api: bigquery, size: s

#1698 docs: include the clean-up step in the udf code snippet
  samples/snippets/udf.py
Labels: samples, api: bigquery, size: s

#1673 feat: improve error message in `Series.apply` for direct udfs
  bigframes/series.py
Labels: api: bigquery, size: s

#1677 refactor: support to compile project and add_op
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/scalar_compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/dataframe.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_projection/test_compile_projection/out.sql
  tests/unit/core/compile/sqlglot/test_compile_projection.py
Labels: api: bigquery, size: m

#1702 feat: support `mod`(`%`) operator between timedeltas
  bigframes/operations/numeric_ops.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: s

#1700 fix: Fix issues with chunked arrow data
  bigframes/core/local_data.py
  tests/unit/test_local_data.py
Labels: api: bigquery, size: s

#1705 feat: support to_strip parameter for str.strip, str.lstrip and str.rstrip
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/string_ops.py
  bigframes/operations/strings.py
  tests/system/small/operations/test_strings.py
  third_party/bigframes_vendored/pandas/core/strings/accessor.py
Labels: api: bigquery, size: m

#1707 test: enable gemini-1.5-pro-002 tests
  tests/system/load/test_llm.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
Labels: api: bigquery, size: s

#1696 deps: move bigtable and pubsub to extras
  setup.py
  tests/system/large/streaming/test_bigtable.py
  tests/system/large/streaming/test_pubsub.py
Labels: api: bigquery, size: m

#1688 chore: create private `_read_gbq_colab` which will enable partial ordering mode even when session is in strict mode
  bigframes/session/__init__.py
  bigframes/session/loader.py
  bigframes/testing/mocks.py
  tests/system/small/session/__init__.py
  tests/system/small/session/test_read_gbq_colab.py
  tests/unit/session/test_read_gbq_colab.py
Labels: api: bigquery, size: m

#1710 feat: Add inplace arg support to sort methods
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/ml/metrics/_metrics.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#1711 chore: add exif test image in scripts
  scripts/data/images_exif/test_image_exif.jpg
Labels: api: bigquery, size: u

#1712 docs: move multimodal notebook out of experimental folder
  notebooks/experimental/multimodal_dataframe.ipynb
  notebooks/multimodal/multimodal_dataframe.ipynb
  noxfile.py
Labels: api: bigquery, size: xl

#1714 docs: update blob_display option in snippets
  notebooks/multimodal/multimodal_dataframe.ipynb
  samples/snippets/multimodal_test.py
Labels: samples, api: bigquery, size: xs

#1699 docs: include import statement in the bigframes code snippet
  samples/snippets/explore_query_result_test.py
Labels: samples, api: bigquery, size: xs

#1713 feat: add `.dt.days`, `.dt.seconds`, `dt.microseconds`, and `dt.total_seconds()` for timedelta series.
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
Labels: api: bigquery, size: m

#1708 refactor: Streamline executor paths
  bigframes/core/array_value.py
  bigframes/core/compile/__init__.py
  bigframes/core/compile/api.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/executor.py
  bigframes/session/local_scan_executor.py
  bigframes/session/read_api_execution.py
  tests/system/large/test_dataframe_io.py
  tests/unit/polars_session.py
Labels: api: bigquery, size: l

#1715 chore: change error to warning for gemini models
  bigframes/ml/llm.py
  bigframes/ml/loader.py
Labels: api: bigquery, size: s

#1704 chore: add pyformat_args to _read_gbq_colab
  bigframes/core/pyformat.py
  bigframes/core/sql.py
  bigframes/session/__init__.py
  tests/system/small/session/test_read_gbq_colab.py
  tests/unit/core/test_pyformat.py
Labels: api: bigquery, size: l

#1678 chore: Revert temporary fix for q11
  third_party/bigframes_vendored/tpch/queries/q11.py
Labels: api: bigquery, size: xs

#1597 docs: deprecate `bpd.options.bigquery.allow_large_results` in favor of `bpd.options.compute.allow_large_results`
  bigframes/_config/__init__.py
  bigframes/_config/bigquery_options.py
  bigframes/_config/compute_options.py
  bigframes/session/bq_caching_executor.py
  tests/system/conftest.py
  tests/system/large/test_dataframe_io.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_index_io.py
  tests/system/small/test_progress_bar.py
  tests/system/small/test_series.py
  tests/system/small/test_series_io.py
  tests/unit/_config/test_compute_options.py
Labels: api: bigquery, size: m

#1717 feat: add `isocalendar()` for `dt` accessor
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/date_ops.py
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
Labels: api: bigquery, size: m

#1721 chore: add dry_run parameter to _read_gbq_colab
  bigframes/session/__init__.py
  bigframes/session/dry_runs.py
  bigframes/testing/mocks.py
  tests/system/small/session/test_read_gbq_colab.py
  tests/unit/session/test_read_gbq_colab.py
Labels: api: bigquery, size: m

#1660 chore: replace api_name with updated method_logger
  bigframes/core/blocks.py
  bigframes/core/log_adapter.py
  bigframes/pandas/__init__.py
  bigframes/pandas/io/api.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/anonymous_dataset.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/loader.py
  tests/unit/core/test_log_adapter.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_read_gbq_colab.py
  tests/unit/session/test_read_gbq_table.py
Labels: api: bigquery, size: l

#1716 feat: support astype conversions to and from JSON dtypes
  bigframes/core/compile/scalar_op_compiler.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/base.py
Labels: api: bigquery, size: m

#1722 chore: add code samples for Data Manipulation public doc
  samples/snippets/bigquery_modules_test.py
Labels: samples, api: bigquery, size: s

#1729 test: add gemini-2.0-flash-lite-001 test
  bigframes/ml/llm.py
  tests/system/load/test_llm.py
Labels: api: bigquery, size: xs

#1732 docs: add llm output_schema notebook
  notebooks/generative_ai/bq_dataframes_llm_output_schema.ipynb
  notebooks/multimodal/multimodal_dataframe.ipynb
Labels: api: bigquery, size: l

#1734 docs: use partial ordering mode in the quickstart sample
  samples/snippets/quickstart.py
  samples/snippets/quickstart_test.py
Labels: samples, api: bigquery, size: s

#1731 feat: Use read api for some peek ops
  bigframes/session/read_api_execution.py
  tests/system/large/test_dataframe_io.py
Labels: api: bigquery, size: s

#1736 fix: Support str.replace re.compile with flags
  bigframes/operations/strings.py
  tests/system/small/operations/test_strings.py
Labels: api: bigquery, size: s

#1727 chore: enable bigframes objects in _read_gbq_colab pyformat arg
  bigframes/core/blocks.py
  bigframes/core/pyformat.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/anonymous_dataset.py
  tests/system/small/session/test_read_gbq_colab.py
  tests/unit/session/test_read_gbq_colab.py
Labels: api: bigquery, size: m

#1737 fix: reduce bigquery table modification via DML for to_gbq
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/session/bq_caching_executor.py
  tests/system/small/test_dataframe_io.py
  tests/unit/test_dataframe_io.py
Labels: api: bigquery, size: m

#1738 perf: Faster local data comparison using idenitity
  bigframes/core/local_data.py
  tests/unit/test_local_data.py
Labels: api: bigquery, size: s

#1745 docs: updated multimodal notebook instructions
  notebooks/multimodal/multimodal_dataframe.ipynb
Labels: api: bigquery, size: s

#1723 feat: add deprecation warning to Gemini-1.5-X, text-embedding-004, and remove remove legacy models in notebooks and docs
  bigframes/ml/llm.py
  bigframes/operations/semantics.py
  notebooks/apps/synthetic_data_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_llm_vector_search.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/generative_ai/large_language_models.ipynb
  notebooks/getting_started/bq_dataframes_template.ipynb
  samples/snippets/gemini_model_test.py
  samples/snippets/multimodal_test.py
  tests/system/large/operations/conftest.py
  tests/system/large/operations/test_ai.py
  tests/system/large/operations/test_semantics.py
  tests/system/load/test_llm.py
Labels: api: bigquery, size: m

#1746 feat!: add structured output for ai map, ai filter and ai join
  bigframes/operations/ai.py
  notebooks/experimental/ai_operators.ipynb
  tests/system/large/operations/test_ai.py
  tests/system/small/operations/test_ai.py
Labels: api: bigquery, size: l

#1739 fix: Fix clip int series with float bounds
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/base.py
  bigframes/series.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1743 feat: add bpd.options.reset() method
  bigframes/_config/__init__.py
  samples/snippets/quickstart.py
Labels: api: bigquery, size: s

#1750 feat: support `unique()` for Index
  bigframes/core/indexes/base.py
  tests/system/small/core/indexes/test_base.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: m

#1757 fix: prevent creating unnecessary client objects in multithreaded environments
  bigframes/pandas/io/api.py
  bigframes/session/clients.py
Labels: api: bigquery, size: m

#1760 chore: Move polars_session.py to bigframes/testing module
  bigframes/testing/polars_session.py
  tests/unit/test_local_engine.py
Labels: api: bigquery, size: xs

#1762 deps: avoid `gcsfs==2025.5.0`
  setup.py
Labels: api: bigquery, size: xs

#1761 feat: add support for df.loc[list, column(s)]
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1764 test: remove gemini-1x model tests due to model deprecation
  tests/system/load/test_llm.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
Labels: api: bigquery, size: s

#1754 fix: support JSON and STRUCT for bbq.sql_scalar
  bigframes/bigquery/_operations/sql.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/dtypes.py
  tests/system/small/bigquery/test_sql.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal/out.sql
  third_party/bigframes_vendored/ibis/backends/bigquery/datatypes.py
Labels: api: bigquery, size: m

#1752 feat: include bq schema and query string in dry run results
  bigframes/session/dry_runs.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_index_io.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#1749 feat: support dtype parameter in read_csv for bigquery engine
  bigframes/session/__init__.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#1768 chore: add individual timeout for unit-tests
  noxfile.py
Labels: api: bigquery, size: xs

#1763 perf: use JOB_CREATION_OPTIONAL when `allow_large_results=False`
  bigframes/session/clients.py
  tests/unit/session/test_clients.py
Labels: api: bigquery, size: s

#1767 test: ignore `bigframes/testing` folder from testing
  noxfile.py
Labels: api: bigquery, size: xs

#1756 feat: add bbq.json_query and warn bbq.json_extract deprecated
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/json.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/json_ops.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#1776 test: remove deprecated gemini 1.5 tests
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1772 feat: support dict param for dataframe.agg()
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1778 perf: Optimize repr for unordered gbq table
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/slices.py
  bigframes/core/tree_properties.py
  bigframes/session/loader.py
  bigframes/session/read_api_execution.py
  tests/system/small/session/test_read_gbq_colab.py
Labels: api: bigquery, size: m

#1748 docs: fix typo for "population" in the `GeminiTextGenerator.predict(..., output_schema={...})` sample notebook
  notebooks/generative_ai/bq_dataframes_llm_output_schema.ipynb
Labels: samples, api: bigquery, size: s

#1755 feat: add `bpd.options.bigquery.requests_transport_adapters` option
  bigframes/_config/bigquery_options.py
  bigframes/pandas/io/api.py
  bigframes/session/__init__.py
  bigframes/session/clients.py
  tests/system/small/test_pandas_options.py
  tests/unit/_config/test_bigquery_options.py
  tests/unit/session/test_clients.py
Labels: api: bigquery, size: m

#1492 chore: Finish factoring unit tests from presubmit
  noxfile.py
Labels: api: bigquery, size: s

#1744 feat: support `inplace=True` in `rename` and `rename_axis`
  bigframes/core/compile/polars/compiler.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/testing/mocks.py
  bigframes/testing/polars_session.py
  tests/unit/test_dataframe.py
  tests/unit/test_index.py
  tests/unit/test_local_engine.py
  tests/unit/test_series.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#1784 docs: integrations notebook extracts token from `bqclient._http.credentials` instead of `bqclient._credentials`
  notebooks/dataframes/integrations.ipynb
Labels: api: bigquery, size: m

#1725 docs: add MatrixFactorization to the table of contents
  docs/templates/toc.yml
Labels: api: bigquery, size: xs
