Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-07, with the labels that each got.

#1871 feat: Add filter pushdown to hybrid engine
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_filtering.py
  tests/system/small/test_polars_execution.py
Labels: api: bigquery, size: m

#1881 fea: support multi index for dataframe where
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_multiindex.py
  tests/unit/test_dataframe_polars.py
Labels: api: bigquery, size: m

#1873 feat: Add simple stats support to hybrid local pushdown
  bigframes/session/polars_executor.py
  bigframes/testing/engine_utils.py
  tests/system/small/engines/test_aggregation.py
Labels: api: bigquery, size: m

#1888 feat: Add total_rows property to pandas batches iterator
  bigframes/core/blocks.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#1885 feat: add `thresh` param for Dataframe.dropna
  bigframes/core/block_transforms.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#1896 chore: add logger to plot accessor
  bigframes/operations/plotting.py
Labels: api: bigquery, size: xs

#1894 fix: DataFrame string addition respects order
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: s

#1899 feat: Add __contains__ to Index, Series, DataFrame
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_index.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_null_index.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1903 test: Run some engine tests on sqlglot compiler
  bigframes/session/direct_gbq_execution.py
  tests/system/small/engines/conftest.py
  tests/system/small/engines/test_join.py
  tests/system/small/engines/test_read_local.py
  tests/system/small/engines/test_sorting.py
Labels: api: bigquery, size: s

#1904 refactor: add compile_aggregate
  bigframes/core/compile/sqlglot/aggregate_compiler.py
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/core/rewrite/schema_binding.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_aggregate/test_compile_aggregate/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_aggregate/test_compile_aggregate_wo_dropna/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join_w_on/bool_col/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join_w_on/float64_col/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join_w_on/int64_col/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join_w_on/numeric_col/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join_w_on/string_col/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_join/test_compile_join_w_on/time_col/out.sql
  tests/unit/core/compile/sqlglot/test_compile_aggregate.py
Labels: api: bigquery, size: l

#1907 chore: update benchmark to assert on empty df returned by to_pandas_batches
  tests/benchmark/read_gbq_colab/filter_output.py
Labels: api: bigquery, size: xs

#1905 fix: bpd.merge on common columns
  bigframes/dataframe.py
  tests/system/small/test_pandas.py
Labels: api: bigquery, size: m

#1910 feat: add ml.metrics.mean_absolute_error method
  bigframes/ml/metrics/__init__.py
  bigframes/ml/metrics/_metrics.py
  tests/system/small/ml/test_metrics.py
  third_party/bigframes_vendored/sklearn/metrics/_regression.py
Labels: api: bigquery, size: m

#1909 chore: fix benchmark file count mismatch issue.
  bigframes/session/loader.py
  bigframes/session/metrics.py
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: s

#1911 feat: provide day_of_year and day_of_week for dt accessor
  bigframes/operations/datetimes.py
  tests/system/small/operations/test_datetimes.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
Labels: api: bigquery, size: m

#1897 feat: support params `max_batching_rows`, `container_cpu`, and `container_memory` for `udf`
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: m

#1917 fix: correct min field from max() to min() in remote function tests
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: xs

#1919 docs: add code snippets for session and IO public docs
  samples/snippets/sessions_and_io_test.py
Labels: samples, api: bigquery, size: m

#1923 docs: add snippets for performance optimization doc
  samples/snippets/performance_optimizations_test.py
Labels: samples, api: bigquery, size: m

#1927 tests: fixing flaky test: test_create_job_configs_labels_log_adaptor_call_method_under_length_limit
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: xs

#1915 feat: Add isin local execution to hybrid engine
  bigframes/core/compile/polars/compiler.py
  bigframes/core/rewrite/schema_binding.py
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_join.py
Labels: api: bigquery, size: m

#1925 chore: migrate 15 scalar operators to SQLGlot
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_abs/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_arccosh/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_arcsinh/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_arctanh/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_capitalize/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_ceil/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_cosh/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_date/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_day/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_dayofweek/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_dayofyear/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_exp/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_expm1/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_floor/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_tanh/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: l

#1898 feat: add code samples for dbt bigframes integration
  samples/dbt/.dbt.yml
  samples/dbt/README.md
  samples/dbt/dbt_sample_project/dbt_project.yml
  samples/dbt/dbt_sample_project/models/example/dbt_bigframes_code_sample_1.py
  samples/dbt/dbt_sample_project/models/example/dbt_bigframes_code_sample_2.py
Labels: samples, api: bigquery, size: m

#1929 chore: migrate 12 scalar operators to SQLGlot
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_hour/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_invert/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isalnum/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isalpha/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isdecimal/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isdigit/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_islower/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isnumeric/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_iso_day/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_iso_week/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isspace/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_isupper/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: l

#1930 feat: support typed pyarrow.Scalar in assignment
  bigframes/dtypes.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_session.py
  tests/unit/core/test_dtypes.py
  third_party/bigframes_vendored/ibis/common/temporal.py
  third_party/bigframes_vendored/ibis/expr/datatypes/value.py
  third_party/bigframes_vendored/ibis/formats/pyarrow.py
Labels: api: bigquery, size: m

#1932 feat: Add row numbering local pushdown in hybrid execution
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_windowing.py
Labels: api: bigquery, size: s

#1901 feat: _read_gbq_colab creates hybrid session
  bigframes/pandas/io/api.py
  tests/system/small/session/test_read_gbq_colab.py
Labels: api: bigquery, size: s

#1936 chore: Migrate up to 15 scalar operators to SQLGlot
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_len/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_ln/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_log10/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_log1p/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_lower/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_lstrip/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_neg/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_pos/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_reverse/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_rstrip/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_sqrt/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_contains/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_str_contains_regex/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_strip/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_upper/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: l

#1931 fix: add license header and correct issues in dbt sample
  samples/dbt/.dbt.yml
  samples/dbt/dbt_sample_project/dbt_project.yml
  samples/dbt/dbt_sample_project/models/example/dbt_bigframes_code_sample_1.py
  samples/dbt/dbt_sample_project/models/example/dbt_bigframes_code_sample_2.py
Labels: samples, api: bigquery, size: m

#1943 docs: add code snippet for storing dataframes to a CSV file
  samples/snippets/conftest.py
  samples/snippets/multimodal_test.py
  samples/snippets/sessions_and_io_test.py
Labels: samples, api: bigquery, size: s

#1942 chore: use `bigframes.pandas._read_gbq_colab()` in benchmarks
  tests/benchmark/read_gbq_colab/aggregate_output.py
  tests/benchmark/read_gbq_colab/dry_run.py
  tests/benchmark/read_gbq_colab/filter_output.py
  tests/benchmark/read_gbq_colab/first_page.py
  tests/benchmark/read_gbq_colab/last_page.py
  tests/benchmark/read_gbq_colab/sort_output.py
  tests/benchmark/utils.py
Labels: api: bigquery, size: m

#1946 chore: polish session/IO code examples
  samples/snippets/sessions_and_io_test.py
Labels: samples, api: bigquery, size: xs

#1952 Revert "docs: add code snippet for storing dataframes to a CSV file"
  samples/snippets/conftest.py
  samples/snippets/multimodal_test.py
  samples/snippets/sessions_and_io_test.py
Labels: samples, api: bigquery, size: s

#1947 refactor: add apply_window_if_present and get_window_order_by methods
  bigframes/core/compile/sqlglot/aggregations/nullary_compiler.py
  bigframes/core/compile/sqlglot/aggregations/unary_compiler.py
  bigframes/core/compile/sqlglot/aggregations/utils.py
  bigframes/core/compile/sqlglot/aggregations/windows.py
  bigframes/core/compile/sqlglot/compiler.py
  tests/unit/core/compile/sqlglot/aggregations/test_windows.py
Labels: api: bigquery, size: l

#1953 docs: add code snippet for storing dataframes to a CSV file
  samples/snippets/conftest.py
  samples/snippets/multimodal_test.py
  samples/snippets/sessions_and_io_test.py
Labels: samples, api: bigquery, size: s

#1941 chore: Migrate up to 15 scalar operators to SQLGlot
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_floor_dt/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_geo_st_boundary/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_geo_st_geogfromtext/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_geo_st_isclosed/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_geo_st_length/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_is_in/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_strftime/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_struct_field/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_to_datetime/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_to_timedelta/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_to_timestamp/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_unix_micros/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_unix_millis/out.sql
  tests/unit/core/compile/sqlglot/expressions/snapshots/test_unary_compiler/test_unix_seconds/out.sql
  tests/unit/core/compile/sqlglot/expressions/test_unary_compiler.py
Labels: api: bigquery, size: l
