Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-04, with the labels that each got.

#1576 chore: Update dev dependencies and blob metadata tests
  noxfile.py
  setup.py
  tests/system/small/blob/test_properties.py
  tests/unit/session/test_time.py
Labels: api: bigquery, size: s

#1571 test: move test_struct_from_dataframe with allow_large_result=False
  tests/system/small/bigquery/test_struct.py
Labels: api: bigquery, size: xs

#1577 docs: add samples for ArimiaPlus `time_series_id_col` feature
  .gitignore
  owlbot.py
  samples/snippets/create_multiple_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: m

#1579 chore: add a `scratch/` directory to gitignore
  scratch/.gitignore
Labels: api: bigquery, size: xs

#1330 feat: add support for creating a Matrix Factorization model
  bigframes/ml/core.py
  bigframes/ml/decomposition.py
  bigframes/ml/loader.py
  bigframes/ml/sql.py
  tests/data/ratings.jsonl
  tests/data/ratings_schema.json
  tests/system/conftest.py
  tests/system/large/ml/test_decomposition.py
  tests/unit/ml/test_golden_sql.py
  tests/unit/ml/test_matrix_factorization.py
  third_party/bigframes_vendored/sklearn/decomposition/_mf.py
Labels: api: bigquery, size: l

#1556 feat: add `on` parameter in `dataframe.rolling()` and `dataframe.groupby.rolling()`
  bigframes/core/blocks.py
  bigframes/core/groupby/dataframe_group_by.py
  bigframes/core/groupby/series_group_by.py
  bigframes/core/window/rolling.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_window.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: m

#1581 chore: expose blob.get_runtime_json_str as public API
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1583 chore: fix blob functions missed in cleanup set
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1585 refactor: create ai ops notebook and deprecate semantic ops notebook
  notebooks/experimental/ai_operators.ipynb
  notebooks/experimental/semantic_operators.ipynb
  noxfile.py
Labels: api: bigquery, size: xl

#1569 feat: Use session temp tables for all ephemeral storage
  bigframes/blob/_functions.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/anonymous_dataset.py
  bigframes/session/bigquery_session.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  bigframes/session/temporary_storage.py
  tests/system/large/test_session.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_encryption.py
  tests/system/small/test_index_io.py
  tests/system/small/test_series_io.py
Labels: api: bigquery, size: l

#1588 fix: ensure `page_size` works correctly in `to_pandas_batches` when `max_results` is not set
  bigframes/dataframe.py
  bigframes/series.py
  bigframes/session/executor.py
  tests/system/large/test_dataframe_io.py
Labels: api: bigquery, size: m

#1586 docs: add explain forecast snippet to multiple time series tutorial
  samples/snippets/create_multiple_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: s

#1589 feat: Support inlining small list, struct, json data
  bigframes/core/local_data.py
  bigframes/session/__init__.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_pandas.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/base.py
Labels: api: bigquery, size: m

#1591 refactor: Simplify local arrow data management
  bigframes/core/array_value.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/local_data.py
  bigframes/core/nodes.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
Labels: api: bigquery, size: m

#1594 chore: fix doctest
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: xs

#1587 chore: temporary fix for q11
  third_party/bigframes_vendored/tpch/queries/q11.py
Labels: api: bigquery, size: xs

#1595 refactor: refactor read_csv and tests based on bigquery vs. pandas behavior comparison
  bigframes/session/__init__.py
  tests/system/small/test_session.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: l

#1592 feat: add Series.to_pandas_batches() method
  bigframes/core/blocks.py
  bigframes/series.py
  tests/system/small/test_series_io.py
Labels: api: bigquery, size: m

#1590 feat: support time range rolling on Series.
  bigframes/core/array_value.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/windows.py
  bigframes/core/window/ordering.py
  bigframes/core/window/rolling.py
  bigframes/core/window_spec.py
  bigframes/series.py
  tests/system/small/test_window.py
Labels: api: bigquery, size: l

#1593 chore: relax adding objectUser role in blob creation
  bigframes/clients.py
  bigframes/operations/strings.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: s

#1573 feat: warn the deprecated `max_download_size`, `random_state` and `sampling_method` parameters in `(DataFrame|Series).to_pandas()`
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_index.py
  tests/system/small/test_index_io.py
  tests/system/small/test_series_io.py
Labels: api: bigquery, size: m

#1600 chore: revert "chore: disable managed function tests temporarily (#1532)"
  tests/system/large/blob/test_function.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: s

#1602 chore: add Multimodal notebook
  notebooks/experimental/longer_ml_demo.ipynb
  notebooks/experimental/multimodal_dataframe.ipynb
Labels: api: bigquery, size: xl

#1603 chore: exclude multimodal notebook in tests
  noxfile.py
Labels: api: bigquery, size: xs

#1596 chore: add blob snippets
  notebooks/experimental/multimodal_dataframe.ipynb
  samples/snippets/multimodal_test.py
Labels: samples, api: bigquery, size: m

#1606 chore: fix from_glob_path iam objectUser
  bigframes/session/__init__.py
Labels: api: bigquery, size: xs

#1599 refactor: add sqlglot type conversions
  bigframes/core/compile/sqlglot/__init__.py
  bigframes/core/compile/sqlglot/sqlglot_types.py
  tests/unit/core/compile/sqlglot/__init__.py
  tests/unit/core/compile/sqlglot/test_sqlglot_types.py
Labels: api: bigquery, size: m

#1605 feat: Enable time range rolling for DataFrame, DataFrameGroupBy and SeriesGroupBy
  bigframes/core/groupby/dataframe_group_by.py
  bigframes/core/groupby/series_group_by.py
  bigframes/core/window/ordering.py
  bigframes/core/window/rolling.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_window.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/groupby/__init__.py
Labels: api: bigquery, size: l

#1610 deps: remove parsy dependency
  bigframes/core/compile/scalar_op_compiler.py
  setup.py
  testing/constraints-3.9.txt
  third_party/bigframes_vendored/ibis/backends/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/expr/api.py
  third_party/bigframes_vendored/ibis/expr/datatypes/__init__.py
  third_party/bigframes_vendored/ibis/expr/datatypes/core.py
  third_party/bigframes_vendored/ibis/expr/datatypes/parse.py
  third_party/bigframes_vendored/ibis/expr/types/arrays.py
  third_party/bigframes_vendored/ibis/expr/types/generic.py
  third_party/bigframes_vendored/ibis/expr/types/json.py
  third_party/bigframes_vendored/ibis/expr/types/relations.py
Labels: api: bigquery, size: l

#1611 fix: use dictionaries to avoid problematic google.iam namespace
  bigframes/clients.py
  bigframes/functions/function.py
Labels: api: bigquery, size: s

#1609 docs: add details for `bigquery_connection` in `@bpd.udf` docstring
  bigframes/functions/_function_session.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: s

#1578 chore: move multimodal tests from PROD to TEST
  tests/system/conftest.py
  tests/system/large/blob/test_function.py
  tests/system/small/blob/test_io.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1612 feat: Use validated local storage for data uploads
  bigframes/core/array_value.py
  bigframes/core/blocks.py
  bigframes/core/local_data.py
  bigframes/core/nodes.py
  bigframes/core/schema.py
  bigframes/core/utils.py
  bigframes/dtypes.py
  bigframes/session/__init__.py
  bigframes/session/_io/pandas.py
  bigframes/session/loader.py
  tests/system/small/geopandas/test_geoseries.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_session.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: l

#1607 perf: Directly read gbq table for simple plans
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/pruning.py
  bigframes/core/rewrite/scan_reduction.py
  bigframes/session/__init__.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/executor.py
  bigframes/session/read_api_execution.py
  bigframes/session/semi_executor.py
  tests/system/large/ml/test_linear_model.py
  tests/unit/core/test_blocks.py
Labels: api: bigquery, size: xl

#1615 fix: detect duplicate column/index names in read_gbq before send query.
  bigframes/session/loader.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1616 chore: multimodal snippets has to input gcs folder
  samples/snippets/conftest.py
  samples/snippets/multimodal_test.py
Labels: samples, api: bigquery, size: s

#1620 chore: Update read_gbq_table logging to respect input api name and remove one label processing function call that should not be there
  bigframes/session/bq_caching_executor.py
  bigframes/session/loader.py
Labels: api: bigquery, size: xs

#1619 fix!: make `dataset` and `name` params mandatory in `udf`
  README.rst
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: m

#1621 deps: support a shapely versions 1.8.5+
  bigframes/core/sql.py
  bigframes/dtypes.py
  bigframes/session/_io/pandas.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/test_series.py
  tests/unit/core/test_sql.py
  third_party/bigframes_vendored/geopandas/geoseries.py
  third_party/bigframes_vendored/ibis/expr/datatypes/value.py
  third_party/bigframes_vendored/ibis/expr/types/geospatial.py
Labels: api: bigquery, size: m

#1570 docs: deprecate default model in `TextEmbedddingGenerator`, `GeminiTextGenerator`, and other `bigframes.ml.llm` classes
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: m

#1624 chore: update AI model in ai ops docs
  bigframes/operations/ai.py
  bigframes/operations/semantics.py
Labels: api: bigquery, size: s

#1625 chore: revert the change of session for llm tests
  tests/system/conftest.py
Labels: api: bigquery, size: xs

#1623 chore: move unit test utilities to bigframes.testing module, remove unnecessary skip_legacy_pandas
  bigframes/testing/__init__.py
  bigframes/testing/mocks.py
  tests/system/small/operations/test_datetimes.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_groupby.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_null_index.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  tests/system/small/test_unordered.py
  tests/system/utils.py
  tests/unit/functions/test_remote_function.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_io_pandas.py
  tests/unit/session/test_read_gbq_table.py
  tests/unit/session/test_session.py
  tests/unit/test_dataframe.py
  tests/unit/test_dataframe_io.py
  tests/unit/test_local_engine.py
  tests/unit/test_series_io.py
Labels: api: bigquery, size: l

#1626 docs: include all licenses for vendored packages in the root LICENSE file
  LICENSE
  owlbot.py
Labels: api: bigquery, size: m

#1628 chore: blob.display to support width and height params
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1614 feat: enable local json string validations
  bigframes/core/local_data.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1635 chore: improve improper naming in function session
  bigframes/functions/_function_session.py
Labels: api: bigquery, size: xs

#1613 chore: add notebook showcasing `LinearRegression` on large data
  notebooks/ml/bq_dataframes_ml_linear_regression.ipynb
  notebooks/ml/bq_dataframes_ml_linear_regression_big.ipynb
  noxfile.py
Labels: api: bigquery, size: xl

#1632 docs: add code samples in the `udf` API docstring
  bigframes/session/__init__.py
Labels: samples, api: bigquery, size: m

#1636 refactor: Unify compile paths with ResultNode
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/googlesql/expression.py
  bigframes/core/compile/googlesql/query.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/order.py
  bigframes/core/rewrite/pruning.py
  bigframes/core/rewrite/slices.py
Labels: api: bigquery, size: l

#1627 fix: add retry for test_clean_up_via_context_manager
  tests/system/large/test_session.py
Labels: api: bigquery, size: xs

#1634 fix: improve robustness of managed udf code extraction
  bigframes/functions/_function_client.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: s

#1637 feat: add `bigframes.bigquery.st_distance` function
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/bigquery/test_geo.py
  tests/system/small/geopandas/test_geoseries.py
  tests/unit/core/test_dtypes.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l

#1629 docs: note that `udf` is in preview and must be python 3.11 compatible
  bigframes/functions/_function_session.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: s

#1644 fix: Prefer remote schema instead of throwing on materialize conflicts
  bigframes/session/executor.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1641 feat: support passing list of values to `bigframes.core.sql.simple_literal`
  bigframes/core/sql.py
  tests/unit/core/test_sql.py
Labels: api: bigquery, size: m

#1646 chore: remove read_gbq for large tables test.
  tests/system/large/test_session.py
Labels: api: bigquery, size: s

#1645 chore: add tests for `to_gbq` with flexible column names
  tests/system/small/test_dataframe_io.py
Labels: api: bigquery, size: m

#1651 deps: support shapely 1.8.5+ again
  bigframes/bigquery/_operations/geo.py
  bigframes/dtypes.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/bigquery/test_geo.py
  tests/unit/core/test_dtypes.py
  tests/unit/core/test_sql.py
Labels: api: bigquery, size: m

#1618 feat: Short circuit query for local scan
  bigframes/core/local_data.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/scan_reduction.py
  bigframes/dtypes.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/local_scan_executor.py
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_session.py
  tests/unit/test_local_engine.py
Labels: api: bigquery, size: m

#1638 fix: Remove itertools.pairwise usage
  bigframes/core/local_data.py
  tests/unit/test_local_data.py
Labels: api: bigquery, size: m

#1654 perf: Use flyweight for node fields
  bigframes/core/bigframe_node.py
  bigframes/core/nodes.py
  bigframes/core/schema.py
  bigframes/core/sequences.py
  tests/unit/test_sequences.py
Labels: api: bigquery, size: l

#1655 fix: resolve some of the typo errors
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/googlesql/expression.py
Labels: api: bigquery, size: xs

#1653 feat: add GeminiTextGenerator.predict structured output
  bigframes/ml/base.py
  bigframes/ml/core.py
  bigframes/ml/globals.py
  bigframes/ml/imported.py
  bigframes/ml/llm.py
  bigframes/ml/remote.py
  bigframes/ml/sql.py
  bigframes/ml/utils.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: l

#1649 docs: add sample code snippets for `udf`
  bigframes/functions/_function_session.py
  samples/snippets/conftest.py
  samples/snippets/remote_function.py
  samples/snippets/udf.py
  samples/snippets/udf_test.py
Labels: samples, api: bigquery, size: m

#1617 feat: Support write api as loading option
  bigframes/core/local_data.py
  bigframes/core/utils.py
  bigframes/session/__init__.py
  bigframes/session/clients.py
  bigframes/session/loader.py
  setup.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_session.py
  tests/unit/core/test_bf_utils.py
  third_party/bigframes_vendored/constants.py
Labels: api: bigquery, size: l

#1491 fix: resolve issue where pre-release versions of google-auth are installed
  setup.py
Labels: api: bigquery, size: xs

#1663 refactor: add compile_readlocal for SQLGlotCompiler
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sql_gen.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/core/compile/sqlglot/sqlglot_types.py
  bigframes/core/nodes.py
  noxfile.py
  setup.py
  tests/unit/core/compile/sqlglot/conftest.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal/out.sql
  tests/unit/core/compile/sqlglot/test_compile_readlocal.py
Labels: api: bigquery, size: l

#1656 perf: Fold row count ops when known
  bigframes/core/array_value.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/fold_row_count.py
  bigframes/core/rewrite/order.py
  bigframes/core/rewrite/pruning.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/executor.py
  bigframes/session/local_scan_executor.py
  bigframes/session/read_api_execution.py
  tests/system/small/test_session.py
  tests/unit/core/test_blocks.py
Labels: api: bigquery, size: l

#1650 feat: add gemini-2.0-flash-001 and gemini-2.0-flash-lite-001 to fine tune score endponts and multimodal endpoints
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
Labels: api: bigquery, size: s

#1668 feat: DataFrames.__getitem__ support for slice input
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1669 feat: session.bytes_processed_sum will be updated when allow_large_re…
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/metrics.py
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: m

#1659 feat: support names parameter in read_csv for bigquery engine
  bigframes/core/utils.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
  tests/unit/session/test_session.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
Labels: api: bigquery, size: l

#1672 refactor: implements `compile_selection` method
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/scalar_compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal/out.sql
Labels: api: bigquery, size: m

#1666 refactor: support all data types for readlocal compiler
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  tests/data/scalars.jsonl
  tests/unit/core/compile/sqlglot/conftest.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_json_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_lists_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_nested_structs_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_structs_df/out.sql
  tests/unit/core/compile/sqlglot/test_compile_readlocal.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
Labels: api: bigquery, size: l
