Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-06, with the labels that each got.

#1786 fix: replace function now can handle bpd.NA value.
  bigframes/dtypes.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/ibis/expr/types/core.py
Labels: api: bigquery, size: s

#1781 feat: implement ai.classify()
  bigframes/operations/ai.py
  tests/system/large/operations/test_ai.py
  tests/system/small/operations/test_ai.py
Labels: api: bigquery, size: m

#1788 docs: fix docstrings to improve html rendering of code examples
  third_party/bigframes_vendored/pandas/core/computation/eval.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/indexes/accessor.py
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: xs

#1777 chore: use faster query_and_wait API in _read_gbq_colab
  bigframes/blob/_functions.py
  bigframes/core/array_value.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/local_data.py
  bigframes/core/nodes.py
  bigframes/core/pyarrow_utils.py
  bigframes/core/rewrite/scan_reduction.py
  bigframes/core/rewrite/slices.py
  bigframes/core/schema.py
  bigframes/functions/_function_client.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/_io/bigquery/read_gbq_query.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/loader.py
  bigframes/session/local_scan_executor.py
  bigframes/session/metrics.py
  bigframes/testing/mocks.py
  tests/system/small/functions/test_remote_function.py
  tests/system/small/session/test_read_gbq_colab.py
  tests/system/small/test_encryption.py
  tests/unit/session/test_io_bigquery.py
  tests/unit/session/test_local_scan_executor.py
  tests/unit/session/test_read_gbq_colab.py
  tests/unit/session/test_read_gbq_query.py
  tests/unit/session/test_read_gbq_table.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: l

#1773 feat: add blob.transcribe function
  bigframes/operations/blob.py
  scripts/data/audio/audio_LJ001-0010.wav
  scripts/data/pdfs/pdfs_sample-local-pdf.pdf
  scripts/data/pdfs/test-protected.pdf
  tests/system/conftest.py
  tests/system/large/blob/test_function.py
Labels: api: bigquery, size: m

#1785 fix: read_csv with both index_col and use_cols inconsistent with pandas
  bigframes/session/__init__.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1791 feat: Implement ST_LENGTH geography function
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  tests/system/small/bigquery/test_geo.py
  tests/system/small/geopandas/test_geoseries.py
Labels: api: bigquery, size: m

#1789 feat: Implement ST_ISCLOSED geography function
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  tests/system/small/bigquery/test_geo.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: m

#1800 test: Engine tests for selection ops
  tests/system/small/engines/conftest.py
  tests/system/small/engines/engine_utils.py
  tests/system/small/engines/test_read_local.py
  tests/system/small/engines/test_selection.py
Labels: api: bigquery, size: m

#1803 fix: Fix single row broadcast with null index
  bigframes/core/blocks.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1802 chore: prevent location warning when `_read_gbq_colab` can determine the location
  bigframes/pandas/io/api.py
  tests/unit/pandas/io/test_api.py
Labels: api: bigquery, size: m

#1810 chore: Move remaining test utils to bigframes.testing module
  bigframes/testing/compiler_session.py
  bigframes/testing/engine_utils.py
  bigframes/testing/utils.py
  pytest.ini
  scripts/__init__.py
  scripts/conftest.py
  scripts/test_publish_api_coverage.py
  tests/system/conftest.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
  tests/system/large/ml/test_cluster.py
  tests/system/large/ml/test_compose.py
  tests/system/large/ml/test_core.py
  tests/system/large/ml/test_decomposition.py
  tests/system/large/ml/test_ensemble.py
  tests/system/large/ml/test_forecasting.py
  tests/system/large/ml/test_linear_model.py
  tests/system/large/ml/test_model_selection.py
  tests/system/large/ml/test_pipeline.py
  tests/system/load/test_llm.py
  tests/system/small/bigquery/test_vector_search.py
  tests/system/small/engines/test_read_local.py
  tests/system/small/engines/test_selection.py
  tests/system/small/functions/test_remote_function.py
  tests/system/small/geopandas/test_geoseries.py
  tests/system/small/ml/test_cluster.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_decomposition.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_multimodal_llm.py
  tests/system/small/ml/test_preprocessing.py
  tests/system/small/operations/test_datetimes.py
  tests/system/small/operations/test_lists.py
  tests/system/small/operations/test_strings.py
  tests/system/small/regression/test_issue355_merge_after_filter.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_encryption.py
  tests/system/small/test_groupby.py
  tests/system/small/test_index.py
  tests/system/small/test_large_local_data.py
  tests/system/small/test_multiindex.py
  tests/system/small/test_pandas.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
  tests/system/small/test_unordered.py
  tests/unit/core/compile/sqlglot/conftest.py
  tests/unit/test_dataframe_polars.py
Labels: api: bigquery, size: m

#1808 docs: document how to use ai.map() for information extraction
  bigframes/operations/ai.py
  notebooks/experimental/ai_operators.ipynb
Labels: api: bigquery, size: m

#1807 refactor: Polars scalar op uses singledispatchmethod
  bigframes/core/compile/polars/compiler.py
  bigframes/operations/base_ops.py
  bigframes/operations/blob_ops.py
  bigframes/operations/bool_ops.py
  bigframes/operations/comparison_ops.py
  bigframes/operations/date_ops.py
  bigframes/operations/datetime_ops.py
  bigframes/operations/distance_ops.py
  bigframes/operations/generic_ops.py
  bigframes/operations/geo_ops.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/string_ops.py
  bigframes/operations/time_ops.py
Labels: api: bigquery, size: l

#1796 feat: support custom build service account in `remote_function`
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1811 feat: add bbq.json_query_array and warn bbq.json_extract_array deprecated
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/json.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/json_ops.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#1814 refactor: Refactor udf definitions
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/functions/__init__.py
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/functions/_utils.py
  bigframes/functions/function.py
  bigframes/functions/function_typing.py
  bigframes/functions/udf_def.py
  bigframes/operations/remote_function_ops.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/testing/polars_session.py
  tests/system/conftest.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
  tests/system/small/functions/test_remote_function.py
  tests/unit/core/test_dtypes.py
  tests/unit/functions/test_remote_function.py
  tests/unit/functions/test_remote_function_utils.py
  third_party/bigframes_vendored/ibis/expr/operations/udf.py
Labels: api: bigquery, size: xl

#1818 feat: Add bbq.json_value_array and deprecate bbq.json_extract_string_array
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/json.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/json_ops.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#1825 docs: use pandas API instead of pandas-like or pandas-compatible
  README.rst
  notebooks/getting_started/bq_dataframes_template.ipynb
  third_party/bigframes_vendored/pandas/io/gbq.py
Labels: api: bigquery, size: xs

#1824 chore: compile concat nodes by sqlglot
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_concat/test_compile_concat/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_projection/test_compile_projection/out.sql
  tests/unit/core/compile/sqlglot/test_compile_concat.py
Labels: api: bigquery, size: m

#1821 chore: inject dtypes to SQLGlot scalar expr compiler
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/scalar_compiler.py
  bigframes/core/rewrite/schema_binding.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_limit/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_ordering/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_scalar_expr/test_compile_numerical_add/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_scalar_expr/test_compile_string_add/out.sql
  tests/unit/core/compile/sqlglot/test_compile_scalar_expr.py
Labels: api: bigquery, size: m

#1820 feat: Add `bpd.options.display.repr_mode = "anywidget"` to create an interactive display of the results
  bigframes/_config/display_options.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/series.py
  mypy.ini
  notebooks/dataframes/anywidget_mode.ipynb
  noxfile.py
  setup.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_progress_bar.py
Labels: api: bigquery, size: m

#1833 chore: remove squash_selections from sqlglot_ir
  bigframes/core/compile/googlesql/query.py
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  bigframes/core/rewrite/pruning.py
Labels: api: bigquery, size: m

#1836 perf: Produce simpler sql
  bigframes/core/compile/compiler.py
  bigframes/core/compile/googlesql/query.py
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/select_pullup.py
  bigframes/core/utils.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_concat/test_compile_concat/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_json_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_lists_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_structs_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_limit/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_ordering/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_scalar_expr/test_compile_numerical_add/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_scalar_expr/test_compile_numerical_add_w_scalar/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_scalar_expr/test_compile_string_add/out.sql
  tests/unit/core/test_bf_utils.py
Labels: api: bigquery, size: l

#1840 docs: add ai.forecast notebook
  notebooks/generative_ai/bq_dataframes_ai_forecast.ipynb
Labels: api: bigquery, size: xl

#1844 docs: update ai.forecast notebook
  notebooks/generative_ai/bq_dataframes_ai_forecast.ipynb
Labels: api: bigquery, size: xl

#1843 chore: add more types for read_gbq_table in conftest
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  tests/unit/core/compile/sqlglot/conftest.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_concat/test_compile_concat/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readlocal/test_compile_readlocal_w_json_df/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_json_types/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_nested_structs_types/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_readtable/test_compile_readtable_w_repeated_types/out.sql
  tests/unit/core/compile/sqlglot/test_compile_readlocal.py
  tests/unit/core/compile/sqlglot/test_compile_readtable.py
  third_party/bigframes_vendored/google_cloud_bigquery/_pandas_helpers.py
Labels: api: bigquery, size: m

#1847 docs: add data visualization samples for public doc
  samples/snippets/data_visualization_test.py
Labels: samples, api: bigquery, size: m

#1842 chore!: remove ai.top_k().
  bigframes/operations/ai.py
  notebooks/experimental/ai_operators.ipynb
  tests/system/large/operations/test_ai.py
  tests/system/small/operations/test_ai.py
Labels: api: bigquery, size: l

#1832 feat: create `deploy_remote_function` and `deploy_udf` functions to immediately deploy functions to BigQuery
  bigframes/core/global_session.py
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/unit/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1850 refactor: provide infrastructure for SQLGlot scalar compiler
  bigframes/core/compile/sqlglot/expressions/__init__.py
  bigframes/core/compile/sqlglot/expressions/binary_compiler.py
  bigframes/core/compile/sqlglot/expressions/nary_compiler.py
  bigframes/core/compile/sqlglot/expressions/op_registration.py
  bigframes/core/compile/sqlglot/expressions/ternary_compiler.py
  bigframes/core/compile/sqlglot/expressions/typed_expr.py
  bigframes/core/compile/sqlglot/expressions/unary_compiler.py
  bigframes/core/compile/sqlglot/scalar_compiler.py
Labels: api: bigquery, size: l

#1848 chore: add compile_explode
  bigframes/core/compile/sqlglot/compiler.py
  bigframes/core/compile/sqlglot/sqlglot_ir.py
  tests/unit/core/compile/sqlglot/snapshots/test_compile_explode/test_compile_explode_dataframe/out.sql
  tests/unit/core/compile/sqlglot/snapshots/test_compile_explode/test_compile_explode_series/out.sql
  tests/unit/core/compile/sqlglot/test_compile_explode.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#1846 chore: add script to generate `_read_gbq_colab` BigQuery benchmark tables
  .pre-commit-config.yaml
  noxfile.py
  scripts/create_read_gbq_colab_benchmark_tables.py
  scripts/create_read_gbq_colab_benchmark_tables_test.py
  scripts/readme-gen/readme_gen.py
Labels: api: bigquery, size: l

#1856 test: Enable floordiv local testing
  bigframes/core/compile/polars/compiler.py
  bigframes/core/compile/polars/lowering.py
  bigframes/core/expression.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/op_lowering.py
  tests/unit/test_dataframe_polars.py
Labels: api: bigquery, size: m

#1747 feat: Add experimental polars execution
  bigframes/_config/bigquery_options.py
  bigframes/_importing.py
  bigframes/core/compile/polars/compiler.py
  bigframes/session/__init__.py
  bigframes/session/bq_caching_executor.py
  bigframes/session/polars_executor.py
  bigframes/testing/polars_session.py
  noxfile.py
  testing/constraints-3.10.txt
  tests/system/small/test_polars_execution.py
Labels: api: bigquery, size: m

#1865 feat: Add size op support in local engine
  bigframes/session/polars_executor.py
  tests/system/small/engines/test_aggregation.py
Labels: api: bigquery, size: m

#1868 feat: support index item assign in Series
  bigframes/core/indexes/base.py
  tests/system/small/test_index.py
Labels: api: bigquery, size: s

#1860 chore: add benchmarks for read_gbq_colab
  tests/benchmark/.gitignore
  tests/benchmark/read_gbq_colab/aggregate_output.py
  tests/benchmark/read_gbq_colab/config.jsonl
  tests/benchmark/read_gbq_colab/dry_run.py
  tests/benchmark/read_gbq_colab/filter_output.py
  tests/benchmark/read_gbq_colab/first_page.py
  tests/benchmark/read_gbq_colab/last_page.py
  tests/benchmark/read_gbq_colab/sort_output.py
  tests/benchmark/utils.py
Labels: api: bigquery, size: l

#1869 docs: upload logo to repo
  third_party/logo/colab-logo.png
  third_party/logo/github-logo.png
Labels: api: bigquery, size: u

#1862 refactor: rename scalars_types_df to scalar_types_df
  tests/unit/core/compile/sqlglot/conftest.py
  tests/unit/core/compile/sqlglot/expressions/test_binary_compiler.py
  tests/unit/core/compile/sqlglot/test_compile_concat.py
  tests/unit/core/compile/sqlglot/test_compile_filter.py
  tests/unit/core/compile/sqlglot/test_compile_readlocal.py
  tests/unit/core/compile/sqlglot/test_compile_readtable.py
Labels: api: bigquery, size: s

#1866 docs: changed broken logo
  notebooks/experimental/ai_operators.ipynb
  notebooks/generative_ai/bq_dataframes_ai_forecast.ipynb
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_llm_output_schema.ipynb
  notebooks/generative_ai/bq_dataframes_llm_vector_search.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/getting_started/bq_dataframes_template.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
  notebooks/ml/bq_dataframes_ml_linear_regression.ipynb
  notebooks/ml/bq_dataframes_ml_linear_regression_big.ipynb
  notebooks/multimodal/multimodal_dataframe.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
  notebooks/visualization/tutorial.ipynb
Labels: api: bigquery, size: m

#1855 feat: add `bpd.read_arrow` to convert an Arrow object into a bigframes DataFrame
  bigframes/core/blocks.py
  bigframes/pandas/__init__.py
  bigframes/pandas/io/api.py
  bigframes/session/__init__.py
  tests/unit/session/test_io_arrow.py
Labels: api: bigquery, size: m
