Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-03, with the labels that each got.

#1424 feat: warn if default cloud_function_service_account is used
  bigframes/functions/_function_session.py
  bigframes/session/__init__.py
  notebooks/remote_functions/remote_function_usecases.ipynb
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1444 chore: write chunked text instead of dummy text for pdf chunk
  bigframes/blob/_functions.py
Labels: api: bigquery, size: xs

#1441 chore: double the stale cloud function cleanup rate
  noxfile.py
Labels: api: bigquery, size: xs

#1419 feat: warn if default ingress_settings is used in remote_functions
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1445 chore: track release date for each version
  bigframes/version.py
Labels: api: bigquery, size: xs

#1429 feat: (Preview) Support automatic load of timedelta from BQ tables.
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/session/executor.py
  tests/system/small/test_dataframe_io.py
Labels: api: bigquery, size: m

#1450 chore: add version file paths to release-please confg
  .github/release-please.yml
  owlbot.py
  third_party/bigframes_vendored/version.py
Labels: api: bigquery, owlbot:ignore, size: xs

#1452 fix: do not compare schema description during schema validation
  bigframes/session/executor.py
Labels: api: bigquery, size: s

#1451 fix: window operations over JSON columns
  bigframes/core/compile/compiled.py
  tests/data/json.jsonl
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1448 feat: add allow_large_results to peek
  bigframes/core/blocks.py
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
  bigframes/functions/_function_client.py
  bigframes/series.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  bigframes/session/metrics.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_index_io.py
  tests/system/small/test_series.py
  tests/system/small/test_series_io.py
  tests/unit/polars_session.py
Labels: api: bigquery, size: l

#1454 fix: install cryptograph>=3.1
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: xs

#1449 chore: add experimental blob properties tests
  tests/system/small/blob/conftest.py
  tests/system/small/blob/test_io.py
  tests/system/small/blob/test_properties.py
Labels: api: bigquery, size: m

#1447 chore: format warning message with newlines and ansi color
  bigframes/_config/bigquery_options.py
  bigframes/_config/experiment_options.py
  bigframes/core/array_value.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/global_session.py
  bigframes/core/indexers.py
  bigframes/core/utils.py
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/functions/_function_session.py
  bigframes/functions/function.py
  bigframes/ml/base.py
  bigframes/ml/llm.py
  bigframes/ml/remote.py
  bigframes/operations/_matplotlib/core.py
  bigframes/operations/semantics.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/clients.py
  bigframes/session/executor.py
  bigframes/streaming/dataframe.py
  tests/system/large/test_dataframe_io.py
  tests/system/large/test_location.py
  tests/system/small/functions/test_remote_function.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: l

#1456 fix: Fix list-like indexers in partial ordering mode
  bigframes/core/blocks.py
  bigframes/core/indexers.py
  bigframes/dataframe.py
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#1461 fix: fix the merge issue between 1424 and 1373
  bigframes/functions/_function_session.py
Labels: api: bigquery, size: s

#1469 chore: add experimental blob functions retry and timeout
  bigframes/blob/_functions.py
Labels: api: bigquery, size: m

#1468 test: add unit tests for udf experiment options
  tests/unit/_config/test_experiment_options.py
Labels: api: bigquery, size: s

#1467 chore: fix Multimodal Gemini modifies input DF
  bigframes/core/convert.py
  tests/system/small/core/test_convert.py
  tests/unit/ml/test_golden_sql.py
Labels: api: bigquery, size: s

#1464 perf: Compilation no longer bounded by recursion
  bigframes/core/bigframe_node.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiler.py
  bigframes/session/executor.py
Labels: api: bigquery, size: l

#1472 chore: fix experimental blob docs
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1477 test: pin to older pandas-stubs
  noxfile.py
Labels: api: bigquery, size: xs

#1474 test: target e2e tests to python 3.11 for max coverage
  bigframes/functions/_function_session.py
  noxfile.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1458 feat!: reading JSON data as a custom arrow extension type
  bigframes/bigquery/_operations/json.py
  bigframes/core/array_value.py
  bigframes/core/compile/ibis_types.py
  bigframes/dtypes.py
  bigframes/session/_io/pandas.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1480 fix: use `==` instead of `is` for timedelta type equality checks
  bigframes/core/rewrite/timedeltas.py
  bigframes/operations/aggregations.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/timedelta_ops.py
  tests/system/small/operations/test_timedeltas.py
Labels: api: bigquery, size: m

#1482 chore: add experimental blob image_blur tests
  tests/system/conftest.py
  tests/system/large/blob/test_function.py
  tests/system/small/blob/conftest.py
Labels: api: bigquery, size: m

#1483 chore: remove skipif decorator in managed function large tests
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: s

#1453 chore: remove unused files
  .github/.OwlBot.lock.yaml
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docker/docs/requirements.in
  .kokoro/docker/docs/requirements.txt
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit-gerrit.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/docs/docs.cfg
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/release/common.cfg
  .kokoro/release/release.cfg
  .kokoro/requirements.in
  .kokoro/requirements.txt
  owlbot.py
Labels: api: bigquery, size: xl

#1460 chore: Add mypy github action
  .github/sync-repo-settings.yaml
  .github/workflows/mypy.yml
  noxfile.py
Labels: api: bigquery, size: s

#1459 chore: Remove most unit tests, lint, doc testing from kokoro presubmit
  noxfile.py
Labels: api: bigquery, size: xs

#1455 feat: warn when the BigFrames version is more than a year old
  bigframes/exceptions.py
  bigframes/session/__init__.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: s

#1484 chore: fix experimental blob display in partial ordering mode
  bigframes/operations/blob.py
Labels: api: bigquery, size: xs

#1486 chore: add experimental multimodal model tests
  tests/system/small/ml/test_llm.py
  tests/system/utils.py
Labels: api: bigquery, size: m

#1470 chore: add feedback link to all functions exceptions
  bigframes/dataframe.py
  bigframes/formatting_helpers.py
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/functions/_utils.py
  bigframes/functions/function.py
  tests/system/small/functions/test_remote_function.py
  tests/unit/functions/test_remote_function_utils.py
  third_party/bigframes_vendored/constants.py
Labels: api: bigquery, size: m

#1487 chore: enable multi-model input for sem_map and sem_filter
  bigframes/operations/semantics.py
  tests/system/large/operations/test_semantics.py
  tests/system/small/operations/test_semantics.py
Labels: api: bigquery, size: l

#1489 perf: eliminate count queries in llm retry
  bigframes/ml/base.py
Labels: api: bigquery, size: s

#1478 test: use jobless query api for faster tests
  tests/system/conftest.py
  tests/system/small/bigquery/test_json.py
  tests/system/small/bigquery/test_struct.py
  tests/system/small/blob/test_properties.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_encryption.py
  tests/system/small/test_groupby.py
  tests/system/small/test_index_io.py
  tests/system/small/test_pandas_options.py
  tests/system/small/test_progress_bar.py
  tests/system/small/test_series.py
  tests/system/small/test_series_io.py
  tests/system/small/test_session.py
  tests/system/small/test_unordered.py
Labels: api: bigquery, size: l

#1493 chore: skip small udf tests from system and coverage tests
  noxfile.py
  tests/system/small/functions/test_managed_function.py
Labels: api: bigquery, size: s

#1495 chore: add experimental blob image functions tests
  tests/system/large/blob/test_function.py
Labels: api: bigquery, size: m

#963 fix: Fix read_gbq with ORDER BY query and index_col set
  bigframes/core/blocks.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: s

#1498 chore: remove ANSI color codes from warning messages
  bigframes/exceptions.py
Labels: api: bigquery, size: s

#1476 feat: support BQ managed functions through `read_gbq_function`
  bigframes/dataframe.py
  bigframes/functions/_function_session.py
  bigframes/functions/function.py
  bigframes/series.py
  tests/system/large/functions/test_managed_function.py
  tests/system/large/functions/test_remote_function.py
  tests/system/small/functions/test_managed_function.py
  tests/system/small/functions/test_remote_function.py
Labels: api: bigquery, size: l

#1499 fix: fix pandas.cut errors with empty bins
  bigframes/core/reshape/tile.py
  bigframes/operations/aggregations.py
  tests/system/small/test_pandas.py
  tests/unit/test_pandas.py
Labels: api: bigquery, size: m

#1500 docs: add a sample notebook for vector search
  notebooks/generative_ai/bq_dataframes_llm_vector_search.ipynb
  noxfile.py
Labels: samples, api: bigquery, size: xl

#1501 test: remove peek with allow_large_result test milisecond
  tests/system/conftest.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1502 chore: remove unused import in function.py
  bigframes/functions/function.py
Labels: api: bigquery, size: xs

#1497 feat: Allow iloc to support lists of negative indices
  bigframes/core/indexers.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#1509 feat: add df.take and series.take
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/generic.py
Labels: api: bigquery, size: m

#1515 chore: Ignore mypy false positive
  bigframes/core/indexes/base.py
  bigframes/dataframe.py
Labels: api: bigquery, size: xs

#1504 chore: runs 'pip freeze' in system tests for debugging
  noxfile.py
Labels: api: bigquery, size: xs

#1517 chore: fix the change the default value for pdf extract/chunk
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1505 fix: tolerate BQ connection service account propagation delay
  bigframes/clients.py
Labels: api: bigquery, size: s

#1518 chore: Covid notebook uses partial ordering mode
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
Labels: api: bigquery, size: m

#1516 chore: throws NotImplementedError when read_pandas with nested JSON type
  bigframes/core/utils.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1520 refactor: Separate dataset id generation from temp table management
  bigframes/blob/_functions.py
  bigframes/dataframe.py
  bigframes/session/__init__.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  bigframes/session/temp_storage.py
  tests/system/large/test_session.py
  tests/system/small/test_encryption.py
Labels: api: bigquery, size: m

#1471 feat: add `GeoSeries.difference()` and `bigframes.bigquery.st_difference()`
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  bigframes/operations/type.py
  notebooks/geo/geoseries.ipynb
  tests/system/small/bigquery/test_geo.py
  tests/system/small/geopandas/test_geoseries.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l

#1523 test: fix json tests fail locally with disable allow_large_results
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_session.py
  tests/unit/bigquery/__init__.py
  tests/unit/bigquery/test_json.py
Labels: api: bigquery, size: l

#1522 chore: assert test udfs active deletion, make pre-commit mypy dep consistent with nox
  .pre-commit-config.yaml
  tests/system/large/functions/test_managed_function.py
  tests/system/utils.py
Labels: api: bigquery, size: s

#1525 fix: Raise error for large inline DataFrames in read_pandas
  bigframes/session/__init__.py
  tests/unit/session/test_session.py
Labels: api: bigquery, size: m

#1532 chore: disable managed function tests temporarily
  tests/system/large/blob/test_function.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: s

#1507 chore: allow PRECEDING and FOLLOWING to appear on both side of BETWEEN when windowing
  bigframes/core/block_transforms.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/groupby/__init__.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/unit/core/test_windowspec.py
Labels: api: bigquery, size: m

#1531 chore: include source columns in semantics.top_k
  bigframes/operations/semantics.py
Labels: api: bigquery, size: s

#1446 feat: add Linear_Regression.global_explain()
  bigframes/ml/core.py
  bigframes/ml/linear_model.py
  bigframes/ml/sql.py
  samples/snippets/linear_regression_tutorial_test.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_linear_model.py
Labels: api: bigquery, size: m

#1535 chore: set up release-please for previous major version (1.x)
  .github/release-please.yml
Labels: api: bigquery, size: xs

#1512 feat: Support window partition by geo column
  bigframes/core/compile/compiled.py
  tests/system/small/geopandas/test_geoseries.py
Labels: api: bigquery, size: s

#1534 feat: add deprecation warning to GeminiTextGenerator model
  bigframes/ml/llm.py
  notebooks/apps/synthetic_data_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_llm_vector_search.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/generative_ai/large_language_models.ipynb
  notebooks/getting_started/bq_dataframes_template.ipynb
  samples/snippets/gemini_model_test.py
  tests/system/load/test_llm.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: xl

#1533 fix: temporary fix for StreamingDataFrame not working backend bug
  bigframes/streaming/dataframe.py
Labels: api: bigquery, size: xs

#1530 chore: cleanup udf resources in blob transform functions
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1538 chore: rewrite function axis=1 warning in blob transform functions
  bigframes/dataframe.py
  bigframes/exceptions.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1529 feat: add `GeoSeries.intersection()` and `bigframes.bigquery.st_intersection()`
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/geo.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/geopandas/geoseries.py
  bigframes/operations/__init__.py
  bigframes/operations/geo_ops.py
  notebooks/geo/geoseries.ipynb
  tests/system/small/bigquery/test_geo.py
  tests/system/small/geopandas/test_geoseries.py
  third_party/bigframes_vendored/geopandas/geoseries.py
Labels: api: bigquery, size: l

#1545 chore: update benchmark logic to respect allow_large_results=False
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/metrics.py
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: m

#1539 feat: add `closed` parameter in rolling()
  bigframes/core/groupby/__init__.py
  bigframes/core/window_spec.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/test_window.py
  tests/unit/core/test_windowspec.py
Labels: api: bigquery, size: l

#1514 fix: Local data always has sequential index
  bigframes/core/indexes/base.py
  bigframes/operations/base.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: m

#1490 chore: add error handle for pdf extract and pdf chunk
  bigframes/blob/_functions.py
  bigframes/operations/blob.py
  tests/system/conftest.py
  tests/system/large/blob/test_function.py
Labels: api: bigquery, size: l

#1527 feat: set vscode and jupyter environments in the BQ jobs
  bigframes/session/clients.py
  bigframes/session/environment.py
  tests/unit/session/test_clients.py
Labels: api: bigquery, size: m

#1541 feat!: set `allow_large_results=False` by default
  bigframes/_config/bigquery_options.py
  tests/system/small/test_progress_bar.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: s

#1537 feat!: make `remote_function` params keyword-only, and default service account explicit
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  notebooks/apps/synthetic_data_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/location/regionalized.ipynb
  notebooks/remote_functions/remote_function.ipynb
  notebooks/remote_functions/remote_function_usecases.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  samples/snippets/remote_function.py
  tests/system/large/functions/test_remote_function.py
  tests/system/small/functions/test_remote_function.py
  tests/unit/functions/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#1544 feat!: change default ingress setting for `remote_function` to internal-only
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1555 chore: add blob docs link in toc.yml
  docs/templates/toc.yml
Labels: api: bigquery, size: xs

#1551 chore: remove usage of deleted requirements.txt from nightly pipeline
  .kokoro/release-nightly.sh
Labels: api: bigquery, size: xs

#1558 feat!: support gemini-2.0-X, change default llm model to gemini-2.0-flash-001, remove PaLM2TextGenerator and PaLM2TextEmbeddingGenerator
  bigframes/ml/llm.py
  bigframes/ml/loader.py
  notebooks/generative_ai/bq_dataframes_llm_gemini_2.ipynb
  notebooks/ml/bq_dataframes_ml_cross_validation.ipynb
  notebooks/ml/easy_linear_regression.ipynb
  samples/snippets/gen_ai_model_test.py
  samples/snippets/text_generation_test.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_llm.py
  tests/system/small/ml/test_register.py
Labels: api: bigquery, size: xl

#1550 feat: support bq connection path format
  bigframes/clients.py
  bigframes/functions/_function_session.py
  bigframes/operations/blob.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_remote_function.py
  tests/system/small/functions/test_remote_function.py
  tests/unit/test_clients.py
Labels: api: bigquery, size: l

#1554 feat: support bigquery connection in managed function
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  tests/system/conftest.py
  tests/system/large/functions/test_managed_function.py
Labels: api: bigquery, size: m

#1542 feat!: drop support for locational endpoints
  bigframes/_config/bigquery_options.py
  bigframes/constants.py
  bigframes/session/clients.py
  tests/system/large/test_location.py
Labels: api: bigquery, size: m

#1560 feat: allow `input_types`, `output_type`, and `dataset` to be used positionally in `remote_function`
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/functions/test_remote_function.py
Labels: api: bigquery, size: m

#1548 fix: pandas.cut returns labels index for numeric breaks when labels=False
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/reshape/tile.py
  bigframes/operations/aggregations.py
  tests/system/small/test_pandas.py
Labels: api: bigquery, size: l

#1557 docs: add warning for bigframes 2.0
  README.rst
Labels: api: bigquery, size: s

#1563 docs: add message to remove default model for version 3.0
  README.rst
Labels: api: bigquery, size: xs

#1562 docs: correct model deprecation warning for gemini text generator
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: s

#1559 feat: Add component to manage temporary tables
  bigframes/session/bigquery_session.py
  tests/system/small/test_bq_sessions.py
  tests/unit/test_daemon.py
Labels: api: bigquery, size: l

#1547 build: update google-cloud-bigquery to 3.31.0 to support JSON when `allow_large_results=False`
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/bigquery/test_json.py
  tests/system/small/blob/test_properties.py
  tests/system/small/ml/test_llm.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_series.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1549 feat: allow pandas.cut 'labels' parameter to accept a list of strings
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/reshape/tile.py
  bigframes/operations/aggregations.py
  tests/system/small/test_pandas.py
  tests/unit/test_pandas.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
Labels: api: bigquery, size: m

#1564 fix: include role and service account in IAM exception
  bigframes/clients.py
Labels: api: bigquery, size: xs

#1568 fix: prevent `KeyError` in `bpd.concat` with empty DF and struct/array types DF
  bigframes/core/compile/ibis_types.py
  tests/system/conftest.py
  tests/system/small/test_pandas.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: s

#1572 fix: `to_pandas_batches()` respects `page_size` and `max_results` again
  .pre-commit-config.yaml
  bigframes/session/_io/bigquery/__init__.py
  noxfile.py
  tests/system/load/test_large_tables.py
  tests/system/small/test_bq_sessions.py
  tests/system/small/test_dataframe_io.py
Labels: api: bigquery, size: m

#1566 chore: add `include_internal_calls` param to logger
  bigframes/core/log_adapter.py
  tests/unit/core/test_log_adapter.py
Labels: api: bigquery, size: m

#1574 refactor: remove unused llm consts
  bigframes/ml/llm.py
Labels: api: bigquery, size: xs

#1553 refactor: move window logic to window/rolling.py
  bigframes/core/window/__init__.py
  bigframes/core/window/rolling.py
Labels: api: bigquery, size: m
