Repository googleapis/python-bigquery-dataframes, pull requests merged in 2025-01, with the labels that each got.

#1245 fix: reduce the number of labels added to query jobs
  bigframes/core/log_adapter.py
  bigframes/session/__init__.py
  tests/unit/core/test_log_adapter.py
  tests/unit/session/test_io_bigquery.py
Labels: api: bigquery, size: s

#1246 docs: update `bigframes.pandas.DatetimeMethods` docstrings
  third_party/bigframes_vendored/pandas/core/arrays/datetimelike.py
Labels: api: bigquery, size: s

#1252 fix: raise if trying to change `ordering_mode` after session has started
  bigframes/_config/bigquery_options.py
  tests/unit/_config/test_bigquery_options.py
Labels: api: bigquery, size: m

#1254 docs: Update semantic_operators.ipynb
  notebooks/experimental/semantic_operators.ipynb
Labels: api: bigquery, size: xs

#1251 feat: implement confirmation threshold for semantic operators
  bigframes/_config/compute_options.py
  bigframes/exceptions.py
  bigframes/operations/semantics.py
  notebooks/experimental/semantic_operators.ipynb
  tests/system/large/operations/test_semantics.py
Labels: api: bigquery, size: xl

#1258 docs: remove bq studio link
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/getting_started/bq_dataframes_template.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
Labels: api: bigquery, size: m

#1244 chore: fix wordings of Gemini max_retries
  bigframes/ml/llm.py
Labels: api: bigquery, size: s

#1260 docs: Update semantic_operators.ipynb
  notebooks/experimental/semantic_operators.ipynb
Labels: api: bigquery, size: xl

#1256 chore: add experimental blob.image_blur function
  bigframes/blob/_functions.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1259 feat: add max_retries to TextEmbeddingGenerator and Claude3TextGenerator
  bigframes/ml/base.py
  bigframes/ml/llm.py
  tests/system/small/ml/test_llm.py
Labels: api: bigquery, size: l

#1079 test: read_gbp works when table and column share a name
  tests/system/small/test_session.py
Labels: automerge, api: bigquery, size: s

#1266 docs: add bq studio links that allows users to generate Jupiter notebooks in bq studio with github contents
  notebooks/experimental/semantic_operators.ipynb
  notebooks/generative_ai/bq_dataframes_llm_code_generation.ipynb
  notebooks/generative_ai/bq_dataframes_llm_kmeans.ipynb
  notebooks/generative_ai/bq_dataframes_ml_drug_name_generation.ipynb
  notebooks/getting_started/bq_dataframes_template.ipynb
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/getting_started/ml_fundamentals_bq_dataframes.ipynb
  notebooks/ml/bq_dataframes_ml_linear_regression.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  notebooks/visualization/bq_dataframes_covid_line_graphs.ipynb
Labels: api: bigquery, size: l

#1247 docs: update `bigframes.pandas.pandas` docstrings
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  third_party/bigframes_vendored/pandas/core/reshape/encoding.py
  third_party/bigframes_vendored/pandas/core/reshape/merge.py
  third_party/bigframes_vendored/pandas/core/reshape/tile.py
  third_party/bigframes_vendored/pandas/core/tools/datetimes.py
  third_party/bigframes_vendored/pandas/io/gbq.py
  third_party/bigframes_vendored/pandas/io/parsers/readers.py
Labels: api: bigquery, size: m

#1182 chore: update comments and tests for label counts.
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/__init__.py
  bigframes/session/executor.py
  bigframes/session/loader.py
  tests/system/small/test_session.py
  tests/unit/session/test_io_bigquery.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#1262 feat: Support DataFrame.astype(dict)
  bigframes/dataframe.py
  bigframes/dtypes.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: m

#1268 docs: add snippet to see the ARIMA coefficients in the Forecast a single time series with a univariate model tutorial
  samples/snippets/create_single_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: s

#1265 feat: bigframes.bigquery.parse_json
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/json.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/utils.py
  bigframes/operations/__init__.py
  bigframes/operations/blob.py
  tests/system/small/bigquery/test_json.py
Labels: api: bigquery, size: m

#1275 chore: rename snippet
  samples/snippets/create_single_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: xs

#1276 chore: add experimental image blob preview in DataFrame._repr_html_
  bigframes/dataframe.py
Labels: api: bigquery, size: s

#1274 chore: add _test to file name
  samples/snippets/create_multiple_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: xs

#1267 docs: add snippet to evaluate ARIMA plus model in the Forecast a single time series with a univariate model tutorial
  samples/snippets/create_single_timeseries_forecasting_model_test.py
  tests/unit/core/test_dtypes.py
  third_party/bigframes_vendored/ibis/backends/bigquery/datatypes.py
Labels: samples, api: bigquery, size: s

#1279 chore: add experimental blob.image_blur() dst as folder
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1278 deps: remove sqlglot upper bound
  setup.py
Labels: api: bigquery, size: s

#1163 fix: Fix erroneous window bounds removal during compilation
  bigframes/core/block_transforms.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/operations/aggregations.py
  tests/system/small/test_unordered.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
  third_party/bigframes_vendored/ibis/backends/sql/rewrites.py
  third_party/bigframes_vendored/ibis/expr/operations/window.py
Labels: api: bigquery, size: l

#1280 fix: avoid global mutation in `BigQueryOptions.client_endpoints_override`
  bigframes/_config/bigquery_options.py
Labels: api: bigquery, size: xs

#1281 chore: format warning message
  bigframes/_config/bigquery_options.py
  bigframes/_config/experiment_options.py
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/polars/__init__.py
  bigframes/core/global_session.py
  bigframes/core/indexers.py
  bigframes/core/utils.py
  bigframes/dataframe.py
  bigframes/functions/_remote_function_session.py
  bigframes/functions/remote_function.py
  bigframes/ml/base.py
  bigframes/ml/llm.py
  bigframes/ml/remote.py
  bigframes/operations/_matplotlib/core.py
  bigframes/operations/semantics.py
  bigframes/session/__init__.py
  bigframes/session/_io/bigquery/read_gbq_table.py
  bigframes/session/executor.py
  bigframes/streaming/dataframe.py
  notebooks/generative_ai/large_language_models.ipynb
  notebooks/streaming/streaming_dataframe.ipynb
  noxfile.py
  tests/unit/_config/test_experiment_options.py
Labels: api: bigquery, size: l

#1285 fix: dataframe sort_values Series input now raises keyerror.
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
Labels: api: bigquery, size: s

#1283 chore: test with latest sqlglot in prerelease tests
  noxfile.py
  setup.py
  testing/constraints-3.9.txt
Labels: api: bigquery, size: s

#1271 docs: add snippet to forecast future time series in the Forecast a single time series with a univariate model tutorial
  samples/snippets/create_single_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: s

#1269 chore: unimplemented API tracking
  bigframes/core/log_adapter.py
  bigframes/dataframe.py
  bigframes/series.py
  tests/unit/core/test_log_adapter.py
Labels: api: bigquery, size: m

#1057 feat: support array output in `remote_function`
  bigframes/clients.py
  bigframes/core/compile/ibis_types.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/functions/_remote_function_client.py
  bigframes/functions/_remote_function_session.py
  bigframes/functions/_utils.py
  bigframes/functions/remote_function.py
  bigframes/functions/remote_function_template.py
  bigframes/operations/__init__.py
  bigframes/pandas/io/api.py
  bigframes/series.py
  bigframes/session/__init__.py
  scripts/manage_cloud_functions.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  tests/unit/core/test_dtypes.py
  tests/unit/functions/test_remote_function_utils.py
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: l

#1286 chore: add logger to Semantics class.
  bigframes/core/log_adapter.py
  bigframes/operations/semantics.py
Labels: api: bigquery, size: s

#1291 chore: add experimental blob.display to support audio and video
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1284 refactor: Make row hash ordering explicit in tree
  bigframes/bigquery/_operations/search.py
  bigframes/core/__init__.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/default_ordering.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/compile/single_column.py
  bigframes/core/expression.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/operations/__init__.py
  bigframes/session/__init__.py
  bigframes/session/loader.py
  tests/system/small/bigquery/test_vector_search.py
  tests/system/small/test_null_index.py
  tests/system/small/test_session.py
Labels: api: bigquery, size: m

#1290 refactor: move operator definitions from __init__.py to separate files
  bigframes/operations/__init__.py
  bigframes/operations/array_ops.py
  bigframes/operations/base_ops.py
  bigframes/operations/blob_ops.py
  bigframes/operations/bool_ops.py
  bigframes/operations/comparison_ops.py
  bigframes/operations/date_ops.py
  bigframes/operations/datetime_ops.py
  bigframes/operations/distance_ops.py
  bigframes/operations/frequency_ops.py
  bigframes/operations/generic_ops.py
  bigframes/operations/geo_ops.py
  bigframes/operations/json_ops.py
  bigframes/operations/numeric_ops.py
  bigframes/operations/numpy_op_maps.py
  bigframes/operations/remote_function_ops.py
  bigframes/operations/string_ops.py
  bigframes/operations/struct_ops.py
  bigframes/operations/time_ops.py
Labels: api: bigquery, size: xl

#1273 docs: update `bigframes.pandas.Series` docs
  third_party/bigframes_vendored/pandas/core/frame.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: xl

#1294 fix: series sort_index and sort_values now raises when axis!=0
  bigframes/series.py
Labels: api: bigquery, size: xs

#1299 chore: fix experimental blob operations json string values
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dataframe.py
  bigframes/operations/__init__.py
  bigframes/operations/blob.py
  bigframes/operations/json_ops.py
Labels: api: bigquery, size: m

#1293 feat: add `bigframes.bigquery.sql_scalar()` to apply SQL syntax on Series objects
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/sql.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/core/sql.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/generic_ops.py
  notebooks/getting_started/bq_dataframes_template.ipynb
  tests/system/small/bigquery/test_sql.py
  tests/unit/core/test_sql.py
  tests/unit/session/test_io_bigquery.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/base.py
  third_party/bigframes_vendored/ibis/expr/operations/generic.py
Labels: api: bigquery, size: l

#1300 chore: add experimental blob metadata functions
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1174 fix: fix read_gbq_function issue in dataframe apply method
  bigframes/dataframe.py
  tests/system/small/test_remote_function.py
Labels: api: bigquery, size: s

#1298 refactor: Simplify expression generation for some block ops
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/dataframe.py
Labels: api: bigquery, size: m

#1303 feat: DataFrame.join supports Series other
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: s

#1297 feat: add unix_seconds, unix_millis and unix_micros for timestamp series.
  bigframes/bigquery/__init__.py
  bigframes/bigquery/_operations/datetime.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/operations/__init__.py
  bigframes/operations/datetime_ops.py
  tests/system/small/bigquery/test_datetime.py
Labels: api: bigquery, size: m

#1306 chore: fix experimental blob _repr_html_ only previews image content type
  bigframes/dataframe.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: s

#1304 refactor: Generalize Block.aggregate to non-unary aggregates
  bigframes/core/block_transforms.py
  bigframes/core/blocks.py
  bigframes/core/groupby/__init__.py
  bigframes/series.py
Labels: api: bigquery, size: m

#1308 chore: add experimental blob read and write URL functions
  bigframes/dataframe.py
  bigframes/operations/blob.py
Labels: api: bigquery, size: m

#1302 feat: Add DataFrame.mask method
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#1295 refactor: Make window op node support non-unary ops
  bigframes/core/__init__.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/polars/compiler.py
  bigframes/core/nodes.py
  bigframes/operations/aggregations.py
Labels: api: bigquery, size: m

#1314 chore: keep gemini code commented out in the notebook template
  notebooks/getting_started/bq_dataframes_template.ipynb
Labels: api: bigquery, size: l

#1301 refactor: ReadLocal and Explode nodes support offset outputs
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/explode.py
  bigframes/core/nodes.py
Labels: api: bigquery, size: l

#1139 feat!: Enable reading JSON data with `dbjson` extension dtype
  bigframes/bigquery/_operations/json.py
  bigframes/core/__init__.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/operations/json_ops.py
  bigframes/session/_io/pandas.py
  setup.py
  testing/constraints-3.9.txt
  tests/system/small/bigquery/test_json.py
  tests/system/small/test_dataframe_io.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: l

#1319 chore: fix experimental blob video display in IPython 7.x
  bigframes/operations/blob.py
Labels: api: bigquery, size: xs

#1315 feat: Add DataFrame.corrwith method
  bigframes/core/blocks.py
  bigframes/core/expression.py
  bigframes/dataframe.py
  tests/system/small/test_dataframe.py
  third_party/bigframes_vendored/pandas/core/frame.py
Labels: api: bigquery, size: m

#1320 feat: (df|s).hist(), (df|s).line(), (df|s).area(), (df|s).bar(), df.scatter()
  bigframes/dataframe.py
  bigframes/series.py
  tests/system/small/operations/test_plotting.py
Labels: api: bigquery, size: m

#1312 refactor: rename the bigframes function files
  bigframes/dataframe.py
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/functions/function.py
  bigframes/functions/function_template.py
  bigframes/pandas/__init__.py
  bigframes/session/__init__.py
  tests/system/large/test_remote_function.py
  tests/system/small/test_remote_function.py
  tests/system/utils.py
  tests/unit/functions/test_function_template.py
  tests/unit/polars_session.py
  tests/unit/test_remote_function.py
Labels: api: bigquery, size: m

#1317 chore: define timedelta type and to_timedelta function
  bigframes/core/compile/ibis_types.py
  bigframes/core/compile/scalar_op_compiler.py
  bigframes/dtypes.py
  bigframes/operations/__init__.py
  bigframes/operations/timedelta_ops.py
  bigframes/pandas/__init__.py
  bigframes/pandas/core/__init__.py
  bigframes/pandas/core/api.py
  bigframes/pandas/core/tools/__init__.py
  bigframes/pandas/core/tools/timedeltas.py
  tests/system/small/test_pandas.py
  third_party/bigframes_vendored/pandas/core/tools/timedeltas.py
Labels: api: bigquery, size: l

#1328 chore: Amend tpch q8 to reduce join
  third_party/bigframes_vendored/tpch/queries/q8.py
Labels: api: bigquery, size: s

#1325 chore: update tpch benchmark to use to_pandas_batch
  scripts/tpch_result_verify.py
  third_party/bigframes_vendored/tpch/queries/q1.py
  third_party/bigframes_vendored/tpch/queries/q10.py
  third_party/bigframes_vendored/tpch/queries/q11.py
  third_party/bigframes_vendored/tpch/queries/q12.py
  third_party/bigframes_vendored/tpch/queries/q13.py
  third_party/bigframes_vendored/tpch/queries/q14.py
  third_party/bigframes_vendored/tpch/queries/q15.py
  third_party/bigframes_vendored/tpch/queries/q16.py
  third_party/bigframes_vendored/tpch/queries/q17.py
  third_party/bigframes_vendored/tpch/queries/q18.py
  third_party/bigframes_vendored/tpch/queries/q2.py
  third_party/bigframes_vendored/tpch/queries/q20.py
  third_party/bigframes_vendored/tpch/queries/q21.py
  third_party/bigframes_vendored/tpch/queries/q22.py
  third_party/bigframes_vendored/tpch/queries/q3.py
  third_party/bigframes_vendored/tpch/queries/q4.py
  third_party/bigframes_vendored/tpch/queries/q5.py
  third_party/bigframes_vendored/tpch/queries/q6.py
  third_party/bigframes_vendored/tpch/queries/q7.py
  third_party/bigframes_vendored/tpch/queries/q8.py
  third_party/bigframes_vendored/tpch/queries/q9.py
Labels: api: bigquery, size: s

#1311 feat: allow case_when to change dtypes if case list contains the condition True
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#1329 chore: filter internal calls.
  bigframes/core/log_adapter.py
  tests/unit/core/test_log_adapter.py
Labels: api: bigquery, size: s

#1324 chore: add experiment blob read_gbq_object_table
  bigframes/pandas/__init__.py
  bigframes/pandas/io/api.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: s

#1321 refactor: Preprocess expression trees to pull up ordering
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/aggregate_compiler.py
  bigframes/core/compile/api.py
  bigframes/core/compile/compiled.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/concat.py
  bigframes/core/compile/explode.py
  bigframes/core/compile/single_column.py
  bigframes/core/groupby/__init__.py
  bigframes/core/nodes.py
  bigframes/core/ordering.py
  bigframes/core/rewrite/__init__.py
  bigframes/core/rewrite/order.py
  bigframes/core/window_spec.py
  bigframes/operations/aggregations.py
  noxfile.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/bigquery/__init__.py
Labels: api: bigquery, size: xl

#1332 chore: document permissions for experimental session.from_glob_path
  bigframes/session/__init__.py
Labels: api: bigquery, size: xs

#1282 feat: support time_series_id_col in ARIMAPlus
  bigframes/ml/base.py
  bigframes/ml/core.py
  bigframes/ml/forecasting.py
  tests/data/time_series.jsonl
  tests/data/time_series_schema.json
  tests/system/conftest.py
  tests/system/large/ml/test_forecasting.py
  tests/system/small/ml/conftest.py
  tests/system/small/ml/test_core.py
  tests/system/small/ml/test_forecasting.py
Labels: api: bigquery, size: xl

#1333 chore: fix ibis reference in bigframes_vendored
  third_party/bigframes_vendored/ibis/expr/types/core.py
Labels: api: bigquery, size: xs

#1334 chore: fix experimental blob to create connections if not exist
  bigframes/ml/llm.py
  bigframes/ml/remote.py
  bigframes/operations/strings.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#1335 chore: fix experimental blob ObjRefDtype
  bigframes/dtypes.py
Labels: api: bigquery, size: xs

#1272 docs: add snippet to explain the univariate model's forecast result in the Forecast a single time series with a univariate model tutorial
  samples/snippets/create_multiple_timeseries_forecasting_model_test.py
  samples/snippets/create_single_timeseries_forecasting_model_test.py
Labels: samples, api: bigquery, size: s

#1307 deps: Add support for Python 3.13 for everything but remote functions
  .github/workflows/unittest.yml
  CONTRIBUTING.rst
  bigframes/core/expression.py
  bigframes/session/__init__.py
  notebooks/getting_started/getting_started_bq_dataframes.ipynb
  notebooks/location/regionalized.ipynb
  notebooks/remote_functions/remote_function.ipynb
  notebooks/remote_functions/remote_function_usecases.ipynb
  notebooks/remote_functions/remote_function_vertex_claude_model.ipynb
  noxfile.py
  owlbot.py
  scripts/test_publish_api_coverage.py
  setup.py
  tests/system/large/test_remote_function.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: m

#1203 perf: Improve isin performance
  bigframes/core/__init__.py
  bigframes/core/blocks.py
  bigframes/core/compile/compiler.py
  bigframes/core/compile/isin.py
  bigframes/core/nodes.py
  bigframes/core/rewrite/implicit_align.py
  bigframes/core/rewrite/legacy_align.py
  bigframes/core/rewrite/order.py
  tests/system/small/test_series.py
Labels: api: bigquery, size: l

#1337 chore: fix experimental blob repr without content_type
  bigframes/dataframe.py
Labels: api: bigquery, size: xs

#1323 refactor: rename the bigframes function classes
  bigframes/functions/_function_client.py
  bigframes/functions/_function_session.py
  bigframes/functions/_utils.py
  bigframes/functions/function.py
  bigframes/session/__init__.py
Labels: api: bigquery, size: m

#1339 chore: update tpch q20
  third_party/bigframes_vendored/tpch/queries/q20.py
Labels: api: bigquery, size: xs

#1340 test: skip checking llm tuning score labels
  tests/system/small/ml/test_llm.py
  tests/system/utils.py
Labels: api: bigquery, size: s

#1336 refactor: Remove filter deferment from IR
  bigframes/core/compile/compiled.py
  third_party/bigframes_vendored/ibis/backends/sql/compilers/base.py
Labels: api: bigquery, size: m

#1342 feat: Add Series.keys()
  bigframes/series.py
  tests/system/small/test_series.py
  third_party/bigframes_vendored/pandas/core/series.py
Labels: api: bigquery, size: s

#1316 feat: Support python type as astype arg
  bigframes/core/blocks.py
  bigframes/core/compile/ibis_types.py
  bigframes/core/indexes/base.py
  bigframes/core/local_data.py
  bigframes/dataframe.py
  bigframes/dtypes.py
  bigframes/operations/base.py
  bigframes/operations/generic_ops.py
  bigframes/series.py
  bigframes/session/__init__.py
  tests/system/small/test_dataframe.py
  tests/system/small/test_index.py
  tests/system/small/test_series.py
  tests/unit/core/test_dtypes.py
  tests/unit/core/test_expression.py
  third_party/bigframes_vendored/pandas/core/generic.py
  third_party/bigframes_vendored/pandas/core/indexes/base.py
Labels: api: bigquery, size: m

#1343 chore: add type checks for unix epoch conversions
  bigframes/operations/datetime_ops.py
  tests/system/small/bigquery/test_datetime.py
Labels: api: bigquery, size: s

#1345 chore: add a new metric
  bigframes/session/metrics.py
  scripts/run_and_publish_benchmark.py
Labels: api: bigquery, size: s
